Cataclysm BN: src/achievement.cpp File Reference
achievement.cpp File Reference
#include "achievement.h"
#include <cassert>
#include <cstdlib>
#include <set>
#include <tuple>
#include <utility>
#include "character.h"
#include "color.h"
#include "debug.h"
#include "enums.h"
#include "event.h"
#include "event_statistics.h"
#include "game.h"
#include "generic_factory.h"
#include "json.h"
#include "kill_tracker.h"
#include "monstergenerator.h"
#include "skill.h"
#include "stats_tracker.h"
#include "string_formatter.h"
Classes
struct achievement_requirement
class requirement_watcher
Namespaces
namespace anonymous_namespace{achievement.cpp}
namespace io
Functions
template<>
std::string io::enum_to_string< achievement_comparison > (achievement_comparison data)
template<>
std::string io::enum_to_string< achievement::time_bound::epoch > (achievement::time_bound::epoch data)
static nc_color color_from_completion (achievement_completion comp)
static time_point epoch_to_time_point (achievement::time_bound::epoch e)
achievement_completion time_req_completed (const achievement &ach)
Checks if time requirements for achievements are satisfied, have failed, or are pending.
achievement_completion kill_req_completed (const achievement &ach, const kill_tracker &kt)
Checks if kill requirements for achievements are satisfied, have failed, or are pending.
achievement_completion skill_req_completed (const achievement &ach)
Checks if skill requirements for achievements are satisfied, or are pending.
bool ach_compare (const achievement_comparison symbol, const int target, const int to_compare)
Uses comparator supplied to compare target and supplied value.
static std::string text_for_requirement (const achievement_requirement &req, const cata_variant &current_value)
template<>
std::string io::enum_to_string< achievement_completion > (achievement_completion data)
Variables
generic_factory< achievement > anonymous_namespace{achievement.cpp}::achievement_factory ("achievement")
Function Documentation
ach_compare()
bool ach_compare (const achievement_comparison symbol, const int target, const int to_compare)
Uses comparator supplied to compare target and supplied value.
Only works on integers.
Definition at line 400 of file achievement.cpp.
{
    switch( symbol ) {
        case achievement_comparison::greater_equal:
            return to_compare >= target;
        case achievement_comparison::less_equal:
            return to_compare <= target;
        case achievement_comparison::anything:
            return true;
        case achievement_comparison::last:
            return true;
        default:
            return false;
    }
}
References anything, greater_equal, last, less_equal, and symbol().
Referenced by kill_req_completed(), achievement::kill_ui_text(), skill_req_completed(), and achievement::skill_ui_text().
color_from_completion()
static nc_color color_from_completion (achievement_completion comp) static
Definition at line 111 of file achievement.cpp.
{
    switch( comp ) {
        case achievement_completion::pending:
            return c_yellow;
        case achievement_completion::completed:
            return c_light_green;
        case achievement_completion::failed:
            return c_light_gray;
        case achievement_completion::last:
            break;
    }
    debugmsg( "Invalid achievement_completion" );
    abort();
}
References abort, c_light_gray, c_light_green, c_yellow, completed, debugmsg, failed, last, and pending.
Referenced by achievement::kill_ui_text(), achievement::skill_ui_text(), achievement::time_bound::time_ui_text(), achievement_tracker::ui_text(), and achievement_state::ui_text().
epoch_to_time_point()
static time_point epoch_to_time_point (achievement::time_bound::epoch e) static
Definition at line 184 of file achievement.cpp.
{
    switch( e ) {
        case achievement::time_bound::epoch::cataclysm:
            return calendar::start_of_cataclysm;
        case achievement::time_bound::epoch::game_start:
            return calendar::start_of_game;
        case achievement::time_bound::epoch::last:
            break;
    }
    debugmsg( "Invalid epoch" );
    abort();
}
References abort, achievement::time_bound::cataclysm, debugmsg, achievement::time_bound::game_start, achievement::time_bound::last, calendar::start_of_cataclysm, and calendar::start_of_game.
Referenced by achievement::time_bound::target().
kill_req_completed()
achievement_completion kill_req_completed (const achievement & ach, const kill_tracker & kt)
Checks if kill requirements for achievements are satisfied, have failed, or are pending.
Definition at line 311 of file achievement.cpp.
{
    const std::map<mtype_id, std::pair<achievement_comparison, int>> &kill_reqs =
                ach.kill_requirements();
    const std::map<species_id, std::pair<achievement_comparison, int>> &species_kill_reqs =
                ach.species_kill_requirements();
    if( kill_reqs.empty() && species_kill_reqs.empty() ) {
        return achievement_completion::completed;
    }
    achievement_completion satisfied = achievement_completion::completed;
    for( const auto& [m_id, pair] : kill_reqs ) {
        if( satisfied == achievement_completion::failed ) {
            break;
        }
        auto& [comp, count] = pair;
        int kill_count = m_id == mtype_id::NULL_ID() ? kt.monster_kill_count() :
                         kt.kill_count( m_id );
        if( !ach_compare( comp, count, kill_count ) ) {
            switch( comp ) {
                case achievement_comparison::greater_equal:
                    // Still might reach target, check for other fail conditions.
                    satisfied = achievement_completion::pending;
                    break;
                case achievement_comparison::less_equal:
                    // Can't reduce kill count.
                    satisfied = achievement_completion::failed;
                    break;
                default:
                    break;
            }
        }
    }
    for( const auto& [fac_id, pair] : species_kill_reqs ) {
        if( satisfied == achievement_completion::failed ) {
            break;
        }
        auto& [comp, count] = pair;
        int kill_count = kt.kill_count( fac_id );
        if( !ach_compare( comp, count, kill_count ) ) {
            switch( comp ) {
                case achievement_comparison::greater_equal:
                    // Still might reach target, check for other fail conditions.
                    satisfied = achievement_completion::pending;
                    break;
                case achievement_comparison::less_equal:
                    // Can't reduce kill count.
                    satisfied = achievement_completion::failed;
                    break;
                default:
                    break;
            }
        }
    }
    return satisfied;
}
References ach_compare(), completed, detail::count(), failed, greater_equal, kill_tracker::kill_count(), achievement::kill_requirements(), less_equal, kill_tracker::monster_kill_count(), string_id< mtype >::NULL_ID(), pending, and achievement::species_kill_requirements().
Referenced by achievement_tracker::has_failed(), and achievement_tracker::set_requirement().
skill_req_completed()
achievement_completion skill_req_completed (const achievement & ach)
Checks if skill requirements for achievements are satisfied, or are pending.
Definition at line 368 of file achievement.cpp.
{
    const std::map<skill_id, std::pair<achievement_comparison, int>> &skill_reqs =
                ach.skill_requirements();
    if( skill_reqs.empty() ) {
        return achievement_completion::completed;
    }
    Character &u = get_player_character();
    achievement_completion satisfied = achievement_completion::completed;
    for( const auto& [sk_id, pair] : skill_reqs ) {
        auto& [comp, level] = pair;
        int skill_level = u.get_skill_level( sk_id );
        if( !ach_compare( comp, level, skill_level ) ) {
            switch( comp ) {
                case achievement_comparison::greater_equal:
                    // Still might reach target, check for other fail conditions.
                    satisfied = achievement_completion::pending;
                    break;
                case achievement_comparison::less_equal:
                    // Skill level can technically be reduced by rust, but should
                    // still fail.
                    satisfied = achievement_completion::failed;
                    break;
                default:
                    break;
            }
        }
    }
    return satisfied;
}
References ach_compare(), completed, failed, get_player_character(), Character::get_skill_level(), greater_equal, less_equal, pending, and achievement::skill_requirements().
Referenced by achievement_tracker::has_failed(), and achievement_tracker::set_requirement().
text_for_requirement()
static std::string text_for_requirement (const achievement_requirement & req, const cata_variant & current_value) static
Definition at line 739 of file achievement.cpp.
{
    bool is_satisfied = req.satisifed_by( current_value );
    nc_color c = is_satisfied ? c_green : c_yellow;
    int current = current_value.get<int>();
    int target;
    std::string result;
    if( req.comparison == achievement_comparison::anything ) {
        target = 1;
        result = string_format( _( "Triggered by " ) );
    } else {
        target = req.target;
        result = string_format( _( "%s/%s " ), current, target );
    }
    result += req.statistic->description().translated( target );
    return colorize( result, c );
}
References _, anything, c, c_green, c_yellow, colorize(), achievement_requirement::comparison, cata_variant::get(), achievement_requirement::satisifed_by(), achievement_requirement::statistic, string_format(), and achievement_requirement::target.
Referenced by requirement_watcher::ui_text(), and achievement_state::ui_text().
time_req_completed()
achievement_completion time_req_completed (const achievement & ach)
Checks if time requirements for achievements are satisfied, have failed, or are pending.
Definition at line 280 of file achievement.cpp.
{
    if( !ach.time_constraint() ) {
        return achievement_completion::completed;
    }
    const std::optional<achievement::time_bound> &time_req = ach.time_constraint();
    time_point now = calendar::turn;
    switch( time_req->comparison() ) {
        case achievement_comparison::less_equal:
            if( now <= time_req->target() ) {
                return achievement_completion::completed;
            } else {
                return achievement_completion::failed;
            }
        case achievement_comparison::greater_equal:
            if( now >= time_req->target() ) {
                return achievement_completion::completed;
            } else {
                return achievement_completion::pending;
            }
        case achievement_comparison::anything:
            return achievement_completion::completed;
        case achievement_comparison::last:
            break;
    }
    debugmsg( "Invalid achievement_comparison" );
    abort();
}
References completed, and achievement::time_constraint().
Referenced by achievement_tracker::has_failed(), achievement_tracker::set_requirement(), and achievement::ui_text().