Cataclysm BN: src/achievement.h File Reference
achievement.h File Reference
#include <array>
#include <functional>
#include <memory>
#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include "calendar.h"
#include "cata_variant.h"
#include "event_bus.h"
#include "string_id.h"
#include "translations.h"
Classes
struct enum_traits< achievement_comparison >
struct enum_traits< achievement_completion >
class achievement
class achievement::time_bound
struct enum_traits< achievement::time_bound::epoch >
struct achievement_state
class achievement_tracker
class achievements_tracker
Namespaces
namespace cata
Enumerations
enum class achievement_comparison { less_equal , greater_equal , anything , last }
enum class achievement_completion { pending , completed , failed , last }
Functions
achievement_completion time_req_completed (const achievement &ach)
Checks if time requirements for achievements are satisfied, have failed, or are pending.
achievement_completion kill_req_completed (const achievement &ach, const kill_tracker &kt)
Checks if kill requirements for achievements are satisfied, have failed, or are pending.
achievement_completion skill_req_completed (const achievement &ach)
Checks if skill requirements for achievements are satisfied, or are pending.
bool ach_compare (const achievement_comparison symbol, const int target, const int to_compare)
Uses comparator supplied to compare target and supplied value.
Enumeration Type Documentation
achievement_comparison
enum class achievement_comparison strong
Enumerator
less_equal
greater_equal
anything
last
Definition at line 33 of file achievement.h.
{
    less_equal,
    greater_equal,
    anything,
    last,
};
achievement_completion
enum class achievement_completion strong
Enumerator
pending
completed
failed
last
Definition at line 45 of file achievement.h.
{
    pending,
    completed,
    failed,
    last
};
Function Documentation
ach_compare()
bool ach_compare (const achievement_comparison symbol, const int target, const int to_compare)
Uses comparator supplied to compare target and supplied value.
Only works on integers.
Definition at line 400 of file achievement.cpp.
{
    switch( symbol ) {
        case achievement_comparison::greater_equal:
            return to_compare >= target;
        case achievement_comparison::less_equal:
            return to_compare <= target;
        case achievement_comparison::anything:
            return true;
        case achievement_comparison::last:
            return true;
        default:
            return false;
    }
}
References anything, greater_equal, last, less_equal, and symbol().
Referenced by kill_req_completed(), achievement::kill_ui_text(), skill_req_completed(), and achievement::skill_ui_text().
kill_req_completed()
achievement_completion kill_req_completed (const achievement & ach, const kill_tracker & kt)
Checks if kill requirements for achievements are satisfied, have failed, or are pending.
Definition at line 311 of file achievement.cpp.
{
    const std::map<mtype_id, std::pair<achievement_comparison, int>> &kill_reqs =
                ach.kill_requirements();
    const std::map<species_id, std::pair<achievement_comparison, int>> &species_kill_reqs =
                ach.species_kill_requirements();
    if( kill_reqs.empty() && species_kill_reqs.empty() ) {
        return achievement_completion::completed;
    }
    achievement_completion satisfied = achievement_completion::completed;
    for( const auto& [m_id, pair] : kill_reqs ) {
        if( satisfied == achievement_completion::failed ) {
            break;
        }
        auto& [comp, count] = pair;
        int kill_count = m_id == mtype_id::NULL_ID() ? kt.monster_kill_count() :
                         kt.kill_count( m_id );
        if( !ach_compare( comp, count, kill_count ) ) {
            switch( comp ) {
                case achievement_comparison::greater_equal:
                    // Still might reach target, check for other fail conditions.
                    satisfied = achievement_completion::pending;
                    break;
                case achievement_comparison::less_equal:
                    // Can't reduce kill count.
                    satisfied = achievement_completion::failed;
                    break;
                default:
                    break;
            }
        }
    }
    for( const auto& [fac_id, pair] : species_kill_reqs ) {
        if( satisfied == achievement_completion::failed ) {
            break;
        }
        auto& [comp, count] = pair;
        int kill_count = kt.kill_count( fac_id );
        if( !ach_compare( comp, count, kill_count ) ) {
            switch( comp ) {
                case achievement_comparison::greater_equal:
                    // Still might reach target, check for other fail conditions.
                    satisfied = achievement_completion::pending;
                    break;
                case achievement_comparison::less_equal:
                    // Can't reduce kill count.
                    satisfied = achievement_completion::failed;
                    break;
                default:
                    break;
            }
        }
    }
    return satisfied;
}
References ach_compare(), completed, detail::count(), failed, greater_equal, kill_tracker::kill_count(), achievement::kill_requirements(), less_equal, kill_tracker::monster_kill_count(), string_id< mtype >::NULL_ID(), pending, and achievement::species_kill_requirements().
Referenced by achievement_tracker::has_failed(), and achievement_tracker::set_requirement().
skill_req_completed()
achievement_completion skill_req_completed (const achievement & ach)
Checks if skill requirements for achievements are satisfied, or are pending.
Definition at line 368 of file achievement.cpp.
{
    const std::map<skill_id, std::pair<achievement_comparison, int>> &skill_reqs =
                ach.skill_requirements();
    if( skill_reqs.empty() ) {
        return achievement_completion::completed;
    }
    Character &u = get_player_character();
    achievement_completion satisfied = achievement_completion::completed;
    for( const auto& [sk_id, pair] : skill_reqs ) {
        auto& [comp, level] = pair;
        int skill_level = u.get_skill_level( sk_id );
        if( !ach_compare( comp, level, skill_level ) ) {
            switch( comp ) {
                case achievement_comparison::greater_equal:
                    // Still might reach target, check for other fail conditions.
                    satisfied = achievement_completion::pending;
                    break;
                case achievement_comparison::less_equal:
                    // Skill level can technically be reduced by rust, but should
                    // still fail.
                    satisfied = achievement_completion::failed;
                    break;
                default:
                    break;
            }
        }
    }
    return satisfied;
}
References ach_compare(), completed, failed, get_player_character(), Character::get_skill_level(), greater_equal, less_equal, pending, and achievement::skill_requirements().
Referenced by achievement_tracker::has_failed(), and achievement_tracker::set_requirement().
time_req_completed()
achievement_completion time_req_completed (const achievement & ach)
Checks if time requirements for achievements are satisfied, have failed, or are pending.
Definition at line 280 of file achievement.cpp.
{
    if( !ach.time_constraint() ) {
        return achievement_completion::completed;
    }
    const std::optional<achievement::time_bound> &time_req = ach.time_constraint();
    time_point now = calendar::turn;
    switch( time_req->comparison() ) {
        case achievement_comparison::less_equal:
            if( now <= time_req->target() ) {
                return achievement_completion::completed;
            } else {
                return achievement_completion::failed;
            }
        case achievement_comparison::greater_equal:
            if( now >= time_req->target() ) {
                return achievement_completion::completed;
            } else {
                return achievement_completion::pending;
            }
        case achievement_comparison::anything:
            return achievement_completion::completed;
        case achievement_comparison::last:
            break;
    }
    debugmsg( "Invalid achievement_comparison" );
    abort();
}
References completed, less_equal, achievement::time_constraint(), and calendar::turn.
Referenced by achievement_tracker::has_failed(), achievement_tracker::set_requirement(), and achievement::ui_text().