Cataclysm BN: src/catalua_bindings_utils.h File Reference
catalua_bindings_utils.h File Reference
#include "catalua_luna.h"
#include "json.h"
Macros
#define CATA_SRC_CATALUA_BINDINGS_UTILS_H
#define DOC(x) luna::doc(x)
Functions
template<typename T >
void reg_serde_functions (sol::usertype< T > &ut)
Macro Definition Documentation
CATA_SRC_CATALUA_BINDINGS_UTILS_H
#define CATA_SRC_CATALUA_BINDINGS_UTILS_H
Definition at line 3 of file catalua_bindings_utils.h.
DOC
#define DOC (x) luna::doc(x)
Definition at line 15 of file catalua_bindings_utils.h.
Function Documentation
reg_serde_functions()
template<typename T > void reg_serde_functions (sol::usertype< T > & ut)
Definition at line 9 of file catalua_bindings_utils.h.
{
    luna::set_fx( ut, "serialize", sol::resolve< void( JsonOut & ) const >( &T::serialize ) );
    luna::set_fx( ut, "deserialize", sol::resolve< void( JsonIn & ) >( &T::deserialize ) );
}
References deserialize(), serialize(), and luna::set_fx().