Cataclysm BN: src/character.h File Reference
character.h File Reference
#include <array>
#include <bitset>
#include <climits>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "action.h"
#include "bodypart.h"
#include "calendar.h"
#include "character_id.h"
#include "color.h"
#include "coordinates.h"
#include "creature.h"
#include "cursesdef.h"
#include "damage.h"
#include "enums.h"
#include "enum_int_operators.h"
#include "flat_set.h"
#include "game_constants.h"
#include "inventory.h"
#include "item_handling_util.h"
#include "item.h"
#include "item_location.h"
#include "memory_fast.h"
#include "pimpl.h"
#include "player_activity.h"
#include "pldata.h"
#include "point.h"
#include "ret_val.h"
#include "stomach.h"
#include "string_formatter.h"
#include "type_id.h"
#include "units.h"
#include "visitable.h"
#include "weighted_list.h"
Classes
struct enum_traits< character_movemode >
struct special_attack
struct needs_rates
struct char_trait_data
struct mutation_collection
class Character
struct Character::has_mission_item_filter
Namespaces
namespace vision
namespace warmth
Macros
#define CATA_SRC_CHARACTER_H
Enumerations
enum class vision_modes {
DEBUG_NIGHTVISION , NV_GOGGLES , BIRD_EYE , URSINE_VISION ,
BOOMERED , DARKNESS , IR_VISION , VISION_CLAIRVOYANCE ,
VISION_CLAIRVOYANCE_PLUS , VISION_CLAIRVOYANCE_SUPER , NUM_VISION_MODES
}
enum npc_ai_info : size_t {
ideal_weapon_value = 0 , reloadables , reloadable_cbms , range ,
num_npc_ai_info
}
enum character_movemode : int { CMM_WALK = 0 , CMM_RUN , CMM_CROUCH , CMM_COUNT }
enum class fatigue_levels : int { tired = 191 , dead_tired = 383 , exhausted = 575 , massive = 1000 }
enum class sleep_deprivation_levels : int {
harmless = 2 * 24 * 60 , minor = 3 * 24 * 60 , serious = 4 * 24 * 60 , major = 5 * 24 * 60 ,
massive = 6 * 24 * 60
}
enum class thirst_levels : int {
turgid = INT_MIN , hydrated = 0 , slaked = 60 , thirsty = 120 ,
very_thirsty = 240 , dehydrated = 480 , parched = 600 , dead = 1200
}
enum class edible_rating {
edible , inedible , inedible_mutation , allergy ,
allergy_weak , cannibalism , rotten , nausea ,
bloated , too_full , no_tool
}
enum class rechargeable_cbm { none = 0 , reactor , furnace , other }
Functions
Character & get_player_character ()
float vision::threshold_for_nv_range (float range)
Returns the light level that darkness will have at this range from player.
float vision::nv_range_from_per (int per)
float vision::nv_range_from_eye_encumbrance (int enc)
std::map< bodypart_id, int > warmth::from_clothing (const std::map< bodypart_id, std::vector< const item * > > &clothing_map)
std::map< bodypart_id, int > warmth::bonus_from_clothing (const std::map< bodypart_id, std::vector< const item * > > &clothing_map)
std::map< bodypart_id, int > warmth::from_effects (const Character &c)
std::map< bodypart_id, int > warmth::wind_resistance_from_clothing (const std::map< bodypart_id, std::vector< const item * > > &clothing_map)
Returns wind resistance provided by armor, etc.
bool has_psy_protection (const Character &c, int partial_chance)
Returns true if the player has a psyshield artifact, or sometimes if wearing tinfoil.
int get_speedydex_bonus (const int dex)
Returns value of speedydex bonus if enabled.
Variables
const std::unordered_map< std::string, fatigue_levels > fatigue_level_strs
Macro Definition Documentation
CATA_SRC_CHARACTER_H
#define CATA_SRC_CHARACTER_H
Definition at line 3 of file character.h.
Enumeration Type Documentation
character_movemode
enum character_movemode : int
Enumerator
CMM_WALK
CMM_RUN
CMM_CROUCH
CMM_COUNT
Definition at line 108 of file character.h.
                        : int {
    CMM_WALK = 0,
    CMM_RUN,
    CMM_CROUCH,
    CMM_COUNT
};
edible_rating
enum class edible_rating strong
Enumerator
edible
inedible
inedible_mutation
allergy
allergy_weak
cannibalism
rotten
nausea
bloated
too_full
no_tool
Definition at line 164 of file character.h.
{
    // Edible or we pretend it is
    edible,
    // Not food at all
    inedible,
    // Not food because mutated mouth/system
    inedible_mutation,
    // You can eat it, but it will hurt morale
    allergy,
    // Smaller allergy penalty
    allergy_weak,
    // Cannibalism (unless psycho/cannibal)
    cannibalism,
    // Rotten or not rotten enough (for saprophages)
    rotten,
    // Can provoke vomiting if you already feel nauseous.
    nausea,
    // We did overeat, cramming more will surely cause vomiting.
    bloated,
    // We can eat this, but we'll overeat
    too_full,
    // Some weird stuff that requires a tool we don't have
    no_tool
};
fatigue_levels
enum class fatigue_levels : int strong
Enumerator
tired
dead_tired
exhausted
massive
Definition at line 120 of file character.h.
                          : int {
    tired = 191,
    dead_tired = 383,
    exhausted = 575,
    massive = 1000
};
npc_ai_info
enum npc_ai_info : size_t
Enumerator
ideal_weapon_value
reloadables
reloadable_cbms
range
num_npc_ai_info
Definition at line 100 of file character.h.
                 : size_t {
    ideal_weapon_value = 0,
    reloadables,
    reloadable_cbms,
    range,
    num_npc_ai_info,
};
rechargeable_cbm
enum class rechargeable_cbm strong
Enumerator
none
reactor
furnace
other
Definition at line 189 of file character.h.
{
    none = 0,
    reactor,
    furnace,
    other
};
sleep_deprivation_levels
enum class sleep_deprivation_levels : int strong
Enumerator
harmless
minor
serious
major
massive
Definition at line 139 of file character.h.
                                    : int {
    harmless = 2 * 24 * 60,
    minor = 3 * 24 * 60,
    serious = 4 * 24 * 60,
    major = 5 * 24 * 60,
    massive = 6 * 24 * 60
};
thirst_levels
enum class thirst_levels : int strong
Enumerator
turgid
hydrated
slaked
thirsty
very_thirsty
dehydrated
parched
dead
Definition at line 149 of file character.h.
                         : int {
    turgid = INT_MIN,
    hydrated = 0,
    slaked = 60,
    thirsty = 120,
    very_thirsty = 240,
    dehydrated = 480,
    parched = 600,
    dead = 1200
};
vision_modes
enum class vision_modes constexpr strong
Enumerator
DEBUG_NIGHTVISION
NV_GOGGLES
BIRD_EYE
URSINE_VISION
BOOMERED
DARKNESS
IR_VISION
VISION_CLAIRVOYANCE
VISION_CLAIRVOYANCE_PLUS
VISION_CLAIRVOYANCE_SUPER
NUM_VISION_MODES
Definition at line 86 of file character.h.
                  {
    DEBUG_NIGHTVISION,
    NV_GOGGLES,
    BIRD_EYE,
    URSINE_VISION,
    BOOMERED,
    DARKNESS,
    IR_VISION,
    VISION_CLAIRVOYANCE,
    VISION_CLAIRVOYANCE_PLUS,
    VISION_CLAIRVOYANCE_SUPER,
    NUM_VISION_MODES
};
Function Documentation
get_player_character()
Character & get_player_character ()
Definition at line 150 of file character.cpp.
{
    return g->u;
}
Referenced by vehicle::act_on_map(), computer_session::action_map_sewer(), computer_session::action_map_subway(), computer_session::action_maps(), Character::activate_bionic(), map::add_field(), monexamine::add_leash(), npc::address_needs(), npc::address_player(), construction::adjusted_time(), map::apparent_light_helper(), Character::apply_damage(), npc::assess_danger(), item::book_info(), map::build_map_cache(), map::build_seen_cache(), talk_function::buy_100_logs(), talk_function::buy_10_logs(), can_examine_at(), talk_function::caravan_dist(), ui::omap::choose_point(), npc::complain(), npc::complain_about(), construction_color(), npc::consume_food_from_camp(), mission_start::create_hidden_lab_console(), mission_start::create_ice_lab_console(), mission_start::create_lab_console(), debug_menu::debug_menu_uilist(), debug_vision(), repair_item_actor::default_action(), ui::omap::display(), ui::omap::display_editor(), ui::omap::display_hordes(), ui::omap::display_scents(), ui::omap::display_visible_weather(), ui::omap::display_weather(), npc::do_reload(), veh_interact::do_remove(), veh_interact::do_repair(), overmap_ui::draw_ascii(), npc::drop_items(), dialogue::dynamic_line(), explosion_handler::emp_blast(), npc::execute_action(), basecamp::faction_display(), npc::faction_display(), computer_session::failure_manhacks(), computer_session::failure_secubots(), mattack::fear_paralyze(), talk_function::field_build_1(), talk_function::field_build_2(), talk_function::field_harvest(), overmapbuffer::find_all_radio_stations(), npc::find_corpse_to_pulp(), npc::find_item(), overmapbuffer::find_radio_station(), mission_start::find_safety(), heal_actor::finish_using(), npc::form_opinion(), mattack::fungus_sprout(), map::generate_lightmap(), selection_column_preset::get_color(), sfx::get_heard_angle(), get_mission_om_origin(), overmapbuffer::get_npcs_near_player(), overmap_ui::get_overmap_neighbors(), overmap_ui::get_overmap_path_to(), aim_activity_actor::get_weapon(), talk_function::give_aid(), talk_function::give_all_aid(), talk_function::goto_location(), ranged::gunmode_checks_weapon(), handbrake(), item::handle_pickup_ownership(), npc::handle_sound(), vehicle::handle_trap(), npc::heal_player(), npc::heal_self(), heal_actor::info(), defense_game::init_map(), is_player_outside(), ma_style_callback::key(), explosion_handler::legacy_shrapnel(), list_available_constructions(), npc::method_of_attack(), monexamine::mfriend_menu(), map_funcs::migo_nerve_cage_removal(), npc::move(), avatar_action::move(), npc::move_away_from(), overmapbuffer::move_hordes(), map::move_vehicle(), npc::mug_player(), npc_throw(), player_morale::on_worn_item_washed(), vehicle::open_or_close(), vehicle::part_collision(), monexamine::pet_menu(), npc::pick_up_item(), pl_sees(), avatar_action::plthrow(), npc::pretend_heal(), overmapbuffer::process_mongroups(), mission_util::random_house_in_closest_city(), npc::reach_omt_destination(), item::ready_to_revive(), npc::regen_ai_cache(), monexamine::remove_battery(), monexamine::remove_leash(), reveal_destination(), mission_start::reveal_lab_train_depot(), mission_util::reveal_om_ter(), mission_start::reveal_refugee_center(), player_morale::set_worn(), map::shake_vehicle(), skill_req_completed(), achievement::skill_ui_text(), spell_effect_area(), vehicle::start_engine(), vehicle::thrust(), character_funcs::try_uncanny_dodge(), distribution_grid_tracker::update(), veh_interact::update_part_requirements(), editmap::update_view_with_help(), npc::use_painkiller(), and npc::wield_better_weapon().
get_speedydex_bonus()
int get_speedydex_bonus (const int dex)
Returns value of speedydex bonus if enabled.
Definition at line 4141 of file character.cpp.
{
    static const std::string speedydex_min_dex( "SPEEDYDEX_MIN_DEX" );
    static const std::string speedydex_dex_speed( "SPEEDYDEX_DEX_SPEED" );
    // this is the number to be multiplied by the increment
    const int modified_dex = std::max( dex - get_option<int>( speedydex_min_dex ), 0 );
    return modified_dex * get_option<int>( speedydex_dex_speed );
}
Referenced by Character::recalc_speed_bonus().
has_psy_protection()
bool has_psy_protection (const Character & c, int partial_chance)
Returns true if the player has a psyshield artifact, or sometimes if wearing tinfoil.
Definition at line 10617 of file character.cpp.
{
    return c.has_artifact_with( AEP_PSYSHIELD ) ||
           ( c.worn_with_flag( "PSYSHIELD_PARTIAL" ) && one_in( partial_chance ) );
}
References AEP_PSYSHIELD, c, and one_in().
Referenced by mattack::fear_paralyze(), and Character::hardcoded_effects().
Variable Documentation
fatigue_level_strs
const std::unordered_map<std::string, fatigue_levels> fatigue_level_strs
Initial value:
= { {
        { "TIRED", fatigue_levels::tired },
        { "DEAD_TIRED", fatigue_levels::dead_tired },
        { "EXHAUSTED", fatigue_levels::exhausted },
        { "MASSIVE_FATIGUE", fatigue_levels::massive }
    }
}
Definition at line 129 of file character.h.
Referenced by conditional_t< T >::set_need().