Cataclysm BN: explosion_handler::ExplosionEvent Class Reference
explosion_handler::ExplosionEvent Class Reference
Classes
struct FieldToAdd
struct PropelledEntity
Public Types
enum class Kind {
ITEM_MOVEMENT , MOB_MOVEMENT , BLAST , SHRAPNEL ,
FIELD_ADDITION , FIELD_REMOVAL
}
using target_types = std::variant< std::monostate, PropelledEntity, FieldToAdd, field_type_id, int >
Static Public Member Functions
static ExplosionEvent mob_movement (const tripoint position, Creature *mob, float angle, float velocity, float cur_relative_time)
static ExplosionEvent item_movement (const tripoint position, safe_reference< item > item, float angle, float velocity, float cur_relative_time)
static ExplosionEvent tile_blast (const tripoint position, const int distance)
static ExplosionEvent tile_shrapnel (const tripoint position)
static ExplosionEvent field_addition (const tripoint position, field_type_id target, const int intensity=INT_MAX, const bool hit_player=false)
static ExplosionEvent field_removal (const tripoint position, field_type_id target)
Public Attributes
enum explosion_handler::ExplosionEvent::Kind kind
target_types target
tripoint position
Private Member Functions
ExplosionEvent (Kind kind, const tripoint position)
ExplosionEvent (Kind kind, const tripoint position, target_types target)
Detailed Description
Definition at line 238 of file explosion.cpp.
Member Typedef Documentation
target_types
using explosion_handler::ExplosionEvent::target_types = std::variant<std::monostate, PropelledEntity, FieldToAdd, field_type_id, int>
Definition at line 255 of file explosion.cpp.
Member Enumeration Documentation
Kind
enum class explosion_handler::ExplosionEvent::Kind strong
Enumerator
ITEM_MOVEMENT
MOB_MOVEMENT
BLAST
SHRAPNEL
FIELD_ADDITION
FIELD_REMOVAL
Definition at line 258 of file explosion.cpp.
{ ITEM_MOVEMENT, MOB_MOVEMENT, BLAST, SHRAPNEL, FIELD_ADDITION, FIELD_REMOVAL } kind;
Constructor & Destructor Documentation
ExplosionEvent() [1/2]
explosion_handler::ExplosionEvent::ExplosionEvent (Kind kind, const tripoint position) inline private
Definition at line 301 of file explosion.cpp.
                                                             :
            kind( kind ), position( position ) {};
Referenced by field_addition(), field_removal(), item_movement(), mob_movement(), tile_blast(), and tile_shrapnel().
ExplosionEvent() [2/2]
explosion_handler::ExplosionEvent::ExplosionEvent (Kind kind, const tripoint position, target_types target) inline private
Definition at line 303 of file explosion.cpp.
                                                                                  :
            kind( kind ), target( target ), position( position ) {};
Member Function Documentation
field_addition()
static ExplosionEvent explosion_handler::ExplosionEvent::field_addition (const tripoint position, field_type_id target, const int intensity = INT_MAX, const bool hit_player = false) inline static
Definition at line 290 of file explosion.cpp.
          {
            return ExplosionEvent( Kind::FIELD_ADDITION, position, FieldToAdd{target, intensity, hit_player} );
        }
References ExplosionEvent(), FIELD_ADDITION, position, and target.
Referenced by explosion_handler::ExplosionProcess::blast_tile().
field_removal()
static ExplosionEvent explosion_handler::ExplosionEvent::field_removal (const tripoint position, field_type_id target) inline static
Definition at line 296 of file explosion.cpp.
{
            return ExplosionEvent( Kind::FIELD_REMOVAL, position, target );
        }
References ExplosionEvent(), FIELD_REMOVAL, position, and target.
Referenced by explosion_handler::ExplosionProcess::blast_tile().
item_movement()
static ExplosionEvent explosion_handler::ExplosionEvent::item_movement (const tripoint position, safe_reference< item > item, float angle, float velocity, float cur_relative_time) inline static
Definition at line 273 of file explosion.cpp.
{
            return ExplosionEvent( Kind::ITEM_MOVEMENT, position,
            PropelledEntity{
                item,
                rl_vec2d( position.x + 0.5, position.y + 0.5 ),
                angle,
                velocity,
                cur_relative_time
            } );
        }
References ExplosionEvent(), ITEM_MOVEMENT, position, tripoint::x, and tripoint::y.
Referenced by explosion_handler::ExplosionProcess::blast_tile(), and explosion_handler::ExplosionProcess::move_entity().
mob_movement()
static ExplosionEvent explosion_handler::ExplosionEvent::mob_movement (const tripoint position, Creature * mob, float angle, float velocity, float cur_relative_time) inline static
Definition at line 262 of file explosion.cpp.
{
            return ExplosionEvent( Kind::MOB_MOVEMENT, position,
            PropelledEntity{
                mob,
                rl_vec2d( position.x + 0.5, position.y + 0.5 ),
                angle,
                velocity,
                cur_relative_time
            } );
        }
References ExplosionEvent(), MOB_MOVEMENT, position, tripoint::x, and tripoint::y.
Referenced by explosion_handler::ExplosionProcess::blast_tile(), and explosion_handler::ExplosionProcess::move_entity().
tile_blast()
static ExplosionEvent explosion_handler::ExplosionEvent::tile_blast (const tripoint position, const int distance) inline static
Definition at line 284 of file explosion.cpp.
{
            return ExplosionEvent( Kind::BLAST, position, distance );
        }
References BLAST, ExplosionEvent(), and position.
Referenced by explosion_handler::ExplosionProcess::init_event_queue().
tile_shrapnel()
static ExplosionEvent explosion_handler::ExplosionEvent::tile_shrapnel (const tripoint position) inline static
Definition at line 287 of file explosion.cpp.
{
            return ExplosionEvent( Kind::SHRAPNEL, position );
        }
References ExplosionEvent(), position, and SHRAPNEL.
Referenced by explosion_handler::ExplosionProcess::init_event_queue().
Member Data Documentation
kind
enum explosion_handler::ExplosionEvent::Kind explosion_handler::ExplosionEvent::kind
position
tripoint explosion_handler::ExplosionEvent::position
Definition at line 260 of file explosion.cpp.
Referenced by field_addition(), field_removal(), item_movement(), mob_movement(), tile_blast(), and tile_shrapnel().
target
target_types explosion_handler::ExplosionEvent::target
Definition at line 259 of file explosion.cpp.
Referenced by field_addition(), and field_removal().
The documentation for this class was generated from the following file:
src/explosion.cpp