Cataclysm BN: npc_template Class Reference
npc_template Class Reference
#include <npc.h>
Public Types
enum class gender { random , male , female }
Public Member Functions
npc_template ()=default
Static Public Member Functions
static void load (const JsonObject &jsobj)
static void reset ()
static void check_consistency ()
Public Attributes
npc guy
translation name_unique
translation name_suffix
gender gender_override = gender::random
Detailed Description
Definition at line 1372 of file npc.h.
Member Enumeration Documentation
gender
enum class npc_template::gender strong
Enumerator
random
male
female
Definition at line 1380 of file npc.h.
{
            random,
            male,
            female
        };
Constructor & Destructor Documentation
npc_template()
npc_template::npc_template () default
Member Function Documentation
check_consistency()
void npc_template::check_consistency () static
Definition at line 265 of file npc.cpp.
{
    for( const auto &e : npc_templates ) {
        const auto &guy = e.second.guy;
        if( !guy.myclass.is_valid() ) {
            debugmsg( "Invalid NPC class %s", guy.myclass.c_str() );
        }
    }
}
References string_id< T >::c_str(), debugmsg, guy, string_id< T >::is_valid(), npc::myclass, and npc_templates.
Referenced by DynamicDataLoader::check_consistency().
load()
void npc_template::load (const JsonObject & jsobj) static
Definition at line 220 of file npc.cpp.
{
    npc_template tem;
    npc &guy = tem.guy;
    guy.idz = jsobj.get_string( "id" );
    guy.name.clear();
    jsobj.read( "name_unique", tem.name_unique );
    jsobj.read( "name_suffix", tem.name_suffix );
    if( jsobj.has_string( "gender" ) ) {
        if( jsobj.get_string( "gender" ) == "male" ) {
            tem.gender_override = gender::male;
        } else {
            tem.gender_override = gender::female;
        }
    } else {
        tem.gender_override = gender::random;
    }
    if( jsobj.has_string( "faction" ) ) {
        guy.set_fac_id( jsobj.get_string( "faction" ) );
    }
    if( jsobj.has_int( "class" ) ) {
        guy.myclass = npc_class::from_legacy_int( jsobj.get_int( "class" ) );
    } else if( jsobj.has_string( "class" ) ) {
        guy.myclass = npc_class_id( jsobj.get_string( "class" ) );
    }
    guy.set_attitude( static_cast<npc_attitude>( jsobj.get_int( "attitude" ) ) );
    guy.mission = static_cast<npc_mission>( jsobj.get_int( "mission" ) );
    guy.chatbin.first_topic = jsobj.get_string( "chat" );
    if( jsobj.has_string( "mission_offered" ) ) {
        guy.miss_ids.emplace_back( mission_type_id( jsobj.get_string( "mission_offered" ) ) );
    } else if( jsobj.has_array( "mission_offered" ) ) {
        for( const std::string line : jsobj.get_array( "mission_offered" ) ) {
            guy.miss_ids.emplace_back( mission_type_id( line ) );
        }
    }
    npc_templates.emplace( string_id<npc_template>( guy.idz ), std::move( tem ) );
}
References npc::chatbin, female, npc_chatbin::first_topic, npc_class::from_legacy_int(), gender_override, JsonObject::get_array(), JsonObject::get_int(), JsonObject::get_string(), guy, JsonObject::has_array(), JsonObject::has_int(), JsonObject::has_string(), npc::idz, line(), male, npc::miss_ids, npc::mission, avatar_action::move(), npc::myclass, Character::name, name_suffix, name_unique, npc_templates, random, JsonObject::read(), npc::set_attitude(), and Character::set_fac_id().
Referenced by DynamicDataLoader::initialize().
reset()
void npc_template::reset () static
Definition at line 260 of file npc.cpp.
{
    npc_templates.clear();
}
References npc_templates.
Referenced by DynamicDataLoader::unload_data().
Member Data Documentation
gender_override
gender npc_template::gender_override = gender::random
Definition at line 1385 of file npc.h.
Referenced by load(), and npc::load_npc_template().
guy
npc npc_template::guy
Definition at line 1377 of file npc.h.
Referenced by check_consistency(), load(), and npc::load_npc_template().
name_suffix
translation npc_template::name_suffix
Definition at line 1379 of file npc.h.
Referenced by load(), and npc::load_npc_template().
name_unique
translation npc_template::name_unique
Definition at line 1378 of file npc.h.
Referenced by load(), and npc::load_npc_template().
The documentation for this class was generated from the following files:
src/npc.h
src/npc.cpp