Cataclysm BN: explosion_handler::ExplosionProcess Class Reference
explosion_handler::ExplosionProcess Class Reference
Public Member Functions
void run ()
std::map< const Creature *, int > get_blasted ()
std::map< const Creature *, int > get_shrapneled ()
ExplosionProcess (const tripoint blast_center, const int blast_power, const int blast_radius, const std::optional< projectile > proj=std::nullopt, const bool is_fiery=false, const std::optional< Creature * > responsible=std::nullopt)
Public Attributes
const tripoint center
const int blast_power
const int blast_radius
const bool is_fiery
const std::optional< projectile > shrapnel
const std::optional< Creature * > emitter
Private Types
using dist_point_pair = std::pair< float, tripoint >
using time_event_pair = std::pair< float, ExplosionEvent >
Private Member Functions
void update_timings ()
void fill_maps ()
void init_event_queue ()
float generate_fling_angle (const tripoint from, const tripoint to)
bool is_occluded (const tripoint from, const tripoint to)
void add_event (const float delay, const ExplosionEvent event)
bool is_animated ()
bool process_next ()
void blast_tile (const tripoint position, const int rl_distance)
void project_shrapnel (const tripoint position)
void add_field (const tripoint position, const field_type_id field, const int intensity, const bool hit_player)
void remove_field (const tripoint position, const field_type_id target)
void move_entity (const tripoint position, const ExplosionEvent::PropelledEntity &datum, bool is_mob)
float one_tile_at_vel (float velocity)
Static Private Member Functions
static bool dist_comparator (dist_point_pair a, dist_point_pair b)
static bool time_comparator (time_event_pair a, time_event_pair b)
Private Attributes
std::vector< dist_point_pair > blast_map
std::vector< dist_point_pair > shrapnel_map
std::priority_queue< time_event_pair, std::vector< time_event_pair >, pair_greater_cmp_first > event_queue
std::optional< player * > player_flung
std::map< const Creature *, int > mobs_blasted
std::map< const Creature *, int > mobs_shrapneled
std::set< const Creature * > flung_set
std::vector< tripoint > recombination_targets
float cur_relative_time
long long last_update_ms
bool request_redraw
Detailed Description
Definition at line 307 of file explosion.cpp.
Member Typedef Documentation
dist_point_pair
using explosion_handler::ExplosionProcess::dist_point_pair = std::pair<float, tripoint> private
Definition at line 328 of file explosion.cpp.
time_event_pair
using explosion_handler::ExplosionProcess::time_event_pair = std::pair<float, ExplosionEvent> private
Definition at line 329 of file explosion.cpp.
Constructor & Destructor Documentation
ExplosionProcess()
explosion_handler::ExplosionProcess::ExplosionProcess (const tripoint blast_center, const int blast_power, const int blast_radius, const std::optional< projectile > proj = std::nullopt, const bool is_fiery = false, const std::optional< Creature * > responsible = std::nullopt) inline
Definition at line 355 of file explosion.cpp.
          : center( blast_center ),
            blast_power( blast_power ),
            blast_radius( blast_radius ),
            is_fiery( is_fiery ),
            shrapnel( proj ),
            emitter( responsible ),
            player_flung( std::nullopt ),
            cur_relative_time( 0.0 ),
            last_update_ms(
                std::chrono::time_point_cast<std::chrono::milliseconds>
                ( std::chrono::system_clock::now() ).time_since_epoch().count()
            ),
            request_redraw( false ) {}
Member Function Documentation
add_event()
void explosion_handler::ExplosionProcess::add_event (const float delay, const ExplosionEvent event) inline private
Definition at line 405 of file explosion.cpp.
{
            assert( delay >= 0 );
            event_queue.push( { cur_relative_time + delay + std::numeric_limits<float>::epsilon(), event } );
        }
References cur_relative_time, and event_queue.
Referenced by blast_tile(), init_event_queue(), and move_entity().
add_field()
void explosion_handler::ExplosionProcess::add_field (const tripoint position, const field_type_id field, const int intensity, const bool hit_player) private
Definition at line 893 of file explosion.cpp.
{
    map &here = get_map();
    here.add_field( position, field, intensity, 0_turns, hit_player );
    request_redraw |= position.z == g->u.posz();
}
References map::add_field(), g, get_map(), request_redraw, and tripoint::z.
Referenced by process_next().
blast_tile()
void explosion_handler::ExplosionProcess::blast_tile (const tripoint position, const int rl_distance) private
Definition at line 657 of file explosion.cpp.
{
    assert( blast_radius > 0 );
    // Verify we have view of the center
    if( is_occluded( center, position ) ) {
        return;
    }
    map &here = get_map();
    if( blast_power ) {
        // Item damage comes first in order to prevent dropped loot from being destroyed immediately.
        {
            const std::string cause = _( "force of the explosion" );
            const int smash_force = blast_power * item_blast_percentage( blast_radius, rl_distance );
            here.smash_trap( position, smash_force, cause );
            here.smash_items( position, smash_force, cause, true );
            // Don't forget to mark them as explosion smashed already
            for( auto &item : here.i_at( position ) ) {
                item.set_flag( "EXPLOSION_SMASHED" );
            }
        }
        // Damage creatures. Done first to reduce the amount of flung enemies.
        {
            Creature *critter = g->critter_at( position );
            if( critter != nullptr && !mobs_blasted.count( critter ) ) {
                const int blast_damage = blast_power * critter_blast_percentage( critter, blast_radius,
                                         rl_distance );
                const auto shockwave_dmg = damage_instance::physical( blast_damage, 0, 0, 0.4f );
                player *player_ptr = critter->as_player();
                if( player_ptr != nullptr ) {
                    player_ptr->add_msg_if_player( m_bad, _( "You're caught in the explosion!" ) );
                    struct blastable_part {
                        bodypart_id bp;
                        float low_mul;
                        float high_mul;
                        float armor_mul;
                    };
                    static const std::array<blastable_part, 6> blast_parts = { {
                            { bodypart_id( "torso" ), 0.5f, 1.0f, 0.5f },
                            { bodypart_id( "head" ),  0.5f, 1.0f, 0.5f },
                            { bodypart_id( "leg_l" ), 0.75f, 1.25f, 0.4f },
                            { bodypart_id( "leg_r" ), 0.75f, 1.25f, 0.4f },
                            { bodypart_id( "arm_l" ), 0.75f, 1.25f, 0.4f },
                            { bodypart_id( "arm_r" ), 0.75f, 1.25f, 0.4f },
                        }
                    };
                    for( const auto &blast_part : blast_parts ) {
                        const int part_dam = rng( blast_damage * blast_part.low_mul, blast_damage * blast_part.high_mul );
                        const std::string hit_part_name = body_part_name_accusative( blast_part.bp->token );
                        const auto dmg_instance = damage_instance( DT_BASH, part_dam, 0, blast_part.armor_mul );
                        const auto result = player_ptr->deal_damage( emitter.value_or( nullptr ), blast_part.bp,
                                            dmg_instance );
                        const int res_dmg = result.total_damage();
                        if( res_dmg > 0 ) {
                            mobs_blasted[critter] = res_dmg;
                        }
                    }
                } else {
                    critter->deal_damage( emitter.value_or( nullptr ), bodypart_id( "torso" ), shockwave_dmg );
                    critter->check_dead_state();
                    mobs_blasted[critter] = blast_damage;
                }
            }
        }
        // Fling creatures
        {
            Creature *critter = g->critter_at( position );
            if( critter != nullptr && !flung_set.count( critter ) ) {
                const int push_strength = ( blast_radius - rl_distance ) * blast_power;
                const float move_power = ExplosionConstants::MOB_FLING_FACTOR * push_strength;
                const int weight = to_gram( critter->get_weight() );
                const int inertia = std::max( weight, 1 ) * ExplosionConstants::EXPLOSION_CALIBRATION_POWER;
                const float real_velocity = move_power / inertia;
                const float velocity = real_velocity > ExplosionConstants::FLING_THRESHOLD ?
                                       rng_float( ExplosionConstants::FLING_THRESHOLD, ExplosionConstants::FLING_MAX_RANGE ) :
                                       real_velocity;
                if( velocity >= 1.0 ) {
                    player *player_ptr = critter->as_player();
                    if( player_ptr != nullptr ) {
                        player_flung = std::make_optional( player_ptr );
                    }
                    add_event( one_tile_at_vel( velocity ),
                               ExplosionEvent::mob_movement(
                                   position, critter,
                                   generate_fling_angle( center, position ), velocity, cur_relative_time
                               )
                             );
                    flung_set.insert( critter );
                }
            }
        }
        {
            // This reduces the randomness factor in terrain bash significantly
            // Which makes explosions have a more well-defined shape.
            const float offset_distance = std::max( rl_distance - 1.0, 0.0 );
            const float terrain_random_factor = rng_float( 0.0, ExplosionConstants::BASH_RANDOM_FACTOR );
            const float terrain_factor = std::min( std::max( offset_distance / blast_radius -
                                                   terrain_random_factor, 0.0f ), 1.0f );
            float terrain_blast_force = blast_power * obstacle_blast_percentage( blast_radius, rl_distance );
            // Multibash is done by bashing the tile with decaying force.
            // The reason for this existing is because a number of tiles undergo multiple bashed states
            // Things like doors and wall -> floor -> ground.
            const float blast_force_decay = ( ExplosionConstants::VEHICLE_DAMAGE_MULT - 1.0 ) *
                                            blast_power / ExplosionConstants::MULTIBASH_COUNT;
            assert( blast_force_decay > 0 );
            while( terrain_blast_force > 0 ) {
                bash_params bash{
                    static_cast<int>( terrain_blast_force ),
                    true,
                    false,
                    here.passable( position + tripoint_below ),
                    terrain_factor,
                    center.z > position.z,
                    true
                };
                // Despite what you might expect, this is NOT the same as smash_items
                here.bash_items( position, bash );
                here.bash_field( position, bash );
                here.bash_vehicle( position, bash );
                here.bash_ter_furn( position, bash );
                terrain_blast_force -= blast_force_decay;
            }
        }
        {
            // Split items here into stacks
            std::vector<item> stacks;
            for( auto &it : here.i_at( position ) ) {
                while( true ) {
                    const int amt = it.count();
                    const int split_cnt = rng( 1, amt - 1 );
                    const bool is_final = amt <= 1;
                    // If the item is already propelled, ignore it
                    if( !is_final && !it.has_flag( "EXPLOSION_PROPELLED" ) ) {
                        stacks.push_back( it.split( split_cnt ) );
                    } else {
                        stacks.push_back( item( it ) );
                        break;
                    }
                }
            }
            here.i_clear( position );
            for( const auto &it : stacks ) {
                here.add_item( position, it );
            }
            recombination_targets.push_back( position );
        }
        // Now give items velocity
        for( auto &it : here.i_at( position ) ) {
            // If the item is already propelled, ignore it
            if( it.has_flag( "EXPLOSION_PROPELLED" ) ) {
                continue;
            };
            const float random_factor = rng_float( -ExplosionConstants::ITEM_FLING_RANDOM_FACTOR,
                                                   ExplosionConstants::ITEM_FLING_RANDOM_FACTOR );
            const float push_strength = std::max( blast_radius - rl_distance + random_factor,
                                                  0.0f ) * blast_power;
            const float move_power = ExplosionConstants::ITEM_FLING_FACTOR * push_strength;
            const int weight = to_gram( it.weight() );
            const float inertia = std::max( weight, 1 ) * ExplosionConstants::EXPLOSION_CALIBRATION_POWER;
            const float real_velocity = move_power / inertia;
            const float velocity = real_velocity > ExplosionConstants::FLING_THRESHOLD ?
                                   rng_float( ExplosionConstants::FLING_THRESHOLD, ExplosionConstants::FLING_MAX_RANGE ) :
                                   real_velocity;
            if( velocity < 1.0 ) {
                continue;
            }
            it.set_flag( "EXPLOSION_PROPELLED" );
            add_event(
                one_tile_at_vel( velocity ),
                ExplosionEvent::item_movement(
                    position, it.get_safe_reference(),
                    generate_fling_angle( center, position ), velocity, cur_relative_time )
            );
        }
    }
    // Finally, add fields if we can
    if( here.passable( position ) ) {
        const float radius_percent = static_cast<float>( rl_distance ) / blast_radius;
        // Create fresh smoke
        // 50% of the radius is guaranteed to be covered in thin smoke afterwards
        if( here.get_field( position, fd_smoke ) == nullptr ) {
            const float radius_offset = 2 * radius_percent - 1;
            add_event( 0, ExplosionEvent::field_addition( position, fd_smoke ) );
            if( radius_offset > 0 ) {
                const float delay = blast_radius * rng_float( 0.0, 1.1 - radius_offset );
                add_event( delay, ExplosionEvent::field_removal( position, fd_smoke ) );
            }
        }
        // Create fresh fire fields
        if( here.get_field( position, fd_fire ) == nullptr ) {
            add_event(
                0.5,
                ExplosionEvent::field_addition( position, fd_fire,
                                                1 + ( blast_power > 10 ) + ( blast_power > 30 ),
                                                is_fiery
                                              )
            );
            if( !is_fiery ) {
                // Remove at an accelerating pace
                const float delay = 1.0 + rng_float( 2.0, 4.0 ) * ( 1.1 - radius_percent );
                add_event( delay, ExplosionEvent::field_removal( position, fd_fire ) );
            }
        }
    }
    request_redraw |= position.z == g->u.posz();
}
References _, add_event(), map::add_item(), player::add_msg_if_player(), Creature::as_player(), spell_effect::bash(), map::bash_field(), map::bash_items(), ExplosionConstants::BASH_RANDOM_FACTOR, map::bash_ter_furn(), map::bash_vehicle(), blast_power, blast_radius, body_part_name_accusative(), center, Creature::check_dead_state(), critter_blast_percentage(), cur_relative_time, Character::deal_damage(), Creature::deal_damage(), DT_BASH, emitter, ExplosionConstants::EXPLOSION_CALIBRATION_POWER, fd_fire, fd_smoke, explosion_handler::ExplosionEvent::field_addition(), explosion_handler::ExplosionEvent::field_removal(), ExplosionConstants::FLING_MAX_RANGE, ExplosionConstants::FLING_THRESHOLD, flung_set, g, generate_fling_angle(), map::get_field(), get_map(), Creature::get_weight(), map::i_at(), map::i_clear(), is_fiery, is_occluded(), item_blast_percentage(), ExplosionConstants::ITEM_FLING_FACTOR, ExplosionConstants::ITEM_FLING_RANDOM_FACTOR, explosion_handler::ExplosionEvent::item_movement(), m_bad, ExplosionConstants::MOB_FLING_FACTOR, explosion_handler::ExplosionEvent::mob_movement(), mobs_blasted, ExplosionConstants::MULTIBASH_COUNT, obstacle_blast_percentage(), one_tile_at_vel(), map::passable(), damage_instance::physical(), player_flung, recombination_targets, request_redraw, rng(), rng_float(), item::set_flag(), map::smash_items(), map::smash_trap(), units::to_gram(), tripoint_below, ExplosionConstants::VEHICLE_DAMAGE_MULT, and tripoint::z.
Referenced by process_next().
dist_comparator()
static bool explosion_handler::ExplosionProcess::dist_comparator (dist_point_pair a, dist_point_pair b) inline static private
Definition at line 376 of file explosion.cpp.
{
            return a.first < b.first;
        };
References a, and b.
Referenced by fill_maps().
fill_maps()
void explosion_handler::ExplosionProcess::fill_maps () private
Definition at line 429 of file explosion.cpp.
{
    map &here = get_map();
    const int shrapnel_range = shrapnel.has_value() ? shrapnel.value().range : 0;
    const int aoe_radius = std::max( blast_radius, shrapnel_range );
    const int z_levels_affected = aoe_radius / ExplosionConstants::Z_LEVEL_DIST;
    const tripoint_range<tripoint> affected_block(
        center + tripoint( -aoe_radius, -aoe_radius, -z_levels_affected ),
        center + tripoint( aoe_radius, aoe_radius, z_levels_affected )
    );
    for( const tripoint &target : affected_block ) {
        if( !here.inbounds( target ) ) {
            continue;
        }
        // Uses this ternany check instead of rl_dist because it converts trig_dist's distance to int implicitly
        const float distance = (
                                   trigdist ?
                                   trig_dist( center, target ) :
                                   square_dist( center, target )
                               );
        const float z_distance = abs( target.z - center.z );
        const float z_aware_distance = distance + ( ExplosionConstants::Z_LEVEL_DIST - 1 ) * z_distance;
        // We static_cast<int> in order to keep parity with legacy blasts using rl_dist for distance
        //   which, as stated above, converts trig_dist into int implicitly
        if( blast_radius > 0 && static_cast<int>( z_aware_distance ) <= blast_radius ) {
            blast_map.push_back( { z_aware_distance, target } );
        }
        if( shrapnel && static_cast<int>( distance ) <= shrapnel_range && target.z == center.z &&
            !is_occluded( center, target ) ) {
            shrapnel_map.push_back( { distance, target } );
        }
    }
    std::stable_sort( blast_map.begin(), blast_map.end(), dist_comparator );
    std::stable_sort( shrapnel_map.begin(), shrapnel_map.end(), dist_comparator );
}
References blast_map, blast_radius, center, dist_comparator(), get_map(), map::inbounds(), is_occluded(), shrapnel, shrapnel_map, square_dist(), trig_dist(), trigdist, tripoint::z, and ExplosionConstants::Z_LEVEL_DIST.
Referenced by run().
generate_fling_angle()
float explosion_handler::ExplosionProcess::generate_fling_angle (const tripoint from, const tripoint to) inline private
Definition at line 522 of file explosion.cpp.
{
    if( from != to ) {
        // -+ 0.95 added to add a half-arc
        // It should be noted that this mathematically has a bias towards diagonal directions
        //   but this is the shortest way to get good enough results
        return units::atan2(
                   to.y - from.y + rng_float( -0.95, 0.95 ),
                   to.x - from.x + rng_float( -0.95, 0.95 )
               ).value();
    } else {
        return rng_float( -M_PI, M_PI );
    }
}
References units::atan2(), M_PI, rng_float(), units::quantity< V, U >::value(), tripoint::x, and tripoint::y.
Referenced by blast_tile().
get_blasted()
std::map< const Creature *, int > explosion_handler::ExplosionProcess::get_blasted () inline
Definition at line 348 of file explosion.cpp.
{
            return mobs_blasted;
        };
References mobs_blasted.
Referenced by explosion_handler::explosion_funcs::regular().
get_shrapneled()
std::map< const Creature *, int > explosion_handler::ExplosionProcess::get_shrapneled () inline
Definition at line 351 of file explosion.cpp.
{
            return mobs_shrapneled;
        };
References mobs_shrapneled.
Referenced by explosion_handler::explosion_funcs::regular().
init_event_queue()
void explosion_handler::ExplosionProcess::init_event_queue () private
Definition at line 469 of file explosion.cpp.
{
    // Start with shrapnel first
    // In how many blast steps should the animation for shrapnel complete?
    const float SHRAPNEL_EQUIV = 3.0;
    const float shrapnel_delay = shrapnel.has_value() ? SHRAPNEL_EQUIV : 0.0;
    for( const auto &[distance, position] : shrapnel_map ) {
        const float random_factor = rng_float( -0.2, 0.2 );
        const float range_percent = distance / shrapnel.value().range;
        const float timing = std::min( std::max( range_percent + random_factor, 0.0f ), 1.0f );
        const float time_taken = SHRAPNEL_EQUIV * timing;
        add_event( time_taken, ExplosionEvent::tile_shrapnel( position ) );
    }
    // Then apply blasting
    for( const auto &[distance, position] : blast_map ) {
        const float time_taken = shrapnel_delay + distance;
        // We static_cast<int> in order to keep parity with legacy blasts using rl_dist for distance
        //   which, as stated before, converts trig_dist into int implicitly
        add_event( time_taken, ExplosionEvent::tile_blast( position, static_cast<int>( distance ) ) );
    }
}
References add_event(), blast_map, rng_float(), shrapnel, shrapnel_map, explosion_handler::ExplosionEvent::tile_blast(), and explosion_handler::ExplosionEvent::tile_shrapnel().
Referenced by run().
is_animated()
bool explosion_handler::ExplosionProcess::is_animated () inline private
Definition at line 409 of file explosion.cpp.
{
            return !test_mode && get_option<int>( "ANIMATION_DELAY" ) > 0;
        }
References test_mode.
Referenced by process_next(), project_shrapnel(), run(), and update_timings().
is_occluded()
bool explosion_handler::ExplosionProcess::is_occluded (const tripoint from, const tripoint to) inline private
Definition at line 493 of file explosion.cpp.
{
    if( from == to ) {
        return false;
    }
    map &here = get_map();
    tripoint last_position = from;
    std::vector<tripoint> line_of_movement = line_to( from, to );
    // Annoyingly, line_to does not include the origin point
    //   so it has to be added manually
    line_of_movement.insert( line_of_movement.begin(), from );
    for( const auto &position : line_of_movement ) {
        // position != to necessary because we do want to strike the
        //   target obstacle
        if( position != to && here.impassable( position ) ) {
            return true;
        }
        // position != to is unneeded here though because we want to
        //   make sure stuff does not fly into vehicles
        if( here.obstructed_by_vehicle_rotation( last_position, position ) ) {
            return true;
        }
        last_position = position;
    }
    return false;
}
References get_map(), map::impassable(), line_to(), and map::obstructed_by_vehicle_rotation().
Referenced by blast_tile(), fill_maps(), and project_shrapnel().
move_entity()
void explosion_handler::ExplosionProcess::move_entity (const tripoint position, const ExplosionEvent::PropelledEntity & datum, bool is_mob) private
Definition at line 910 of file explosion.cpp.
{
    if( datum.velocity < 1 ) {
        return;
    }
    std::variant<Creature *, safe_reference<item>> cur_target = datum.target;
    if( !is_mob && !std::get<safe_reference<item>>( cur_target ) ) {
        return;
    }
    map &here = get_map();
    const float time_delta = cur_relative_time - datum.cur_relative_time;
    const float adjusted_delta = time_delta / ExplosionConstants::FLING_SLOWDOWN;
    const float distance_to_travel = std::min( datum.velocity * adjusted_delta, datum.velocity );
    tripoint new_position = position;
    float new_velocity = datum.velocity;
    float new_angle = datum.angle;
    // Sometimes items fly more than one tile at once
    //   so we want to make sure we do not hit any obstacles on the way
    // Hence this complication
    {
        const int intermediate_steps = ceil( 1.5 * distance_to_travel );
        for( int step = 0; step <= intermediate_steps; step++ ) {
            const float progress = static_cast<float>( step ) / static_cast<float>( intermediate_steps );
            const float cur_distance_travelled = distance_to_travel * progress;
            rl_vec2d new_position_vec = datum.position +
                                        rl_vec2d( cur_distance_travelled, 0.0 ).rotated( datum.angle );
            tripoint maybe_new_position = tripoint( static_cast<int>( new_position_vec.x ),
                                                    static_cast<int>( new_position_vec.y ),
                                                    position.z );
            if( !here.inbounds( maybe_new_position ) ||
                here.impassable( maybe_new_position ) ||
                ( is_mob && maybe_new_position != position && g->critter_at( maybe_new_position ) ) ||
                here.obstructed_by_vehicle_rotation( position, maybe_new_position ) ) {
                // TODO: Bash the obstacle with whatever is flung?
                // Just a 180 degree flip
                // Too expensive to compute the proper reflection angle
                new_angle += M_PI;
                new_velocity = datum.velocity - cur_distance_travelled;
                new_velocity *= ExplosionConstants::RESTITUTION_COEFF;
                break;
            }
            new_position = maybe_new_position;
            new_velocity = datum.velocity - cur_distance_travelled;
        }
    }
    bool do_next = new_velocity >= 1;
    if( new_position != position ) {
        if( is_mob ) {
            std::get<Creature *>( cur_target )->setpos( new_position );
        } else {
            item *target = std::get<safe_reference<item>>( cur_target ).get();
            item copy = *target;
            if( !copy.is_null() ) {
                here.i_rem( position, target );
                item *new_item = &here.add_item( new_position, copy );
                recombination_targets.push_back( position );
                recombination_targets.push_back( new_position );
                // add_item may in fact change the item in a number of ways
                //   so we _have_ to check if it's in the location we expect
                // It's slow, but what can you do?
                new_item->set_flag( "IS_EXPLOSION_PROPELLED" );
                bool is_safe = false;
                for( auto &it : here.i_at( new_position ) ) {
                    if( it.has_flag( "IS_EXPLOSION_PROPELLED" ) ) {
                        is_safe = true;
                        break;
                    }
                }
                new_item->unset_flag( "IS_EXPLOSION_PROPELLED" );
                if( !is_safe ) {
                    do_next = false;
                } else {
                    cur_target = new_item->get_safe_reference();
                }
            }
        }
        request_redraw |= position.z == g->u.posz();
        request_redraw |= new_position.z == g->u.posz();
    }
    if( do_next ) {
        add_event(
            one_tile_at_vel( new_velocity ),
            is_mob ?
            ExplosionEvent::mob_movement( new_position,
                                          std::get<Creature *>( cur_target ), new_angle, new_velocity, cur_relative_time ) :
            ExplosionEvent::item_movement( new_position,
                                           std::get<safe_reference<item>>( cur_target ), new_angle, new_velocity, cur_relative_time )
        );
    }
}
References add_event(), map::add_item(), explosion_handler::ExplosionEvent::PropelledEntity::angle, explosion_handler::ExplosionEvent::PropelledEntity::cur_relative_time, cur_relative_time, ExplosionConstants::FLING_SLOWDOWN, g, charge_removal_blacklist::get(), get_map(), item::get_safe_reference(), map::i_at(), map::i_rem(), map::impassable(), map::inbounds(), item::is_null(), explosion_handler::ExplosionEvent::item_movement(), M_PI, explosion_handler::ExplosionEvent::mob_movement(), map::obstructed_by_vehicle_rotation(), one_tile_at_vel(), explosion_handler::ExplosionEvent::PropelledEntity::position, recombination_targets, request_redraw, ExplosionConstants::RESTITUTION_COEFF, rl_vec2d::rotated(), item::set_flag(), explosion_handler::ExplosionEvent::PropelledEntity::target, item::unset_flag(), explosion_handler::ExplosionEvent::PropelledEntity::velocity, rl_vec2d::x, rl_vec2d::y, and tripoint::z.
Referenced by process_next().
one_tile_at_vel()
float explosion_handler::ExplosionProcess::one_tile_at_vel (float velocity) inline private
Definition at line 423 of file explosion.cpp.
{
            assert( velocity > 0 );
            return ExplosionConstants::FLING_SLOWDOWN / velocity;
        };
References ExplosionConstants::FLING_SLOWDOWN.
Referenced by blast_tile(), and move_entity().
process_next()
bool explosion_handler::ExplosionProcess::process_next () private
Definition at line 537 of file explosion.cpp.
{
    if( event_queue.empty() ) {
        return false;
    }
    // We don't need to wait in testing mode or if there is no animation delay
    if( is_animated() ) {
        const float next_event_time = event_queue.top().first;
        const double relative_time_step = static_cast<double>( next_event_time - cur_relative_time );
        const double animation_delay = static_cast<double>( get_option<int>( "ANIMATION_DELAY" ) );
        // We balance the timing in such a way
        //   that, at 10 ANIMATION_DELAY, it will take an explosion of radius 10
        //   exactly 1 second to propagate fully
        const long int delay_ms = static_cast<long int>( relative_time_step * 10.0 * animation_delay );
        if( delay_ms > 0 ) {
            const timespec delay = timespec {0, delay_ms * 1000000L};
            nanosleep( &delay, nullptr );
        }
    }
    update_timings();
    while( !event_queue.empty() && cur_relative_time >= event_queue.top().first ) {
        const auto &event = event_queue.top().second;
        switch( event.kind ) {
            case ExplosionEvent::Kind::SHRAPNEL:
                project_shrapnel( event.position );
                break;
            case ExplosionEvent::Kind::BLAST:
                blast_tile( event.position, std::get<int>( event.target ) );
                break;
            case ExplosionEvent::Kind::FIELD_ADDITION: {
                const auto &[field, intensity,
                                    hit_player] = std::get<ExplosionEvent::FieldToAdd>( event.target );
                add_field( event.position, field, intensity, hit_player );
                break;
            }
            case ExplosionEvent::Kind::FIELD_REMOVAL:
                remove_field( event.position, std::get<field_type_id>( event.target ) );
                break;
            case ExplosionEvent::Kind::ITEM_MOVEMENT:
            case ExplosionEvent::Kind::MOB_MOVEMENT:
                move_entity(
                    event.position,
                    std::get<ExplosionEvent::PropelledEntity>( event.target ),
                    event.kind == ExplosionEvent::Kind::MOB_MOVEMENT
                );
                break;
        };
        event_queue.pop();
    }
    return true;
}
References add_field(), explosion_handler::ExplosionEvent::BLAST, blast_tile(), cur_relative_time, event_queue, explosion_handler::ExplosionEvent::FIELD_ADDITION, explosion_handler::ExplosionEvent::FIELD_REMOVAL, is_animated(), explosion_handler::ExplosionEvent::ITEM_MOVEMENT, explosion_handler::ExplosionEvent::MOB_MOVEMENT, move_entity(), project_shrapnel(), remove_field(), explosion_handler::ExplosionEvent::SHRAPNEL, and update_timings().
Referenced by run().
project_shrapnel()
void explosion_handler::ExplosionProcess::project_shrapnel (const tripoint position) private
Definition at line 594 of file explosion.cpp.
{
    map &here = get_map();
    assert( shrapnel );
    if( is_occluded( center, position ) ) {
        return;
    }
    projectile fragment = shrapnel.value();
    fragment.add_effect( ammo_effect_NULL_SOURCE );
    auto critter = g->critter_at( position );
    if( critter && !critter->is_dead_state() ) {
        int damage_taken = 0;
        const auto bps = critter->get_all_body_parts( true );
        // Humans get hit in all body parts
        if( critter->is_player() ) {
            for( bodypart_id bp : bps ) {
                if( Character::bp_to_hp( bp->token ) == num_hp_parts ) {
                    continue;
                }
                // TODO: Apply projectile effects
                // TODO: Penalize low coverage armor
                // Halve damage to be closer to what monsters take
                damage_instance half_impact = fragment.impact;
                half_impact.mult_damage( 0.5f );
                dealt_damage_instance dealt = critter->deal_damage( emitter.value_or( nullptr ), bp,
                                              fragment.impact );
                if( dealt.total_damage() > 0 ) {
                    damage_taken += dealt.total_damage();
                }
            }
        } else {
            dealt_damage_instance dealt = critter->deal_damage( emitter.value_or( nullptr ), bps[0],
                                          fragment.impact );
            if( dealt.total_damage() > 0 ) {
                damage_taken += dealt.total_damage();
            }
            critter->check_dead_state();
        }
        mobs_shrapneled[critter] = damage_taken;
    }
    if( here.impassable( position ) ) {
        const int damage = fragment.impact.total_damage() * ExplosionConstants::SHRAPNEL_OBSTACLE_REDUCTION;
        if( optional_vpart_position vp = here.veh_at( position ) ) {
            vp->vehicle().damage( vp->part_index(), damage );
        } else {
            // Terrain should be affected by shrapnel less
            here.bash( position, damage, true );
        }
    }
    if( is_animated() ) {
        std::vector<tripoint> buf = line_to( position, center );
        buf.resize( 2 );
        g->draw_line( position, buf );
    }
    request_redraw |= true;
}
References projectile::add_effect(), ammo_effect_NULL_SOURCE, map::bash(), Character::bp_to_hp(), center, emitter, g, get_map(), projectile::impact, map::impassable(), is_animated(), is_occluded(), line_to(), mobs_shrapneled, damage_instance::mult_damage(), num_hp_parts, request_redraw, shrapnel, ExplosionConstants::SHRAPNEL_OBSTACLE_REDUCTION, damage_instance::total_damage(), dealt_damage_instance::total_damage(), and map::veh_at().
Referenced by process_next().
remove_field()
void explosion_handler::ExplosionProcess::remove_field (const tripoint position, const field_type_id target) private
Definition at line 903 of file explosion.cpp.
{
    map &here = get_map();
    here.remove_field( position, target );
    request_redraw |= position.z == g->u.posz();
}
References g, get_map(), map::remove_field(), request_redraw, and tripoint::z.
Referenced by process_next().
run()
void explosion_handler::ExplosionProcess::run ()
Definition at line 1018 of file explosion.cpp.
{
    fill_maps();
    init_event_queue();
    // We need to temporary disable it because
    //   larger explosions may end up filling
    //   the texture pool, causing a crash
    bool disable_minimap = is_animated() && pixel_minimap_option;
    if( disable_minimap ) {
        g->toggle_pixel_minimap();
    }
    map &here = get_map();
    while( process_next() ) {
        // No need to redraw in testing mode
        if( request_redraw && is_animated() ) {
            ui_manager::redraw();
            refresh_display();
            request_redraw = false;
        }
        update_timings();
    };
    // Reenable disabled options
    if( disable_minimap ) {
        g->toggle_pixel_minimap();
    }
    // Remove temporary flags
    for( int z = -OVERMAP_DEPTH; z <= OVERMAP_HEIGHT; z++ ) {
        for( const auto &pos : here.points_on_zlevel( z ) ) {
            for( auto &it : here.i_at( pos ) ) {
                it.unset_flag( "EXPLOSION_SMASHED" );
                it.unset_flag( "EXPLOSION_PROPELLED" );
            }
        }
    }
    // Make sure the map is centered around the player
    if( player_flung.has_value() ) {
        g->update_map( *player_flung.value() );
    }
    // Finally, recombine thrown items into full stacks again
    std::sort( recombination_targets.begin(), recombination_targets.end() );
    auto end = std::unique( recombination_targets.begin(), recombination_targets.end() );
    recombination_targets.erase( end, recombination_targets.end() );
    for( const auto &position : recombination_targets ) {
        std::vector<item> storage;
        for( item &it : here.i_at( position ) ) {
            storage.push_back( it );
        }
        here.i_clear( position );
        for( item &it : storage ) {
            here.add_item_or_charges( position, it );
        }
    }
}
References map::add_item_or_charges(), fill_maps(), g, get_map(), map::i_at(), map::i_clear(), init_event_queue(), is_animated(), OVERMAP_DEPTH, OVERMAP_HEIGHT, pixel_minimap_option, player_flung, map::points_on_zlevel(), process_next(), recombination_targets, ui_manager::redraw(), refresh_display(), request_redraw, and update_timings().
Referenced by explosion_handler::explosion_funcs::regular().
time_comparator()
static bool explosion_handler::ExplosionProcess::time_comparator (time_event_pair a, time_event_pair b) inline static private
Definition at line 379 of file explosion.cpp.
{
            return a.first < b.first;
        };
References a, and b.
update_timings()
void explosion_handler::ExplosionProcess::update_timings () inline private
Definition at line 383 of file explosion.cpp.
{
            if( !is_animated() ) {
                // Arbitrary large number since for null delays
                //   we just want to scroll thru events as fast as possible
                cur_relative_time += 1e6;
                return;
            }
            const int animation_delay = get_option<int>( "ANIMATION_DELAY" );
            const auto now = std::chrono::time_point_cast<std::chrono::milliseconds>
                             ( std::chrono::system_clock::now() ).time_since_epoch().count();
            const long long ms_diff = now - last_update_ms;
            // Multiplied by 10x to calibrate it such that at 10 animation delay, an explosion
            //   of radius 10 will take exactly 1 second to fully propagate
            const float rel_diff = static_cast<float>( ms_diff ) / ( 10.0 * animation_delay );
            cur_relative_time += rel_diff;
            last_update_ms = now;
        }
References cur_relative_time, is_animated(), and last_update_ms.
Referenced by process_next(), and run().
Member Data Documentation
blast_map
std::vector<dist_point_pair> explosion_handler::ExplosionProcess::blast_map private
Definition at line 331 of file explosion.cpp.
Referenced by fill_maps(), and init_event_queue().
blast_power
const int explosion_handler::ExplosionProcess::blast_power
Definition at line 314 of file explosion.cpp.
Referenced by blast_tile().
blast_radius
const int explosion_handler::ExplosionProcess::blast_radius
Definition at line 317 of file explosion.cpp.
Referenced by blast_tile(), and fill_maps().
center
const tripoint explosion_handler::ExplosionProcess::center
Definition at line 311 of file explosion.cpp.
Referenced by blast_tile(), fill_maps(), and project_shrapnel().
cur_relative_time
float explosion_handler::ExplosionProcess::cur_relative_time private
Definition at line 342 of file explosion.cpp.
Referenced by add_event(), blast_tile(), move_entity(), process_next(), and update_timings().
emitter
const std::optional<Creature *> explosion_handler::ExplosionProcess::emitter
Definition at line 326 of file explosion.cpp.
Referenced by blast_tile(), and project_shrapnel().
event_queue
std::priority_queue<time_event_pair, std::vector<time_event_pair>, pair_greater_cmp_first> explosion_handler::ExplosionProcess::event_queue private
Definition at line 334 of file explosion.cpp.
Referenced by add_event(), and process_next().
flung_set
std::set<const Creature *> explosion_handler::ExplosionProcess::flung_set private
Definition at line 339 of file explosion.cpp.
Referenced by blast_tile().
is_fiery
const bool explosion_handler::ExplosionProcess::is_fiery
Definition at line 320 of file explosion.cpp.
Referenced by blast_tile().
last_update_ms
long long explosion_handler::ExplosionProcess::last_update_ms private
Definition at line 343 of file explosion.cpp.
Referenced by update_timings().
mobs_blasted
std::map<const Creature *, int> explosion_handler::ExplosionProcess::mobs_blasted private
Definition at line 337 of file explosion.cpp.
Referenced by blast_tile(), and get_blasted().
mobs_shrapneled
std::map<const Creature *, int> explosion_handler::ExplosionProcess::mobs_shrapneled private
Definition at line 338 of file explosion.cpp.
Referenced by get_shrapneled(), and project_shrapnel().
player_flung
std::optional<player *> explosion_handler::ExplosionProcess::player_flung private
Definition at line 336 of file explosion.cpp.
Referenced by blast_tile(), and run().
recombination_targets
std::vector<tripoint> explosion_handler::ExplosionProcess::recombination_targets private
Definition at line 340 of file explosion.cpp.
Referenced by blast_tile(), move_entity(), and run().
request_redraw
bool explosion_handler::ExplosionProcess::request_redraw private
Definition at line 344 of file explosion.cpp.
Referenced by add_field(), blast_tile(), move_entity(), project_shrapnel(), remove_field(), and run().
shrapnel
const std::optional<projectile> explosion_handler::ExplosionProcess::shrapnel
Definition at line 323 of file explosion.cpp.
Referenced by fill_maps(), init_event_queue(), and project_shrapnel().
shrapnel_map
std::vector<dist_point_pair> explosion_handler::ExplosionProcess::shrapnel_map private
Definition at line 332 of file explosion.cpp.
Referenced by fill_maps(), and init_event_queue().
The documentation for this class was generated from the following file:
src/explosion.cpp