Cataclysm BN: achievement Class Reference
achievement Class Reference
#include <achievement.h>
Classes
class time_bound
Public Member Functions
achievement ()=default
void load (const JsonObject &, const std::string &)
void check () const
std::string ui_text (achievement_completion completion, const kill_tracker &kt) const
std::string skill_ui_text () const
std::string kill_ui_text (achievement_completion completion, const kill_tracker &kt) const
const translation & name () const
const translation & description () const
const std::vector< string_id< achievement > > & hidden_by () const
const std::optional< time_bound > & time_constraint () const
const std::map< mtype_id, std::pair< achievement_comparison, int > > & kill_requirements () const
const std::map< species_id, std::pair< achievement_comparison, int > > & species_kill_requirements () const
const std::map< skill_id, std::pair< achievement_comparison, int > > & skill_requirements () const
const std::vector< achievement_requirement > & requirements () const
Static Public Member Functions
static void load_achievement (const JsonObject &, const std::string &)
static void finalize ()
static void check_consistency ()
static const std::vector< achievement > & get_all ()
static void reset ()
Public Attributes
string_id< achievement > id
bool was_loaded = false
Private Member Functions
void add_kill_requirements (const JsonObject &jo, const std::string &src)
Retrieves kill requirement JsonObjects and feeds it to add_skill_requirement.
void add_kill_requirement (const JsonObject inner, const std::string &src)
Organizes variables provided and adds kill_requirements to achievements.
void add_skill_requirements (const JsonObject &jo, const std::string &src)
Retrieves skill requirement JsonObjects and feeds it to add_skill_requirement.
void add_skill_requirement (const JsonObject inner, const std::string &src)
Organizes variables provided and adds skill_requirements to achievements.
Private Attributes
translation name_
translation description_
std::vector< string_id< achievement > > hidden_by_
std::optional< time_bound > time_constraint_
std::map< skill_id, std::pair< achievement_comparison, int > > skill_requirements_
std::map< mtype_id, std::pair< achievement_comparison, int > > kill_requirements_
std::map< species_id, std::pair< achievement_comparison, int > > species_kill_requirements_
std::vector< achievement_requirement > requirements_
Detailed Description
Definition at line 57 of file achievement.h.
Constructor & Destructor Documentation
achievement()
achievement::achievement () default
Member Function Documentation
add_kill_requirement()
void achievement::add_kill_requirement (const JsonObject inner, const std::string & src) private
Organizes variables provided and adds kill_requirements to achievements.
Definition at line 231 of file achievement.cpp.
{
    if( inner.has_string( "monster" ) && inner.has_string( "species" ) ) {
        inner.throw_error( "Cannot have both id and species identifiers" );
    }
    if( inner.has_string( "monster" ) ) {
        const mtype_id victim = static_cast<mtype_id>( inner.get_string( "monster" ) );
        const achievement_comparison compare = inner.get_enum_value<achievement_comparison>( "is" );
        const int count = inner.get_int( "count" );
        kill_requirements_[victim] = std::make_pair( compare, count );
    } else if( inner.has_string( "species" ) ) {
        const species_id victim = static_cast<species_id>( inner.get_string( "species" ) );
        const achievement_comparison compare = inner.get_enum_value<achievement_comparison>( "is" );
        const int count = inner.get_int( "count" );
        species_kill_requirements_[victim] = std::make_pair( compare, count );
    } else {
        const achievement_comparison compare = inner.get_enum_value<achievement_comparison>( "is" );
        const int count = inner.get_int( "count" );
        kill_requirements_[mtype_id::NULL_ID()] = std::make_pair( compare, count );
    }
}
References game_menus::inv::compare(), detail::count(), JsonObject::get_enum_value(), JsonObject::get_int(), JsonObject::get_string(), JsonObject::has_string(), kill_requirements_, string_id< mtype >::NULL_ID(), species_kill_requirements_, and JsonObject::throw_error().
Referenced by add_kill_requirements().
add_kill_requirements()
void achievement::add_kill_requirements (const JsonObject & jo, const std::string & src) private
Retrieves kill requirement JsonObjects and feeds it to add_skill_requirement.
Definition at line 216 of file achievement.cpp.
{
    if( !jo.has_array( "kill_requirements" ) ) {
        return;
    }
    for( const JsonValue entry : jo.get_array( "kill_requirements" ) ) {
        if( entry.test_object() ) {
            add_kill_requirement( entry, src );
        } else {
            entry.throw_error( "array element is not an object." );
        }
    }
}
References add_kill_requirement(), JsonObject::get_array(), and JsonObject::has_array().
Referenced by load().
add_skill_requirement()
void achievement::add_skill_requirement (const JsonObject inner, const std::string & src) private
Organizes variables provided and adds skill_requirements to achievements.
Definition at line 271 of file achievement.cpp.
{
    const skill_id skill = static_cast<skill_id>( inner.get_string( "skill" ) );
    const achievement_comparison compare = inner.get_enum_value<achievement_comparison>( "is" );
    const int count = inner.get_int( "level" );
    skill_requirements_[skill] = std::make_pair( compare, count );
}
References game_menus::inv::compare(), detail::count(), JsonObject::get_enum_value(), JsonObject::get_int(), JsonObject::get_string(), and skill_requirements_.
Referenced by add_skill_requirements().
add_skill_requirements()
void achievement::add_skill_requirements (const JsonObject & jo, const std::string & src) private
Retrieves skill requirement JsonObjects and feeds it to add_skill_requirement.
Definition at line 256 of file achievement.cpp.
{
    if( !jo.has_array( "skill_requirements" ) ) {
        return;
    }
    for( const JsonValue entry : jo.get_array( "skill_requirements" ) ) {
        if( entry.test_object() ) {
            add_skill_requirement( entry, src );
        } else {
            entry.throw_error( "array element is not an object." );
        }
    }
}
References add_skill_requirement(), JsonObject::get_array(), and JsonObject::has_array().
Referenced by load().
check()
void achievement::check () const
Definition at line 684 of file achievement.cpp.
{
    for( const string_id<achievement> &a : hidden_by_ ) {
        if( !a.is_valid() ) {
            debugmsg( "Achievement %s specifies hidden_by achievement %s, but the latter does not "
                      "exist.", id.str(), a.str() );
        }
    }
    if( time_constraint_ ) {
        time_constraint_->check( id );
    }
    if( !skill_requirements_.empty() ) {
        for( const auto& [sk_id, pair] : skill_requirements_ ) {
            auto &&[comp, level] = pair;
            if( !sk_id.is_valid() ) {
                debugmsg( "Achievement %s specifies invalid skill requirement %s.", id.str(), sk_id.c_str() );
            } else if( comp == achievement_comparison::anything ) {
                debugmsg( "Achievement %s specifies invalid comparator for skill requirement %s.", id.str(),
                          sk_id.c_str() );
            } else if( level < 0 ) {
                debugmsg( "Achievement %s has negative value for skill requirement %s.", id.str(), sk_id.c_str() );
            }
        }
    }
    if( !kill_requirements_.empty() ) {
        for( const auto& [m_id, pair] : kill_requirements_ ) {
            auto &&[comp, count] = pair;
            if( !m_id.is_valid() ) {
                debugmsg( "Achievement %s specifies invalid kill requirement %s.", id.str(), m_id.c_str() );
            } else if( comp == achievement_comparison::anything ) {
                debugmsg( "Achievement %s specifies invalid comparator for kill requirement %s.", id.str(),
                          m_id.c_str() );
            } else if( count < 0 ) {
                debugmsg( "Achievement %s has negative count for kill requirement %s.", id.str(), m_id.c_str() );
            }
        }
    }
    if( !species_kill_requirements_.empty() ) {
        for( const auto& [fac_id, pair] : species_kill_requirements_ ) {
            auto &&[comp, count] = pair;
            if( !fac_id.is_valid() || fac_id.is_null() ) {
                debugmsg( "Achievement %s specifies invalid kill requirement %s.", id.str(), fac_id.c_str() );
            } else if( comp == achievement_comparison::anything ) {
                debugmsg( "Achievement %s specifies invalid comparator for kill requirement %s.", id.str(),
                          fac_id.c_str() );
            } else if( count < 0 ) {
                debugmsg( "Achievement %s has negative count for kill requirement %s.", id.str(), fac_id.c_str() );
            }
        }
    }
    for( const achievement_requirement &req : requirements_ ) {
        req.check( id );
    }
}
References a, anything, detail::count(), debugmsg, hidden_by_, kill_requirements_, requirements_, skill_requirements_, species_kill_requirements_, and time_constraint_.
check_consistency()
void achievement::check_consistency () static
Definition at line 653 of file achievement.cpp.
{
    achievement_factory.check();
}
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by DynamicDataLoader::check_consistency().
description()
const translation & achievement::description () const inline
Definition at line 80 of file achievement.h.
{
            return description_;
        }
References description_.
Referenced by achievement_tracker::ui_text(), achievement_state::ui_text(), and achievements_tracker::ui_text_for().
finalize()
void achievement::finalize () static
Definition at line 644 of file achievement.cpp.
{
    for( achievement &a : const_cast<std::vector<achievement>&>( achievement::get_all() ) ) {
        for( achievement_requirement &req : a.requirements_ ) {
            req.finalize();
        }
    }
}
References a, achievement_requirement::finalize(), and get_all().
Referenced by DynamicDataLoader::finalize_loaded_data().
get_all()
const std::vector< achievement > & achievement::get_all () static
Definition at line 658 of file achievement.cpp.
{
    return achievement_factory.get_all();
}
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by finalize(), and achievements_tracker::valid_achievements().
hidden_by()
const std::vector< string_id< achievement > > & achievement::hidden_by () const inline
Definition at line 84 of file achievement.h.
{
            return hidden_by_;
        }
References hidden_by_.
Referenced by achievements_tracker::is_hidden().
kill_requirements()
const std::map< mtype_id, std::pair< achievement_comparison, int > > & achievement::kill_requirements () const inline
Definition at line 113 of file achievement.h.
{
            return kill_requirements_;
        }
References kill_requirements_.
Referenced by kill_req_completed(), kill_ui_text(), and ui_text().
kill_ui_text()
std::string achievement::kill_ui_text (achievement_completion completion, const kill_tracker & kt) const
Definition at line 444 of file achievement.cpp.
{
    std::string kill_string;
    for( const auto& [m_id, pair] : kill_requirements() ) {
        auto& [comp, count] = pair;
        std::string cur_kills;
        std::string mon_name = m_id == mtype_id::NULL_ID() ? count > 1 ? "monsters" : "monster" :
                               m_id->nname( count );
        int kill_count = 0;
        std::string progress;
        bool comp_pass = false;
        // Don't waste time tallying kill count if the achievement has already failed.
        if( completion != achievement_completion::failed ) {
            kill_count = m_id == mtype_id::NULL_ID() ? kt.monster_kill_count() :
                         kt.kill_count( m_id );
            progress = string_format( ( " (%i/%i)" ), kill_count, count );
            comp_pass = ach_compare( comp, count, kill_count );
        }
        achievement_completion kill_status;
        switch( comp ) {
            case achievement_comparison::greater_equal:
                kill_status = comp_pass ? achievement_completion::completed : achievement_completion::pending;
                cur_kills = string_format( _( "Kill at least %i %s%s" ), count, mon_name, progress );
                break;
            case achievement_comparison::less_equal:
                kill_status = comp_pass ? achievement_completion::completed : achievement_completion::failed;
                if( count == 0 ) {
                    cur_kills = string_format( _( "Don't kill even a single %s" ), mon_name );
                } else {
                    cur_kills = string_format( _( "Kill no more than %i %s%s" ), count, mon_name, progress );
                }
                break;
            case achievement_comparison::anything:
                kill_status = achievement_completion::completed;
                cur_kills = string_format( "Kill any number of %s", mon_name );
                break;
            default:
                kill_status = achievement_completion::completed;
                break;
        }
        if( completion == achievement_completion::failed ) {
            kill_status = completion;
        }
        nc_color c = color_from_completion( kill_status );
        if( kill_status == achievement_completion::failed &&
            completion != achievement_completion::failed ) {
            cur_kills += _( " (failed)" );
        }
        kill_string += "  " + colorize( cur_kills, c ) + "\n";
    }
    for( const auto& [fac_id, pair] : species_kill_requirements() ) {
        auto& [comp, count] = pair;
        std::string cur_kills;
        std::string fac_name = fac_id->name.translated( count );
        int kill_count = 0;
        std::string progress;
        bool comp_pass = false;
        // Don't waste time tallying kill count if the achievement has already failed.
        if( completion != achievement_completion::failed ) {
            kill_count = kt.kill_count( fac_id );
            progress = string_format( ( " (%i/%i)" ), kill_count, count );
            comp_pass = ach_compare( comp, count, kill_count );
        }
        achievement_completion kill_status;
        switch( comp ) {
            case achievement_comparison::greater_equal:
                kill_status = comp_pass ? achievement_completion::completed : achievement_completion::pending;
                cur_kills = string_format( _( "Kill at least %i %s%s" ), count, fac_name, progress );
                break;
            case achievement_comparison::less_equal:
                kill_status = comp_pass ? achievement_completion::completed : achievement_completion::failed;
                if( count == 0 ) {
                    cur_kills = string_format( _( "Don't kill even a single %s" ), fac_name );
                } else {
                    cur_kills = string_format( _( "Kill no more than %i %s%s" ), count, fac_name, progress );
                }
                break;
            case achievement_comparison::anything:
                kill_status = achievement_completion::completed;
                cur_kills = string_format( "Kill any number of %s", fac_name );
                break;
            default:
                kill_status = achievement_completion::completed;
                break;
        }
        if( completion == achievement_completion::failed ) {
            kill_status = completion;
        }
        nc_color c = color_from_completion( kill_status );
        if( kill_status == achievement_completion::failed &&
            completion != achievement_completion::failed ) {
            cur_kills += _( " (failed)" );
        }
        kill_string += "  " + colorize( cur_kills, c ) + "\n";
    }
    return kill_string;
}
References _, ach_compare(), anything, c, color_from_completion(), colorize(), completed, detail::count(), failed, greater_equal, kill_tracker::kill_count(), kill_requirements(), less_equal, kill_tracker::monster_kill_count(), string_id< mtype >::NULL_ID(), pending, species_kill_requirements(), and string_format().
Referenced by ui_text().
load()
void achievement::load (const JsonObject & jo, const std::string & src)
Definition at line 668 of file achievement.cpp.
{
    mandatory( jo, was_loaded, "name", name_ );
    optional( jo, was_loaded, "description", description_ );
    optional( jo, was_loaded, "hidden_by", hidden_by_ );
    optional( jo, was_loaded, "time_constraint", time_constraint_ );
    mandatory( jo, was_loaded, "requirements", requirements_ );
    if( jo.has_member( "skill_requirements" ) ) {
        add_skill_requirements( jo, src );
    }
    if( jo.has_member( "kill_requirements" ) ) {
        add_kill_requirements( jo, src );
    }
}
References add_kill_requirements(), add_skill_requirements(), description_, JsonObject::has_member(), hidden_by_, mandatory(), name_, optional(), requirements_, time_constraint_, and was_loaded.
load_achievement()
void achievement::load_achievement (const JsonObject & jo, const std::string & src) static
Definition at line 639 of file achievement.cpp.
{
    achievement_factory.load( jo, src );
}
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by DynamicDataLoader::initialize().
name()
const translation & achievement::name () const inline
Definition at line 76 of file achievement.h.
{
            return name_;
        }
References name_.
Referenced by achievement_tracker::ui_text(), and achievement_state::ui_text().
requirements()
const std::vector< achievement_requirement > & achievement::requirements () const inline
Definition at line 123 of file achievement.h.
{
            return requirements_;
        }
References requirements_.
Referenced by ui_text(), and achievement_state::ui_text().
reset()
void achievement::reset () static
Definition at line 663 of file achievement.cpp.
{
    achievement_factory.reset();
}
References anonymous_namespace{achievement.cpp}::achievement_factory.
Referenced by DynamicDataLoader::unload_data().
skill_requirements()
const std::map< skill_id, std::pair< achievement_comparison, int > > & achievement::skill_requirements () const inline
Definition at line 120 of file achievement.h.
{
            return skill_requirements_;
        }
References skill_requirements_.
Referenced by skill_req_completed(), skill_ui_text(), and ui_text().
skill_ui_text()
std::string achievement::skill_ui_text () const
Definition at line 549 of file achievement.cpp.
{
    std::string skill_string;
    Character &u = get_player_character();
    for( const auto& [sk_id, pair] : skill_requirements() ) {
        auto& [comp, level] = pair;
        std::string cur_skill;
        achievement_completion skill_status;
        int sk_lvl = u.get_skill_level( sk_id );
        bool comp_pass = ach_compare( comp, level, sk_lvl );
        switch( comp ) {
            case achievement_comparison::greater_equal:
                skill_status = comp_pass ? achievement_completion::completed : achievement_completion::pending;
                cur_skill = string_format( _( "Attain skill level of %i in %s (%i/%i)" ), level, sk_id->name(),
                                           sk_lvl, level );
                break;
            case achievement_comparison::less_equal:
                skill_status = comp_pass ? achievement_completion::completed : achievement_completion::failed;
                cur_skill = string_format( _( "Stay at or below skill level of %i in %s (%i/%i)" ), level,
                                           sk_id->name(), sk_lvl, level );
                break;
            default:
                skill_status = achievement_completion::completed;
                break;
        }
        nc_color c = color_from_completion( skill_status );
        if( skill_status == achievement_completion::failed ) {
            cur_skill += _( " (failed)" );
        }
        skill_string += "  " + colorize( cur_skill, c ) + "\n";
    }
    return skill_string;
}
References _, ach_compare(), c, color_from_completion(), colorize(), completed, failed, get_player_character(), Character::get_skill_level(), greater_equal, less_equal, pending, skill_requirements(), and string_format().
Referenced by ui_text().
species_kill_requirements()
const std::map< species_id, std::pair< achievement_comparison, int > > & achievement::species_kill_requirements () const inline
Definition at line 116 of file achievement.h.
              {
            return species_kill_requirements_;
        }
References species_kill_requirements_.
Referenced by kill_req_completed(), kill_ui_text(), and ui_text().
time_constraint()
const std::optional< time_bound > & achievement::time_constraint () const inline
Definition at line 110 of file achievement.h.
{
            return time_constraint_;
        }
References time_constraint_.
Referenced by time_req_completed(), and ui_text().
ui_text()
std::string achievement::ui_text (achievement_completion completion, const kill_tracker & kt) const
Definition at line 426 of file achievement.cpp.
{
    std::string requirements;
    if( time_constraint() ) {
        requirements += "  " + time_constraint()->time_ui_text( time_req_completed( *this ) ) + "\n";
    }
    if( !skill_requirements().empty() ) {
        requirements += skill_ui_text();
    }
    if( !kill_requirements().empty() || !species_kill_requirements().empty() ) {
        requirements += kill_ui_text( completion, kt );
    }
    return requirements;
}
References kill_requirements(), kill_ui_text(), requirements(), skill_requirements(), skill_ui_text(), species_kill_requirements(), time_constraint(), and time_req_completed().
Referenced by achievement_tracker::ui_text(), and achievement_state::ui_text().
Member Data Documentation
description_
translation achievement::description_ private
Definition at line 128 of file achievement.h.
Referenced by description(), and load().
hidden_by_
std::vector<string_id<achievement> > achievement::hidden_by_ private
Definition at line 129 of file achievement.h.
Referenced by check(), hidden_by(), and load().
id
string_id<achievement> achievement::id
Definition at line 73 of file achievement.h.
Referenced by achievements_tracker::is_hidden(), and achievements_tracker::ui_text_for().
kill_requirements_
std::map<mtype_id, std::pair<achievement_comparison, int> > achievement::kill_requirements_ private
Definition at line 132 of file achievement.h.
Referenced by add_kill_requirement(), check(), and kill_requirements().
name_
translation achievement::name_ private
Definition at line 127 of file achievement.h.
Referenced by load(), and name().
requirements_
std::vector<achievement_requirement> achievement::requirements_ private
Definition at line 134 of file achievement.h.
Referenced by check(), load(), and requirements().
skill_requirements_
std::map<skill_id, std::pair<achievement_comparison, int> > achievement::skill_requirements_ private
Definition at line 131 of file achievement.h.
Referenced by add_skill_requirement(), check(), and skill_requirements().
species_kill_requirements_
std::map<species_id, std::pair<achievement_comparison, int> > achievement::species_kill_requirements_ private
Definition at line 133 of file achievement.h.
Referenced by add_kill_requirement(), check(), and species_kill_requirements().
time_constraint_
std::optional<time_bound> achievement::time_constraint_ private
Definition at line 130 of file achievement.h.
Referenced by check(), load(), and time_constraint().
was_loaded
bool achievement::was_loaded = false
Definition at line 74 of file achievement.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/achievement.h
src/achievement.cpp