Cataclysm BN: bodypart Class Reference
bodypart Class Reference
#include <bodypart.h>
Public Member Functions
bodypart ()
bodypart (bodypart_str_id id)
bodypart_id get_id () const
void set_hp_to_max ()
bool is_at_max_hp () const
int get_hp_cur () const
int get_hp_max () const
int get_healed_total () const
int get_damage_bandaged () const
int get_damage_disinfected () const
void set_hp_cur (int set)
void set_hp_max (int set)
void set_healed_total (int set)
void set_damage_bandaged (int set)
void set_damage_disinfected (int set)
void mod_hp_cur (int mod)
void mod_hp_max (int mod)
void mod_healed_total (int mod)
void mod_damage_bandaged (int mod)
void mod_damage_disinfected (int mod)
void serialize (JsonOut &json) const
void deserialize (JsonIn &jsin)
Public Attributes
wield_status wielding
Private Attributes
bodypart_str_id id
int hp_cur
int hp_max
int healed_total = 0
int damage_bandaged = 0
Not used yet.
int damage_disinfected = 0
Detailed Description
Definition at line 163 of file bodypart.h.
Constructor & Destructor Documentation
bodypart() [1/2]
bodypart::bodypart () inline
Definition at line 181 of file bodypart.h.
: id(bodypart_str_id("num_bp")), hp_cur(0), hp_max(0) {}
bodypart() [2/2]
bodypart::bodypart (bodypart_str_id id) inline
Definition at line 182 of file bodypart.h.
: id(id), hp_cur(id->base_hp), hp_max(id->base_hp)  {}
Member Function Documentation
deserialize()
void bodypart::deserialize (JsonIn & jsin)
Definition at line 483 of file bodypart.cpp.
{
    JsonObject jo = jsin.get_object();
    jo.read( "id", id, true );
    jo.read( "hp_cur", hp_cur, true );
    jo.read( "hp_max", hp_max, true );
    jo.read( "damage_bandaged", damage_bandaged, true );
    jo.read( "damage_disinfected", damage_disinfected, true );
}
References damage_bandaged, damage_disinfected, JsonIn::get_object(), hp_cur, hp_max, and JsonObject::read().
get_damage_bandaged()
int bodypart::get_damage_bandaged () const
Definition at line 412 of file bodypart.cpp.
{
    return damage_bandaged;
}
References damage_bandaged.
get_damage_disinfected()
int bodypart::get_damage_disinfected () const
Definition at line 417 of file bodypart.cpp.
{
    return damage_disinfected;
}
References damage_disinfected.
get_healed_total()
int bodypart::get_healed_total () const
Definition at line 407 of file bodypart.cpp.
{
    return healed_total;
}
References healed_total.
Referenced by Creature::get_part_healed_total().
get_hp_cur()
int bodypart::get_hp_cur () const
Definition at line 397 of file bodypart.cpp.
{
    return hp_cur;
}
References hp_cur.
Referenced by Character::calc_all_parts_hp(), Creature::get_part_hp_cur(), and heal_actor::use_healing_item().
get_hp_max()
int bodypart::get_hp_max () const
Definition at line 402 of file bodypart.cpp.
{
    return hp_max;
}
References hp_max.
Referenced by Character::calc_all_parts_hp(), Creature::get_part_hp_max(), and heal_actor::use_healing_item().
get_id()
bodypart_id bodypart::get_id () const
Definition at line 382 of file bodypart.cpp.
{
    return id;
}
References id.
Referenced by heal_actor::use_healing_item().
is_at_max_hp()
bool bodypart::is_at_max_hp () const
Definition at line 392 of file bodypart.cpp.
{
    return hp_cur == hp_max;
}
References hp_cur, and hp_max.
mod_damage_bandaged()
void bodypart::mod_damage_bandaged (int mod)
Definition at line 462 of file bodypart.cpp.
{
    damage_bandaged += mod;
}
References damage_bandaged.
mod_damage_disinfected()
void bodypart::mod_damage_disinfected (int mod)
Definition at line 467 of file bodypart.cpp.
{
    damage_disinfected += mod;
}
References damage_disinfected.
mod_healed_total()
void bodypart::mod_healed_total (int mod)
Definition at line 457 of file bodypart.cpp.
{
    healed_total += mod;
}
References healed_total.
Referenced by Creature::mod_part_healed_total().
mod_hp_cur()
void bodypart::mod_hp_cur (int mod)
Definition at line 447 of file bodypart.cpp.
{
    hp_cur += mod;
}
References hp_cur.
Referenced by Creature::mod_part_hp_cur().
mod_hp_max()
void bodypart::mod_hp_max (int mod)
Definition at line 452 of file bodypart.cpp.
{
    hp_max += mod;
}
References hp_max.
Referenced by Creature::mod_part_hp_max().
serialize()
void bodypart::serialize (JsonOut & json) const
Definition at line 472 of file bodypart.cpp.
{
    json.start_object();
    json.member( "id", id );
    json.member( "hp_cur", hp_cur );
    json.member( "hp_max", hp_max );
    json.member( "damage_bandaged", damage_bandaged );
    json.member( "damage_disinfected", damage_disinfected );
    json.end_object();
}
References damage_bandaged, damage_disinfected, JsonOut::end_object(), hp_cur, hp_max, JsonOut::member(), and JsonOut::start_object().
set_damage_bandaged()
void bodypart::set_damage_bandaged (int set)
Definition at line 437 of file bodypart.cpp.
{
    damage_bandaged = set;
}
References damage_bandaged.
set_damage_disinfected()
void bodypart::set_damage_disinfected (int set)
Definition at line 442 of file bodypart.cpp.
{
    damage_disinfected = set;
}
References damage_disinfected.
set_healed_total()
void bodypart::set_healed_total (int set)
Definition at line 432 of file bodypart.cpp.
{
    healed_total = set;
}
References healed_total.
Referenced by Creature::set_part_healed_total().
set_hp_cur()
void bodypart::set_hp_cur (int set)
Definition at line 422 of file bodypart.cpp.
{
    hp_cur = set;
}
References hp_cur.
Referenced by Character::calc_all_parts_hp(), and Creature::set_part_hp_cur().
set_hp_max()
void bodypart::set_hp_max (int set)
Definition at line 427 of file bodypart.cpp.
{
    hp_max = set;
}
References hp_max.
Referenced by Character::calc_all_parts_hp(), and Creature::set_part_hp_max().
set_hp_to_max()
void bodypart::set_hp_to_max ()
Definition at line 387 of file bodypart.cpp.
{
    hp_cur = hp_max;
}
References hp_cur, and hp_max.
Member Data Documentation
damage_bandaged
int bodypart::damage_bandaged = 0 private
Not used yet.
Definition at line 173 of file bodypart.h.
Referenced by deserialize(), get_damage_bandaged(), mod_damage_bandaged(), serialize(), and set_damage_bandaged().
damage_disinfected
int bodypart::damage_disinfected = 0 private
Definition at line 174 of file bodypart.h.
Referenced by deserialize(), get_damage_disinfected(), mod_damage_disinfected(), serialize(), and set_damage_disinfected().
healed_total
int bodypart::healed_total = 0 private
Definition at line 171 of file bodypart.h.
Referenced by get_healed_total(), mod_healed_total(), and set_healed_total().
hp_cur
int bodypart::hp_cur private
Definition at line 168 of file bodypart.h.
Referenced by deserialize(), get_hp_cur(), is_at_max_hp(), mod_hp_cur(), serialize(), set_hp_cur(), and set_hp_to_max().
hp_max
int bodypart::hp_max private
Definition at line 169 of file bodypart.h.
Referenced by deserialize(), get_hp_max(), is_at_max_hp(), mod_hp_max(), serialize(), set_hp_max(), and set_hp_to_max().
id
bodypart_str_id bodypart::id private
Definition at line 166 of file bodypart.h.
Referenced by get_id().
wielding
wield_status bodypart::wielding
Definition at line 178 of file bodypart.h.
Referenced by Character::primary_weapon(), Character::set_primary_weapon(), and Character::wielded_items().
The documentation for this class was generated from the following files:
src/bodypart.h
src/bodypart.cpp