Cataclysm BN: src/consumption.h File Reference
consumption.h File Reference
#include <list>
#include "calendar.h"
#include "type_id.h"
Classes
struct consumption_event
struct consumption_history_t
Macros
#define CATA_SRC_CONSUMPTION_H
Functions
bool query_consume_ownership (item &target, avatar &you)
Macro Definition Documentation
CATA_SRC_CONSUMPTION_H
#define CATA_SRC_CONSUMPTION_H
Definition at line 3 of file consumption.h.
Function Documentation
query_consume_ownership()
bool query_consume_ownership (item & target, avatar & you)
Definition at line 1491 of file consumption.cpp.
{
    //Add in a reset here to make sure user keeps getting asked if not set to keep thief setting
    if( you.get_value( "THIEF_MODE_KEEP" ) != "YES" ) {
        you.set_value( "THIEF_MODE", "THIEF_ASK" );
    }
    if( !target.is_owned_by( you, true ) ) {
        bool choice = true;
        if( you.get_value( "THIEF_MODE" ) == "THIEF_ASK" ) {
            choice = pickup::query_thief();
        }
        if( you.get_value( "THIEF_MODE" ) == "THIEF_HONEST" || !choice ) {
            return false;
        }
        avatar_funcs::handle_theft_witnesses( you, target.get_owner() );
    }
    return true;
}
References item::get_owner(), Creature::get_value(), avatar_funcs::handle_theft_witnesses(), item::is_owned_by(), pickup::query_thief(), and Creature::set_value().
Referenced by Character::consume_item(), and avatar_funcs::unload_item().