Cataclysm BN: src/debug.cpp File Reference
debug.cpp File Reference
#include "debug.h"
#include <algorithm>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <fstream>
#include <iomanip>
#include <iterator>
#include <locale>
#include <map>
#include <memory>
#include <optional>
#include <ostream>
#include <regex>
#include <set>
#include <sstream>
#include <sys/stat.h>
#include <type_traits>
#include <utility>
#include <vector>
#include "catalua.h"
#include "cata_utility.h"
#include "cached_options.h"
#include "color.h"
#include "cursesdef.h"
#include "enum_bitset.h"
#include "enum_conversions.h"
#include "filesystem.h"
#include "get_version.h"
#include "input.h"
#include "language.h"
#include "mod_manager.h"
#include "options.h"
#include "output.h"
#include "path_info.h"
#include "point.h"
#include "string_utils.h"
#include "translations.h"
#include "type_id.h"
#include "ui_manager.h"
#include "worldfactory.h"
#include <sys/time.h>
Classes
class capture_debugmsg
Class for capturing debugmsg, used by capture_debugmsg_during.
struct buffered_prompt_info
struct time_info
struct repetition_folder
class NullStream
struct DebugFile
Namespaces
namespace anonymous_namespace{debug.cpp}
namespace io
Functions
std::string capture_debugmsg_during (const std::function< void()> &func)
Capturing debug messages during func execution, used to test debugmsg calls in the unit tests.
bool debug_has_error_been_observed ()
static std::vector< buffered_prompt_info > & buffered_prompts ()
static void debug_error_prompt (const char *filename, const char *line, const char *funcname, const char *text, bool force)
void replay_buffered_debugmsg_prompts ()
Should be called after catacurses::stdscr is initialized.
static time_info get_time () noexcept
static void output_repetitions (std::ostream &out)
void realDebugmsg (const char *filename, const char *line, const char *funcname, const std::string &text)
template<typename E >
static std::string fmt_mask (const enum_bitset< E > &mask)
void setDebugLogLevels (const enum_bitset< DL > &mask, bool silent)
Set debug levels that should be logged.
void setDebugLogClasses (const enum_bitset< DC > &mask, bool silent)
Set debug classes that should be logged.
static bool checkDebugLevelClass (DL lev, DC cl)
void debug_reset_ignored_messages ()
Reset any ignored debug messages.
static DebugFile & debugFile ()
void setupDebug (DebugOutput output_mode)
Initializes the debugging system, called exactly once from main()
void deinitDebug ()
Opposite of setupDebug, shuts the debugging system down.
template<>
std::string io::enum_to_string< DL > (DL x)
template<>
std::string io::enum_to_string< DC > (DC x)
std::optional< int > get_os_bitness ()
Retrieves OS bitness (32, 64 or nullopt if detection failed)
Variables
bool dont_debugmsg = false
If true, disables all debug messages.
static enum_bitset< DL > debugLevel
static enum_bitset< DC > debugClass
static bool buffering_debugmsgs = true
True during game startup, when debugmsgs cannot be displayed yet.
static bool error_observed = false
Set to true when any error is logged.
static bool capturing = false
If true, debug messages will be captured, used to test debugmsg calls in the unit tests.
static std::string captured
сaptured debug messages
std::set< std::string > anonymous_namespace{debug.cpp}::ignored_messages
static repetition_folder rep_folder
Function Documentation
buffered_prompts()
static std::vector< buffered_prompt_info > & buffered_prompts () static
Definition at line 232 of file debug.cpp.
{
    static std::vector<buffered_prompt_info> buffered_prompts;
    return buffered_prompts;
}
References buffered_prompts().
Referenced by buffered_prompts(), realDebugmsg(), and replay_buffered_debugmsg_prompts().
capture_debugmsg_during()
std::string capture_debugmsg_during (const std::function< void()> & func)
Capturing debug messages during func execution, used to test debugmsg calls in the unit tests.
Returns
std::string debugmsg
Definition at line 186 of file debug.cpp.
{
    capture_debugmsg capture;
    func();
    return capture.dmsg();
}
References capture_debugmsg::dmsg().
checkDebugLevelClass()
static bool checkDebugLevelClass (DL lev, DC cl) static
Definition at line 552 of file debug.cpp.
{
    if( lev == DL::Error || cl == DC::DebugMsg ) {
        return true;
    } else {
        return debugClass.test( cl ) && debugLevel.test( lev );
    }
}
References debugClass, debugLevel, DebugMsg, and Error.
Referenced by detail::realDebugLog().
debug_error_prompt()
static void debug_error_prompt (const char * filename, const char * line, const char * funcname, const char * text, bool force) static
Definition at line 238 of file debug.cpp.
{
    assert( catacurses::stdscr );
    assert( filename != nullptr );
    assert( line != nullptr );
    assert( funcname != nullptr );
    assert( text != nullptr );
    std::string msg_key( filename );
    msg_key += line;
    if( !force && ignored_messages.count( msg_key ) > 0 ) {
        return;
    }
    std::string formatted_report = [&]() {
        const char *repetition_string =
            _( "Excessive error repetition detected.  Please file a bug report at https://github.com/cataclysmbnteam/Cataclysm-BN/issues" );
        // try to prepend repetition string if we are forcing the display. Right now that's the only reason for this prompt to display.
        std::string pre = force ? string_format(
                              "            %s\n",
                              repetition_string
                          ) : "";
        return string_format(
                   "%s"
                   " DEBUG    : %s\n\n"
                   " FUNCTION : %s\n"
                   " FILE     : %s\n"
                   " LINE     : %s\n"
                   " VERSION  : BN %s\n",
                   pre, text, funcname, filename, line, getVersionString()
               );
    }
    ();
#if defined(BACKTRACE)
    std::string backtrace_instructions =
        string_format(
            _( "See %s for a full stack backtrace" ),
            PATH_INFO::debug()
        );
#endif
    // Create a special debug message UI that does various things to ensure
    // the graphics are correct when the debug message is displayed during a
    // redraw callback.
    ui_adaptor ui( ui_adaptor::debug_message_ui {} );
    const auto init_window = []( ui_adaptor & ui ) {
        ui.position_from_window( catacurses::stdscr );
    };
    init_window( ui );
    ui.on_screen_resize( init_window );
    const std::string message = string_format(
                                    "\n\n" // Looks nicer with some space
                                    " %s\n" // translated user string: error notification
                                    " -----------------------------------------------------------\n"
                                    "%s"
                                    " -----------------------------------------------------------\n"
#if defined(BACKTRACE)
                                    " %s\n" // translated user string: where to find backtrace
#endif
                                    " %s\n" // translated user string: space to continue
                                    " %s\n" // translated user string: ignore key
#if defined(TILES)
                                    " %s\n" // translated user string: copy
#endif // TILES
                                    , _( "An error has occurred!  Written below is the error report:" ),
                                    formatted_report,
#if defined(BACKTRACE)
                                    backtrace_instructions,
#endif
                                    _( "Press <color_white>space bar</color> to continue the game." ),
                                    _( "Press <color_white>I</color> (or <color_white>i</color>) to also ignore this particular message in the future." )
#if defined(TILES)
                                    , _( "Press <color_white>C</color> (or <color_white>c</color>) to copy this message to the clipboard." )
#endif // TILES
                                );
    ui.on_redraw( [&]( const ui_adaptor & ) {
        catacurses::erase();
        fold_and_print( catacurses::stdscr, point_zero, getmaxx( catacurses::stdscr ), c_light_red,
                        "%s", message );
        wnoutrefresh( catacurses::stdscr );
    } );
#if defined(__ANDROID__)
    input_context ctxt( "DEBUG_MSG" );
    ctxt.register_manual_key( 'C' );
    ctxt.register_manual_key( 'I' );
    ctxt.register_manual_key( ' ' );
#endif
    for( bool stop = false; !stop && !dont_debugmsg; ) {
        ui_manager::redraw();
        switch( inp_mngr.get_input_event().get_first_input() ) {
#if defined(TILES)
            case 'c':
            case 'C':
                SDL_SetClipboardText( formatted_report.c_str() );
                break;
#endif // TILES
            case 'i':
            case 'I':
                ignored_messages.insert( msg_key );
            /* fallthrough */
            case ' ':
                stop = true;
                break;
        }
    }
}
References _, c_light_red, PATH_INFO::debug(), dont_debugmsg, catacurses::erase(), fold_and_print(), input_event::get_first_input(), input_manager::get_input_event(), catacurses::getmaxx(), getVersionString(), anonymous_namespace{debug.cpp}::ignored_messages, init_window(), inp_mngr, line(), mapgen_defer::message, point_zero, ui_manager::redraw(), catacurses::stdscr, string_format(), and catacurses::wnoutrefresh().
Referenced by realDebugmsg(), and replay_buffered_debugmsg_prompts().
debug_has_error_been_observed()
bool debug_has_error_been_observed ()
Returns
true if any error has been logged in this run.
Definition at line 210 of file debug.cpp.
{
    return error_observed;
}
References error_observed.
Referenced by init::check_mods_for_errors().
debug_reset_ignored_messages()
void debug_reset_ignored_messages ()
Reset any ignored debug messages.
Definition at line 561 of file debug.cpp.
{
    ignored_messages.clear();
}
References anonymous_namespace{debug.cpp}::ignored_messages.
Referenced by debug_menu::debug().
debugFile()
static DebugFile & debugFile () static
Definition at line 633 of file debug.cpp.
{
    static DebugFile debugFile;
    return debugFile;
}
References debugFile().
Referenced by debugFile(), deinitDebug(), detail::realDebugLog(), and setupDebug().
deinitDebug()
void deinitDebug ()
Opposite of setupDebug, shuts the debugging system down.
Definition at line 717 of file debug.cpp.
{
    debugFile().deinit();
}
References debugFile(), and DebugFile::deinit().
Referenced by exit_handler().
fmt_mask()
template<typename E > static std::string fmt_mask (const enum_bitset< E > & mask) static
Definition at line 503 of file debug.cpp.
{
    if( mask.test_all() ) {
        return "ALL";
    } else if( !mask.test_any() ) {
        return "NONE";
    } else {
        std::stringstream ss;
        ss << "[";
        bool first = true;
        for( size_t i = 0; i < enum_bitset<E>::size(); i++ ) {
            E &&e = static_cast<E>( i );
            if( !mask.test( e ) ) {
                continue;
            }
            if( first ) {
                first = false;
            } else {
                ss << " ";
            }
            ss << io::enum_to_string<E>( e );
        }
        ss << "]";
        return ss.str();
    }
}
References om_direction::size, enum_bitset< E >::test(), enum_bitset< E >::test_all(), and enum_bitset< E >::test_any().
Referenced by setDebugLogClasses(), and setDebugLogLevels().
get_os_bitness()
std::optional< int > get_os_bitness ()
Retrieves OS bitness (32, 64 or nullopt if detection failed)
Definition at line 1824 of file debug.cpp.
{
#if defined(_WIN32)
    SYSTEM_INFO si;
    GetNativeSystemInfo( &si );
    switch( si.wProcessorArchitecture ) {
        case PROCESSOR_ARCHITECTURE_AMD64:
            return 64;
        case PROCESSOR_ARCHITECTURE_INTEL:
            return 32;
        default:
            // FIXME: other architectures?
            break;
    }
#elif defined(__linux__) && !defined(__ANDROID__)
    std::string output;
    output = shell_exec( "getconf LONG_BIT" );
    if( !output.empty() ) {
        // remove trailing '\n', if any.
        output.erase( std::remove( output.begin(), output.end(), '\n' ),
                      output.end() );
    }
    if( output == "64" ) {
        return 64;
    } else if( output == "32" ) {
        return 32;
    }
#endif
    // FIXME: osx, android
    return std::nullopt;
}
Referenced by main_menu::opening_screen().
get_time()
static time_info get_time () static noexcept
Definition at line 598 of file debug.cpp.
{
    timeval tv;
    gettimeofday( &tv, nullptr );
    const auto tt      = time_t {tv.tv_sec};
    const auto current = localtime( &tt );
    return time_info { current->tm_hour, current->tm_min, current->tm_sec,
                       static_cast<int>( std::lround( tv.tv_usec / 1000.0 ) )
                     };
}
Referenced by DebugFile::deinit(), DebugFile::init(), detail::realDebugLog(), repetition_folder::set_time(), and repetition_folder::timed_out().
output_repetitions()
void output_repetitions (std::ostream & out) static
Definition at line 1352 of file debug.cpp.
{
    // Need to complete the folding
    if( rep_folder.repeat_count > 0 ) {
        if( rep_folder.repeat_count > 1 ) {
            out << "[ Previous repeated " << ( rep_folder.repeat_count - 1 ) << " times ]";
        }
        out << std::endl;
        out << rep_folder.m_time << " ";
        // repetition folding is only done through realDebugmsg
        out << io::enum_to_string<DL>( DL::Error ) << " ";
        out << io::enum_to_string<DC>( DC::DebugMsg ) << " ";
        out << ": ";
        out << rep_folder.m_filename << ":" << rep_folder.m_line << " [" << rep_folder.m_funcname << "] " <<
            rep_folder.m_text << std::endl;
        rep_folder.reset();
    }
}
References DebugMsg, io::enum_to_string< DC >(), io::enum_to_string< DL >(), Error, repetition_folder::m_filename, repetition_folder::m_funcname, repetition_folder::m_line, repetition_folder::m_text, repetition_folder::m_time, rep_folder, repetition_folder::repeat_count, and repetition_folder::reset().
Referenced by DebugFile::deinit(), and detail::realDebugLog().
realDebugmsg()
void realDebugmsg (const char * filename, const char * line, const char * funcname, const std::string & text)
Definition at line 457 of file debug.cpp.
{
    assert( filename != nullptr );
    assert( line != nullptr );
    assert( funcname != nullptr );
    if( capturing ) {
        captured += text;
    } else {
        if( !rep_folder.test( filename, line, funcname, text ) ) {
            *detail::realDebugLog( DL::Error, DC::DebugMsg, filename, line, funcname ) << text;
            rep_folder.set( filename, line, funcname, text );
        } else {
            rep_folder.increment_count();
        }
    }
    if( test_mode ) {
        return;
    }
    // Show excessive repetition prompt once per excessive set
    bool excess_repetition = rep_folder.repeat_count == repetition_folder::repetition_threshold;
    if( buffering_debugmsgs ) {
        buffered_prompts().push_back( {filename, line, funcname, text, false } );
        if( excess_repetition ) {
            buffered_prompts().push_back( {filename, line, funcname, text, true } );
        }
        return;
    }
    debug_error_prompt( filename, line, funcname, text.c_str(), false );
    if( excess_repetition ) {
        debug_error_prompt( filename, line, funcname, text.c_str(), true );
        // Do not count this prompt when considering repetition folding
        // Might look weird in the log if the repetitions end exactly after this prompt is displayed.
        rep_folder.set_time();
    }
}
References buffered_prompts(), buffering_debugmsgs, captured, capturing, debug_error_prompt(), DebugMsg, Error, repetition_folder::increment_count(), line(), detail::realDebugLog(), rep_folder, repetition_folder::repeat_count, repetition_folder::repetition_threshold, repetition_folder::set(), repetition_folder::set_time(), repetition_folder::test(), and test_mode.
Referenced by realDebugmsg().
replay_buffered_debugmsg_prompts()
void replay_buffered_debugmsg_prompts ()
Should be called after catacurses::stdscr is initialized.
If catacurses::stdscr is available, shows all buffered debugmsg prompts.
Definition at line 353 of file debug.cpp.
{
    if( !buffering_debugmsgs ) {
        return;
    }
    buffering_debugmsgs = false;
    for( const auto &prompt : buffered_prompts() ) {
        debug_error_prompt(
            prompt.filename.c_str(),
            prompt.line.c_str(),
            prompt.funcname.c_str(),
            prompt.text.c_str(),
            prompt.force
        );
    }
    buffered_prompts().clear();
}
References buffered_prompts(), buffering_debugmsgs, debug_error_prompt(), and pickup::prompt.
Referenced by main().
setDebugLogClasses()
void setDebugLogClasses (const enum_bitset< DC > & mask, bool silent)
Set debug classes that should be logged.
Definition at line 541 of file debug.cpp.
{
    if( mask == debugClass ) {
        return;
    }
    if( !silent ) {
        DebugLog( DL::Info, DC::Main ) << "Set debug classes to: " << fmt_mask( mask );
    }
    debugClass = mask;
}
References debugClass, DebugLog, fmt_mask(), Info, Main, and silent.
Referenced by options_manager::cache_to_globals(), and setupDebug().
setDebugLogLevels()
void setDebugLogLevels (const enum_bitset< DL > & mask, bool silent)
Set debug levels that should be logged.
Definition at line 530 of file debug.cpp.
{
    if( mask == debugLevel ) {
        return;
    }
    if( !silent ) {
        DebugLog( DL::Info, DC::Main ) << "Set debug levels to: " << fmt_mask( mask );
    }
    debugLevel = mask;
}
References debugLevel, DebugLog, fmt_mask(), Info, Main, and silent.
Referenced by options_manager::cache_to_globals(), and setupDebug().
setupDebug()
void setupDebug (DebugOutput output_mode)
Initializes the debugging system, called exactly once from main()
Definition at line 710 of file debug.cpp.
{
    setDebugLogLevels( enum_bitset<DL>().set( DL::Info ).set( DL::Warn ).set( DL::Error ), true );
    setDebugLogClasses( enum_bitset<DC>().set( DC::Main ).set( DC::DebugMsg ), true );
    debugFile().init( output_mode, PATH_INFO::debug() );
}
References PATH_INFO::debug(), debugFile(), DebugMsg, Error, Info, DebugFile::init(), Main, luna::set(), setDebugLogClasses(), setDebugLogLevels(), and Warn.
Referenced by main().
Variable Documentation
buffering_debugmsgs
bool buffering_debugmsgs = true static
True during game startup, when debugmsgs cannot be displayed yet.
Definition at line 104 of file debug.cpp.
Referenced by realDebugmsg(), and replay_buffered_debugmsg_prompts().
captured
std::string captured static
сaptured debug messages
Definition at line 114 of file debug.cpp.
Referenced by capture_debugmsg::capture_debugmsg(), capture_debugmsg::dmsg(), and realDebugmsg().
capturing
bool capturing = false static
If true, debug messages will be captured, used to test debugmsg calls in the unit tests.
Definition at line 112 of file debug.cpp.
Referenced by capture_debugmsg::capture_debugmsg(), capture_debugmsg::dmsg(), realDebugmsg(), and capture_debugmsg::~capture_debugmsg().
debugClass
enum_bitset<DC> debugClass static
Definition at line 101 of file debug.cpp.
Referenced by checkDebugLevelClass(), and setDebugLogClasses().
debugLevel
enum_bitset<DL> debugLevel static
Definition at line 100 of file debug.cpp.
Referenced by checkDebugLevelClass(), and setDebugLogLevels().
dont_debugmsg
bool dont_debugmsg = false
If true, disables all debug messages.
Only used for debugging "weird" saves.
Definition at line 94 of file debug.cpp.
Referenced by debug_error_prompt(), and main().
error_observed
bool error_observed = false static
Set to true when any error is logged.
Definition at line 107 of file debug.cpp.
Referenced by debug_has_error_been_observed(), and detail::realDebugLog().
rep_folder
repetition_folder rep_folder static
Definition at line 454 of file debug.cpp.
Referenced by output_repetitions(), and realDebugmsg().