Cataclysm BN: src/debug.h File Reference
debug.h File Reference
#include <iostream>
#include <optional>
#include <string>
#include <type_traits>
#include <utility>
#include <functional>
#include "string_formatter.h"
Classes
struct enum_traits< DL >
struct enum_traits< DC >
class detail::DebugLogGuard
Debug log guard.
Namespaces
namespace game_info
Used to generate game report information.
namespace detail
Macros
#define CATA_SRC_DEBUG_H
#define STRING2(x) #x
#define STRING(x) STRING2(x)
#define __FUNCTION_NAME__ __func__
#define debugmsg(...) realDebugmsg(__FILE__, STRING(__LINE__), __FUNCTION_NAME__, __VA_ARGS__)
Debug message of level DL::Error and class DC::DebugMsg, also includes the source file name and line, uses varg style arguments, the first argument must be a printf style format string.
#define constexpr_fatal(ret, ...) do { debugmsg(__VA_ARGS__); abort(); } while(false)
#define DebugLog(lev, cl) *detail::realDebugLog(lev, cl, nullptr, nullptr, nullptr)
DebugLog.
#define DebugLogFL(lev, cl) *detail::realDebugLog(lev, cl, __FILE__, STRING(__LINE__), nullptr)
Like DebugLog, but includes source file name and line number.
Enumerations
enum class DL : int {
Debug , Info , Warn , Error ,
Num
}
Debug level.
enum class DC : int {
DebugMsg , DebugModeMsg , Game , Main ,
Map , MapGen , MapMem , NPC ,
SDL , Lua , Num
}
Debug class.
enum class DebugOutput { std_err , file }
Functions
void realDebugmsg (const char *filename, const char *line, const char *funcname, const std::string &text)
template<typename ... Args>
void realDebugmsg (const char *const filename, const char *const line, const char *const funcname, const char *const mes, Args &&... args)
std::string game_info::operating_system ()
Return the name of the current operating system.
std::string game_info::operating_system_version ()
Return a detailed version of the operating system; e.g.
std::optional< int > game_info::bitness ()
Return the "bitness" of the game (not necessarily of the operating system); either: 64, 32 or nullopt.
std::string game_info::bitness_string ()
Return the "bitness" string of the game (not necessarily of the operating system); either: 64-bit, 32-bit or Unknown.
std::string game_info::game_version ()
Return the game version, as in the entry screen.
std::string game_info::graphics_version ()
Return the underlying graphics version used by the game; either Tiles or Curses.
std::string game_info::mods_loaded ()
Return a list of the loaded mods, including the mod full name and its id name in brackets, e.g.
std::string game_info::game_report ()
Generate a game report, including the information returned by all of the other functions.
void setupDebug (DebugOutput)
Initializes the debugging system, called exactly once from main()
void deinitDebug ()
Opposite of setupDebug, shuts the debugging system down.
void setDebugLogLevels (const enum_bitset< DL > &mask, bool silent=false)
Set debug levels that should be logged.
void setDebugLogClasses (const enum_bitset< DC > &mask, bool silent=false)
Set debug classes that should be logged.
bool debug_has_error_been_observed ()
void debug_reset_ignored_messages ()
Reset any ignored debug messages.
std::string capture_debugmsg_during (const std::function< void()> &func)
Capturing debug messages during func execution, used to test debugmsg calls in the unit tests.
void replay_buffered_debugmsg_prompts ()
Should be called after catacurses::stdscr is initialized.
std::optional< int > get_os_bitness ()
Retrieves OS bitness (32, 64 or nullopt if detection failed)
DebugLogGuard detail::realDebugLog (DL lev, DC cl, const char *filename, const char *line, const char *funcname)
Macro Definition Documentation
__FUNCTION_NAME__
#define __FUNCTION_NAME__ __func__
Definition at line 67 of file debug.h.
CATA_SRC_DEBUG_H
#define CATA_SRC_DEBUG_H
Definition at line 3 of file debug.h.
constexpr_fatal
#define constexpr_fatal (ret, ...) do { debugmsg(__VA_ARGS__); abort(); } while(false)
Definition at line 99 of file debug.h.
DebugLog
#define DebugLog (lev, cl) *detail::realDebugLog(lev, cl, nullptr, nullptr, nullptr)
DebugLog.
See documentation at the top of the file.
Definition at line 285 of file debug.h.
DebugLogFL
#define DebugLogFL (lev, cl) *detail::realDebugLog(lev, cl, __FILE__, STRING(__LINE__), nullptr)
Like DebugLog, but includes source file name and line number.
Definition at line 290 of file debug.h.
debugmsg
#define debugmsg (...) realDebugmsg(__FILE__, STRING(__LINE__), __FUNCTION_NAME__, __VA_ARGS__)
Debug message of level DL::Error and class DC::DebugMsg, also includes the source file name and line, uses varg style arguments, the first argument must be a printf style format string.
Definition at line 75 of file debug.h.
STRING
#define STRING (x) STRING2(x)
Definition at line 62 of file debug.h.
STRING2
#define STRING2 (x) #x
Definition at line 61 of file debug.h.
Enumeration Type Documentation
DC
enum class DC : int strong
Debug class.
Enumerator
DebugMsg
(internal) Messages from realDebugmsg
DebugModeMsg
(internal) Debug-type messages from message log
Game
Main game class.
Main
Generic messages related to game startup and operation.
Enabled by default.
Map
Related to map and mapbuffer (map.cpp, mapbuffer.cpp)
MapGen
Mapgen (mapgen*.cpp), also overmap.cpp.
MapMem
Related to tile memory (map_memory.cpp)
NPC
npcs*.cpp
SDL
SDL & tiles & anything graphical & sound.
Lua
Output from Lua.
Num
Unused.
Definition at line 169 of file debug.h.
              : int {
    /** (internal) Messages from realDebugmsg */
    DebugMsg,
    /** (internal) Debug-type messages from message log */
    DebugModeMsg,
    /** Main game class */
    Game,
    /**
     * Generic messages related to game startup and operation.
     * Enabled by default.
     */
    Main,
    /** Related to map and mapbuffer (map.cpp, mapbuffer.cpp) */
    Map,
    /** Mapgen (mapgen*.cpp), also overmap.cpp */
    MapGen,
    /** Related to tile memory (map_memory.cpp) */
    MapMem,
    /** npcs*.cpp */
    NPC,
    /** SDL & tiles & anything graphical & sound */
    SDL,
    /** Output from Lua */
    Lua,
    /** Unused */
    Num,
};
DebugOutput
enum class DebugOutput strong
Enumerator
std_err
file
Definition at line 202 of file debug.h.
                       {
    std_err,
    file,
};
DL
enum class DL : int strong
Debug level.
Enumerator
Debug
Debug information (default: disabled).
Info
Information (default: enabled).
Warn
Warning (default: enabled).
Error
Error (default: enabled).
Errors are logged regardless of whether debug class is enabled and have backtrace appended to them.
Num
Unused.
Definition at line 138 of file debug.h.
              : int {
    /**
     * Debug information (default: disabled).
     */
    Debug,
    /**
     * Information (default: enabled).
     */
    Info,
    /**
     * Warning (default: enabled).
     */
    Warn,
    /**
     * Error (default: enabled).
     * Errors are logged regardless of whether debug class is enabled
     * and have backtrace appended to them.
     */
    Error,
    /**
     * Unused
     */
    Num,
};
Function Documentation
capture_debugmsg_during()
std::string capture_debugmsg_during (const std::function< void()> & func)
Capturing debug messages during func execution, used to test debugmsg calls in the unit tests.
Returns
std::string debugmsg
Definition at line 186 of file debug.cpp.
{
    capture_debugmsg capture;
    func();
    return capture.dmsg();
}
References capture_debugmsg::dmsg().
debug_has_error_been_observed()
bool debug_has_error_been_observed ()
Returns
true if any error has been logged in this run.
Definition at line 210 of file debug.cpp.
{
    return error_observed;
}
References error_observed.
Referenced by init::check_mods_for_errors().
debug_reset_ignored_messages()
void debug_reset_ignored_messages ()
Reset any ignored debug messages.
Definition at line 561 of file debug.cpp.
{
    ignored_messages.clear();
}
References anonymous_namespace{debug.cpp}::ignored_messages.
Referenced by debug_menu::debug().
deinitDebug()
void deinitDebug ()
Opposite of setupDebug, shuts the debugging system down.
Definition at line 717 of file debug.cpp.
{
    debugFile().deinit();
}
References debugFile(), and DebugFile::deinit().
Referenced by exit_handler().
get_os_bitness()
std::optional< int > get_os_bitness ()
Retrieves OS bitness (32, 64 or nullopt if detection failed)
Definition at line 1824 of file debug.cpp.
{
#if defined(_WIN32)
    SYSTEM_INFO si;
    GetNativeSystemInfo( &si );
    switch( si.wProcessorArchitecture ) {
        case PROCESSOR_ARCHITECTURE_AMD64:
            return 64;
        case PROCESSOR_ARCHITECTURE_INTEL:
            return 32;
        default:
            // FIXME: other architectures?
            break;
    }
#elif defined(__linux__) && !defined(__ANDROID__)
    std::string output;
    output = shell_exec( "getconf LONG_BIT" );
    if( !output.empty() ) {
        // remove trailing '\n', if any.
        output.erase( std::remove( output.begin(), output.end(), '\n' ),
                      output.end() );
    }
    if( output == "64" ) {
        return 64;
    } else if( output == "32" ) {
        return 32;
    }
#endif
    // FIXME: osx, android
    return std::nullopt;
}
Referenced by main_menu::opening_screen().
realDebugmsg() [1/2]
template<typename ... Args> void realDebugmsg (const char *const filename, const char *const line, const char *const funcname, const char *const mes, Args &&... args) inline
Definition at line 81 of file debug.h.
{
    return realDebugmsg( filename, line, funcname, string_format( mes,
                         std::forward<Args>( args )... ) );
}
References line(), realDebugmsg(), and string_format().
realDebugmsg() [2/2]
void realDebugmsg (const char * filename, const char * line, const char * funcname, const std::string & text)
Definition at line 457 of file debug.cpp.
{
    assert( filename != nullptr );
    assert( line != nullptr );
    assert( funcname != nullptr );
    if( capturing ) {
        captured += text;
    } else {
        if( !rep_folder.test( filename, line, funcname, text ) ) {
            *detail::realDebugLog( DL::Error, DC::DebugMsg, filename, line, funcname ) << text;
            rep_folder.set( filename, line, funcname, text );
        } else {
            rep_folder.increment_count();
        }
    }
    if( test_mode ) {
        return;
    }
    // Show excessive repetition prompt once per excessive set
    bool excess_repetition = rep_folder.repeat_count == repetition_folder::repetition_threshold;
    if( buffering_debugmsgs ) {
        buffered_prompts().push_back( {filename, line, funcname, text, false } );
        if( excess_repetition ) {
            buffered_prompts().push_back( {filename, line, funcname, text, true } );
        }
        return;
    }
    debug_error_prompt( filename, line, funcname, text.c_str(), false );
    if( excess_repetition ) {
        debug_error_prompt( filename, line, funcname, text.c_str(), true );
        // Do not count this prompt when considering repetition folding
        // Might look weird in the log if the repetitions end exactly after this prompt is displayed.
        rep_folder.set_time();
    }
}
References buffered_prompts(), buffering_debugmsgs, captured, capturing, debug_error_prompt(), DebugMsg, Error, repetition_folder::increment_count(), line(), detail::realDebugLog(), rep_folder, repetition_folder::repeat_count, repetition_folder::repetition_threshold, repetition_folder::set(), repetition_folder::set_time(), repetition_folder::test(), and test_mode.
Referenced by realDebugmsg().
replay_buffered_debugmsg_prompts()
void replay_buffered_debugmsg_prompts ()
Should be called after catacurses::stdscr is initialized.
If catacurses::stdscr is available, shows all buffered debugmsg prompts.
Definition at line 353 of file debug.cpp.
{
    if( !buffering_debugmsgs ) {
        return;
    }
    buffering_debugmsgs = false;
    for( const auto &prompt : buffered_prompts() ) {
        debug_error_prompt(
            prompt.filename.c_str(),
            prompt.line.c_str(),
            prompt.funcname.c_str(),
            prompt.text.c_str(),
            prompt.force
        );
    }
    buffered_prompts().clear();
}
References buffered_prompts(), buffering_debugmsgs, debug_error_prompt(), and pickup::prompt.
Referenced by main().
setDebugLogClasses()
void setDebugLogClasses (const enum_bitset< DC > & mask, bool silent = false)
Set debug classes that should be logged.
Definition at line 541 of file debug.cpp.
{
    if( mask == debugClass ) {
        return;
    }
    if( !silent ) {
        DebugLog( DL::Info, DC::Main ) << "Set debug classes to: " << fmt_mask( mask );
    }
    debugClass = mask;
}
References debugClass, DebugLog, fmt_mask(), Info, Main, and silent.
Referenced by options_manager::cache_to_globals(), and setupDebug().
setDebugLogLevels()
void setDebugLogLevels (const enum_bitset< DL > & mask, bool silent = false)
Set debug levels that should be logged.
Definition at line 530 of file debug.cpp.
{
    if( mask == debugLevel ) {
        return;
    }
    if( !silent ) {
        DebugLog( DL::Info, DC::Main ) << "Set debug levels to: " << fmt_mask( mask );
    }
    debugLevel = mask;
}
References debugLevel, DebugLog, fmt_mask(), Info, Main, and silent.
Referenced by options_manager::cache_to_globals(), and setupDebug().
setupDebug()
void setupDebug (DebugOutput output_mode)
Initializes the debugging system, called exactly once from main()
Definition at line 710 of file debug.cpp.
{
    setDebugLogLevels( enum_bitset<DL>().set( DL::Info ).set( DL::Warn ).set( DL::Error ), true );
    setDebugLogClasses( enum_bitset<DC>().set( DC::Main ).set( DC::DebugMsg ), true );
    debugFile().init( output_mode, PATH_INFO::debug() );
}
References PATH_INFO::debug(), debugFile(), DebugMsg, Error, Info, DebugFile::init(), Main, luna::set(), setDebugLogClasses(), setDebugLogLevels(), and Warn.
Referenced by main().