Cataclysm BN: src/explosion.cpp File Reference
explosion.cpp File Reference
#include "explosion.h"
#include "fragment_cloud.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <limits>
#include <map>
#include <memory>
#include <optional>
#include <queue>
#include <random>
#include <set>
#include <utility>
#include <variant>
#include <vector>
#include "animation.h"
#include "avatar.h"
#include "ballistics.h"
#include "bodypart.h"
#include "calendar.h"
#include "cata_utility.h"
#include "color.h"
#include "creature.h"
#include "damage.h"
#include "debug.h"
#include "enums.h"
#include "explosion_queue.h"
#include "field_type.h"
#include "flat_set.h"
#include "game.h"
#include "game_constants.h"
#include "int_id.h"
#include "item.h"
#include "item_factory.h"
#include "itype.h"
#include "json.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "material.h"
#include "math_defines.h"
#include "messages.h"
#include "mongroup.h"
#include "monster.h"
#include "mtype.h"
#include "npc.h"
#include "options.h"
#include "output.h"
#include "player.h"
#include "point.h"
#include "posix_time.h"
#include "projectile.h"
#include "rng.h"
#include "shadowcasting.h"
#include "sounds.h"
#include "string_formatter.h"
#include "translations.h"
#include "trap.h"
#include "type_id.h"
#include "units.h"
#include "ui_manager.h"
#include "vehicle.h"
#include "vpart_position.h"
Classes
class explosion_handler::ExplosionEvent
struct explosion_handler::ExplosionEvent::PropelledEntity
struct explosion_handler::ExplosionEvent::FieldToAdd
class explosion_handler::ExplosionProcess
Namespaces
namespace ExplosionConstants
namespace explosion_handler
Functions
static const std::string flag_BLIND ("BLIND")
static const std::string flag_FLASH_PROTECTION ("FLASH_PROTECTION")
static float obstacle_blast_percentage (float range, float distance)
static float critter_blast_percentage (Creature *c, float range, float distance)
static float item_blast_percentage (float range, float distance)
explosion_data load_explosion_data (const JsonObject &jo)
void explosion_handler::explosion (const tripoint &p, Creature *source, float power, float factor=0.8f, bool fire=false, int legacy_casing_mass=0, float legacy_frag_mass=0.05)
Legacy explosion function.
void explosion_handler::explosion (const tripoint &p, const explosion_data &ex, Creature *source)
static std::map< const Creature *, int > explosion_handler::legacy_shrapnel (const tripoint &src, const projectile &fragment, Creature *source)
static std::map< const Creature *, int > explosion_handler::legacy_blast (const tripoint &p, const float power, const float radius, const bool fire, Creature *source)
void explosion_handler::flashbang (const tripoint &p, bool player_immune, const std::string &exp_name)
Triggers a flashbang explosion at p.
void explosion_handler::shockwave (const tripoint &p, const shockwave_data &sw, const std::string &exp_name, Creature *source)
Shockwave applies knockback with given parameters to all targets within radius of p.
void explosion_handler::scrambler_blast (const tripoint &p)
Triggers a scrambler blast at p.
void explosion_handler::emp_blast (const tripoint &p)
Triggers an EMP blast at p.
void explosion_handler::resonance_cascade (const tripoint &p)
Triggers a resonance cascade at p.
projectile explosion_handler::shrapnel_from_legacy (int power, float blast_radius)
float explosion_handler::blast_radius_from_legacy (int power, float distance_factor)
explosion_queue & explosion_handler::get_explosion_queue ()
float shrapnel_calc (const float &intensity, const float &last_obstacle, const int &)
bool shrapnel_check (const float &obstacle, const float &last_intensity)
void update_fragment_cloud (float &output, const float &new_intensity, quadrant)
float accumulate_fragment_cloud (const float &cumulative_obstacle, const float &current_obstacle, const int &)
Variables
static const ammo_effect_str_id ammo_effect_NULL_SOURCE ("NULL_SOURCE")
static const efftype_id effect_blind ("blind")
static const efftype_id effect_deaf ("deaf")
static const efftype_id effect_emp ("emp")
static const efftype_id effect_stunned ("stunned")
static const efftype_id effect_teleglow ("teleglow")
static const species_id ROBOT ("ROBOT")
static const trait_id trait_LEG_TENT_BRACE ("LEG_TENT_BRACE")
static const trait_id trait_PER_SLIME ("PER_SLIME")
static const trait_id trait_PER_SLIME_OK ("PER_SLIME_OK")
static const mongroup_id GROUP_NETHER ("GROUP_NETHER")
static const bionic_id bio_ears ("bio_ears")
static const bionic_id bio_sunglasses ("bio_sunglasses")
static const itype_id itype_battery ("battery")
static const itype_id itype_e_handcuffs ("e_handcuffs")
static const itype_id itype_rm13_armor_on ("rm13_armor_on")
constexpr int ExplosionConstants::Z_LEVEL_DIST = 4
constexpr float ExplosionConstants::SHRAPNEL_OBSTACLE_REDUCTION = 0.25
constexpr int ExplosionConstants::MULTIBASH_COUNT = 5
constexpr float ExplosionConstants::VEHICLE_DAMAGE_MULT = 2.0
constexpr float ExplosionConstants::BASH_RANDOM_FACTOR = 0.3
constexpr int ExplosionConstants::EXPLOSION_CALIBRATION_POWER = 100
constexpr int ExplosionConstants::MOB_FLING_FACTOR = 40750
constexpr int ExplosionConstants::ITEM_FLING_FACTOR = 1500
constexpr float ExplosionConstants::ITEM_FLING_RANDOM_FACTOR = 2.5
constexpr float ExplosionConstants::RESTITUTION_COEFF = 0.3
constexpr float ExplosionConstants::FLING_THRESHOLD = 30.0
constexpr float ExplosionConstants::FLING_MAX_RANGE = 50.0
constexpr float ExplosionConstants::FLING_SLOWDOWN = 5.0
Function Documentation
accumulate_fragment_cloud()
float accumulate_fragment_cloud (const float & cumulative_obstacle, const float & current_obstacle, const int & distance)
Definition at line 1968 of file explosion.cpp.
{
    return std::max( cumulative_obstacle, current_obstacle ) + 1;
}
Referenced by explosion_handler::legacy_shrapnel().
critter_blast_percentage()
static float critter_blast_percentage (Creature * c, float range, float distance) static
Definition at line 99 of file explosion.cpp.
{
    const float radius_reduction = distance > range ? 0.0f : distance > range / 2 ? 0.5f : 1.0f;
    switch( c->get_size() ) {
        case( m_size::MS_TINY ):
            return 0.5 * radius_reduction;
        case( m_size::MS_SMALL ):
            return 0.8 * radius_reduction;
        case( m_size::MS_MEDIUM ):
            return 1.0 * radius_reduction;
        case( m_size::MS_LARGE ):
            return 1.5 * radius_reduction;
        case( m_size::MS_HUGE ):
            return 2.0 * radius_reduction;
        default:
            return 1.0 * radius_reduction;
    }
}
References c, MS_HUGE, MS_LARGE, MS_MEDIUM, MS_SMALL, MS_TINY, and range.
Referenced by explosion_handler::ExplosionProcess::blast_tile().
flag_BLIND()
static const std::string flag_BLIND ("BLIND") static
Referenced by explosion_handler::explosion_funcs::flashbang().
flag_FLASH_PROTECTION()
static const std::string flag_FLASH_PROTECTION ("FLASH_PROTECTION") static
Referenced by explosion_handler::explosion_funcs::flashbang().
item_blast_percentage()
static float item_blast_percentage (float range, float distance) static
Definition at line 119 of file explosion.cpp.
{
    const float radius_reduction = 1.0f - distance / range;
    return radius_reduction;
}
References range.
Referenced by explosion_handler::ExplosionProcess::blast_tile().
load_explosion_data()
explosion_data load_explosion_data (const JsonObject & jo)
Definition at line 125 of file explosion.cpp.
{
    explosion_data ret;
    // First new explosions
    if( jo.has_int( "damage" ) || jo.has_object( "fragment" ) ) {
        jo.read( "damage", ret.damage );
        jo.read( "radius", ret.radius );
        jo.read( "fragment", ret.fragment );
    } else {
        // Legacy
        float power = jo.get_float( "power" );
        ret.damage = power * explosion_handler::power_to_dmg_mult;
        // Don't reuse old formula, it gave way too big blasts
        float distance_factor = jo.get_float( "distance_factor", 0.8f );
        ret.radius = explosion_handler::blast_radius_from_legacy( power, distance_factor );
        if( jo.has_int( "shrapnel" ) ) {
            ret.fragment = explosion_handler::shrapnel_from_legacy( power, ret.radius );
            // Outdated, unused
            jo.get_int( "shrapnel" );
        } else if( jo.has_object( "shrapnel" ) ) {
            ret.fragment = explosion_handler::shrapnel_from_legacy( power, ret.radius );
            auto shr = jo.get_object( "shrapnel" );
            // Legacy bad design - we don't migrate those
            shr.get_int( "casing_mass" );
            shr.get_float( "fragment_mass", 0.15 );
            shr.get_int( "recovery", 0 );
            shr.get_string( "drop", "" );
        }
    }
    ret.fire = jo.get_bool( "fire", false );
    return ret;
}
References explosion_handler::blast_radius_from_legacy(), JsonObject::get_bool(), JsonObject::get_float(), JsonObject::get_int(), JsonObject::get_object(), JsonObject::has_int(), JsonObject::has_object(), explosion_handler::power_to_dmg_mult, JsonObject::read(), cata::hash64_detail::ret, and explosion_handler::shrapnel_from_legacy().
Referenced by ammo_effect::load(), explosion_iuse::load(), and Item_factory::load_basic_info().
obstacle_blast_percentage()
static float obstacle_blast_percentage (float range, float distance) static
Definition at line 95 of file explosion.cpp.
{
    return distance > range ? 0.0f : distance > range / 2 ? 0.5f : 1.0f;
}
References range.
Referenced by explosion_handler::ExplosionProcess::blast_tile(), and explosion_handler::legacy_blast().
shrapnel_calc()
float shrapnel_calc (const float & intensity, const float & last_obstacle, const int & distance)
Definition at line 1953 of file explosion.cpp.
{
    return intensity - last_obstacle;
}
Referenced by explosion_handler::legacy_shrapnel().
shrapnel_check()
bool shrapnel_check (const float & obstacle, const float & last_intensity)
Definition at line 1958 of file explosion.cpp.
{
    return last_intensity - obstacle > 0.0f;
}
Referenced by explosion_handler::legacy_shrapnel().
update_fragment_cloud()
void update_fragment_cloud (float & output, const float & new_intensity, quadrant)
Definition at line 1963 of file explosion.cpp.
{
    output = std::max( output, new_intensity );
}
Referenced by explosion_handler::legacy_shrapnel().
Variable Documentation
ammo_effect_NULL_SOURCE
const ammo_effect_str_id ammo_effect_NULL_SOURCE("NULL_SOURCE") ("NULL_SOURCE") static
Referenced by explosion_handler::legacy_shrapnel(), and explosion_handler::ExplosionProcess::project_shrapnel().
bio_ears
const bionic_id bio_ears("bio_ears") ("bio_ears") static
Referenced by explosion_handler::explosion_funcs::flashbang().
bio_sunglasses
const bionic_id bio_sunglasses("bio_sunglasses") ("bio_sunglasses") static
Referenced by explosion_handler::explosion_funcs::flashbang().
effect_blind
const efftype_id effect_blind("blind") ("blind") static
Referenced by explosion_handler::explosion_funcs::flashbang().
effect_deaf
const efftype_id effect_deaf("deaf") ("deaf") static
Referenced by explosion_handler::explosion_funcs::flashbang().
effect_emp
const efftype_id effect_emp("emp") ("emp") static
Referenced by explosion_handler::emp_blast().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by explosion_handler::explosion_funcs::flashbang().
effect_teleglow
const efftype_id effect_teleglow("teleglow") ("teleglow") static
Referenced by explosion_handler::explosion_funcs::resonance_cascade().
GROUP_NETHER
const mongroup_id GROUP_NETHER("GROUP_NETHER") ("GROUP_NETHER") static
Referenced by explosion_handler::explosion_funcs::resonance_cascade().
itype_battery
const itype_id itype_battery("battery") ("battery") static
Referenced by explosion_handler::emp_blast().
itype_e_handcuffs
const itype_id itype_e_handcuffs("e_handcuffs") ("e_handcuffs") static
Referenced by explosion_handler::emp_blast().
itype_rm13_armor_on
const itype_id itype_rm13_armor_on("rm13_armor_on") ("rm13_armor_on") static
Referenced by explosion_handler::explosion_funcs::flashbang().
ROBOT
const species_id ROBOT("ROBOT") ("ROBOT") static
Referenced by explosion_handler::explosion_funcs::flashbang().
trait_LEG_TENT_BRACE
const trait_id trait_LEG_TENT_BRACE("LEG_TENT_BRACE") ("LEG_TENT_BRACE") static
Referenced by explosion_handler::explosion_funcs::shockwave().
trait_PER_SLIME
const trait_id trait_PER_SLIME("PER_SLIME") ("PER_SLIME") static
Referenced by explosion_handler::explosion_funcs::flashbang().
trait_PER_SLIME_OK
const trait_id trait_PER_SLIME_OK("PER_SLIME_OK") ("PER_SLIME_OK") static
Referenced by explosion_handler::explosion_funcs::flashbang().