Cataclysm BN: src/init.cpp File Reference
init.cpp File Reference
#include "init.h"
#include <cassert>
#include <cstddef>
#include <exception>
#include <fstream>
#include <iterator>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
#include "achievement.h"
#include "activity_type.h"
#include "ammo.h"
#include "ammo_effect.h"
#include "anatomy.h"
#include "ascii_art.h"
#include "artifact.h"
#include "behavior.h"
#include "bionics.h"
#include "bodypart.h"
#include "catalua.h"
#include "cata_utility.h"
#include "clothing_mod.h"
#include "clzones.h"
#include "construction.h"
#include "construction_category.h"
#include "construction_group.h"
#include "construction_sequence.h"
#include "crafting_gui.h"
#include "creature.h"
#include "cursesdef.h"
#include "debug.h"
#include "dependency_tree.h"
#include "dialogue.h"
#include "disease.h"
#include "effect.h"
#include "emit.h"
#include "event_statistics.h"
#include "faction.h"
#include "fault.h"
#include "field_type.h"
#include "filesystem.h"
#include "fstream_utils.h"
#include "flag.h"
#include "gates.h"
#include "harvest.h"
#include "item_action.h"
#include "item_category.h"
#include "item_factory.h"
#include "json.h"
#include "language.h"
#include "loading_ui.h"
#include "lru_cache.h"
#include "magic.h"
#include "magic_enchantment.h"
#include "magic_ter_furn_transform.h"
#include "map_extras.h"
#include "mapbuffer.h"
#include "mapdata.h"
#include "mapgen.h"
#include "martialarts.h"
#include "material.h"
#include "mission.h"
#include "mod_manager.h"
#include "monfaction.h"
#include "mongroup.h"
#include "monstergenerator.h"
#include "morale_types.h"
#include "mutation_data.h"
#include "mutation.h"
#include "npc.h"
#include "npc_class.h"
#include "omdata.h"
#include "overlay_ordering.h"
#include "overmap.h"
#include "overmapbuffer.h"
#include "overmap_connection.h"
#include "overmap_location.h"
#include "overmap_special.h"
#include "profession.h"
#include "recipe_dictionary.h"
#include "recipe_groups.h"
#include "regional_settings.h"
#include "requirements.h"
#include "rotatable_symbols.h"
#include "scenario.h"
#include "scent_map.h"
#include "sdltiles.h"
#include "skill.h"
#include "skill_boost.h"
#include "sounds.h"
#include "speech.h"
#include "start_location.h"
#include "string_formatter.h"
#include "text_snippets.h"
#include "translations.h"
#include "trap.h"
#include "type_id.h"
#include "veh_type.h"
#include "vehicle_group.h"
#include "vitamin.h"
#include "weather.h"
#include "weather_type.h"
#include "worldfactory.h"
Classes
struct DynamicDataLoader::cached_streams
Functions
static void load_ignored_type (const JsonObject &jo)
static void load_and_finalize_packs (loading_ui &ui, const std::string &msg, const std::vector< mod_id > &packs)
Load & finalize specified content packs.
static void clear_loaded_data ()
Function Documentation
clear_loaded_data()
static void clear_loaded_data () static
Definition at line 917 of file init.cpp.
{
    return DynamicDataLoader::get_instance().unload_data();
}
References DynamicDataLoader::get_instance(), and DynamicDataLoader::unload_data().
Referenced by init::check_mods_for_errors(), init::load_core_bn_modfiles(), and init::load_world_modfiles().
load_and_finalize_packs()
static void load_and_finalize_packs (loading_ui & ui, const std::string & msg, const std::vector< mod_id > & packs) static
Load & finalize specified content packs.
Parameters
ui structure for load progress display
msg string to display whilst loading prompt
packs content packs to load in correct dependent order
Definition at line 826 of file init.cpp.
{
    ui.new_context( msg );
    std::vector<mod_id> missing;
    std::vector<mod_id> available;
    for( const mod_id &e : packs ) {
        if( e.is_valid() ) {
            available.emplace_back( e );
            ui.add_entry( e->name() );
        } else {
            missing.push_back( e );
        }
    }
    for( const mod_id &e : missing ) {
        debugmsg( "unknown content pack [%s]", e );
    }
    DynamicDataLoader &loader = DynamicDataLoader::get_instance();
    loader.lua = cata::make_wrapped_state();
    cata::init_global_state_tables( *loader.lua, available );
    ui.show();
    for( const mod_id &mod : available ) {
        if( mod->lua_api_version ) {
            if( !cata::has_lua() ) {
                throw std::runtime_error(
                    string_format(
                        "You need game build with Lua support to load content pack %s [%s]",
                        mod->name(), mod
                    )
                );
            }
            if( cata::get_lua_api_version() != *mod->lua_api_version ) {
                // The mod may be broken, but let's be user-friendly and try to load it anyway
                debugmsg(
                    "Content pack uses outdated Lua API (current: %d, uses: %d) %s [%s]",
                    cata::get_lua_api_version(), *mod->lua_api_version,
                    mod->name(), mod
                );
            }
            cata::set_mod_being_loaded( *loader.lua, mod );
            cata::run_mod_preload_script( *loader.lua, mod );
        }
    }
    cata::reg_lua_iuse_actors( *loader.lua, *item_controller );
    for( const mod_id &mod : available ) {
        loader.load_data_from_path( mod->path, mod.str(), ui );
        ui.proceed();
    }
    loader.finalize_loaded_data( ui );
    if( cata::has_lua() ) {
        for( const mod_id &mod : available ) {
            if( mod->lua_api_version ) {
                cata::set_mod_being_loaded( *loader.lua, mod );
                cata::run_mod_finalize_script( *loader.lua, mod );
            }
        }
    }
    loader.check_consistency( ui );
    if( cata::has_lua() ) {
        init::load_main_lua_scripts( *loader.lua, packs );
        cata::clear_mod_being_loaded( *loader.lua );
    }
}
References available, DynamicDataLoader::check_consistency(), cata::clear_mod_being_loaded(), debugmsg, DynamicDataLoader::finalize_loaded_data(), DynamicDataLoader::get_instance(), cata::get_lua_api_version(), cata::has_lua(), cata::init_global_state_tables(), item_controller, DynamicDataLoader::load_data_from_path(), init::load_main_lua_scripts(), DynamicDataLoader::lua, cata::make_wrapped_state(), cata::reg_lua_iuse_actors(), cata::run_mod_finalize_script(), cata::run_mod_preload_script(), cata::set_mod_being_loaded(), and string_format().
Referenced by init::check_mods_for_errors(), and init::load_core_bn_modfiles().
load_ignored_type()
static void load_ignored_type (const JsonObject & jo) static
Definition at line 202 of file init.cpp.
{
    // This does nothing!
    // This function is used for types that are to be ignored
    // (for example for testing or for unimplemented types)
    jo.allow_omitted_members();
}
References JsonObject::allow_omitted_members().
Referenced by DynamicDataLoader::initialize().