Cataclysm BN: src/json.cpp File Reference
json.cpp File Reference
#include "json.h"
#include <algorithm>
#include <bitset>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <exception>
#include <iterator>
#include <limits>
#include <locale>
#include <set>
#include <sstream>
#include <string>
#include <utility>
#include <vector>
#include "cached_options.h"
#include "cata_utility.h"
#include "debug.h"
#include "string_formatter.h"
#include "string_utils.h"
Functions
static bool is_whitespace (char ch)
static std::string utf16_to_utf8 (uint32_t ch)
void add_array_to_set (std::set< std::string > &s, const JsonObject &json, const std::string &name)
Get an array member from json with name name.
static bool get_escaped_or_unicode (std::istream &stream, std::string &s, std::string &err)
constexpr static uint64_t neg_INT_MIN ()
constexpr static uint64_t neg_INT64_MIN ()
static std::string normalize_relative_path (const std::string &path)
Get the normal form of a relative path.
static std::string escape_property (std::string str)
Escape special chars in github action command properties.
static std::string escape_data (std::string str)
Escape special chars in github action command messages.
std::ostream & operator<< (std::ostream &stream, const JsonError &err)
Function Documentation
add_array_to_set()
void add_array_to_set (std::set< std::string > & s, const JsonObject & json, const std::string & name)
Get an array member from json with name name.
For each element of that array (which should be a string) add it to the given set.
Definition at line 789 of file json.cpp.
{
    for( const std::string line : json.get_array( name ) ) {
        s.insert( line );
    }
}
References JsonObject::get_array(), line(), and om_direction::name().
Referenced by MonsterGroupManager::LoadMonsterBlacklist(), and MonsterGroupManager::LoadMonsterWhitelist().
escape_data()
static std::string escape_data (std::string str) static
Escape special chars in github action command messages.
See https://github.com/actions/toolkit/blob/main/packages/core/src/command.ts
Definition at line 1777 of file json.cpp.
{
    switch( error_log_format ) {
        case error_log_format_t::human_readable:
            break;
        case error_log_format_t::github_action:
            replace_all( str, "%", "%25" );
            // NOLINTNEXTLINE(cata-text-style)
            replace_all( str, "\r", "%0D" );
            replace_all( str, "\n", "%0A" );
            break;
    }
    return str;
}
References error_log_format, github_action, human_readable, and replace_all().
Referenced by JsonIn::error().
escape_property()
static std::string escape_property (std::string str) static
Escape special chars in github action command properties.
See https://github.com/actions/toolkit/blob/main/packages/core/src/command.ts
Definition at line 1756 of file json.cpp.
{
    switch( error_log_format ) {
        case error_log_format_t::human_readable:
            break;
        case error_log_format_t::github_action:
            replace_all( str, "%", "%25" );
            // NOLINTNEXTLINE(cata-text-style)
            replace_all( str, "\r", "%0D" );
            replace_all( str, "\n", "%0A" );
            replace_all( str, ":", "%3A" );
            replace_all( str, ",", "%2C" );
            break;
    }
    return str;
}
References error_log_format, github_action, human_readable, and replace_all().
Referenced by JsonIn::line_number().
get_escaped_or_unicode()
static bool get_escaped_or_unicode (std::istream & stream, std::string & s, std::string & err) static
Definition at line 1030 of file json.cpp.
{
    if( !stream.good() ) {
        err = "stream not good";
        return false;
    }
    char ch;
    stream.get( ch );
    if( !stream.good() ) {
        err = "read operation failed";
        return false;
    }
    if( ch == '\\' ) {
        // converting \", \\, \/, \b, \f, \n, \r, \t and \uxxxx according to JSON spec.
        stream.get( ch );
        if( !stream.good() ) {
            err = "read operation failed";
            return false;
        }
        switch( ch ) {
            case '\\':
                s += '\\';
                break;
            case '"':
                s += '"';
                break;
            case '/':
                s += '/';
                break;
            case 'b':
                s += '\b';
                break;
            case 'f':
                s += '\f';
                break;
            case 'n':
                s += '\n';
                break;
            case 'r':
                s += '\r';
                break;
            case 't':
                s += '\t';
                break;
            case 'u': {
                    uint32_t u = 0;
                    for( int i = 0; i < 4; ++i ) {
                        stream.get( ch );
                        if( !stream.good() ) {
                            err = "read operation failed";
                            return false;
                        }
                        if( ch >= '0' && ch <= '9' ) {
                            u = ( u << 4 ) | ( ch - '0' );
                        } else if( ch >= 'a' && ch <= 'f' ) {
                            u = ( u << 4 ) | ( ch - 'a' + 10 );
                        } else if( ch >= 'A' && ch <= 'F' ) {
                            u = ( u << 4 ) | ( ch - 'A' + 10 );
                        } else {
                            err = "expected hex digit";
                            return false;
                        }
                    }
                    try {
                        s += utf16_to_utf8( u );
                    } catch( const std::exception &e ) {
                        err = e.what();
                        return false;
                    }
                }
                break;
            default:
                err = "invalid escape sequence";
                return false;
        }
    } else if( ch == '\r' || ch == '\n' ) {
        err = "reached end of line without closing string";
        return false;
    } else if( ch == '"' ) {
        // the caller is supposed to handle the ending quote
        err = "unexpected ending quote";
        return false;
    } else if( static_cast<unsigned char>( ch ) < 0x20 ) {
        err = "invalid character inside string";
        return false;
    } else {
        unsigned char uc = static_cast<unsigned char>( ch );
        uint32_t unicode = 0;
        int n = 0;
        if( uc >= 0xFC ) {
            unicode = uc & 0x01;
            n = 5;
        } else if( uc >= 0xF8 ) {
            unicode = uc & 0x03;
            n = 4;
        } else if( uc >= 0xF0 ) {
            unicode = uc & 0x07;
            n = 3;
        } else if( uc >= 0xE0 ) {
            unicode = uc & 0x0f;
            n = 2;
        } else if( uc >= 0xC0 ) {
            unicode = uc & 0x1f;
            n = 1;
        } else if( uc >= 0x80 ) {
            err = "invalid utf8 sequence";
            return false;
        } else {
            unicode = uc;
            n = 0;
        }
        s += ch;
        for( ; n > 0; --n ) {
            stream.get( ch );
            if( !stream.good() ) {
                err = "read operation failed";
                return false;
            }
            uc = static_cast<unsigned char>( ch );
            if( uc < 0x80 || uc >= 0xC0 ) {
                err = "invalid utf8 sequence";
                return false;
            }
            unicode = ( unicode << 6 ) | ( uc & 0x3f );
            s += ch;
        }
        if( unicode > 0x10FFFF ) {
            err = "invalid unicode codepoint";
            return false;
        }
    }
    return true;
}
References utf16_to_utf8().
Referenced by JsonIn::get_string(), and JsonIn::string_error().
is_whitespace()
static bool is_whitespace (char ch) static
Definition at line 29 of file json.cpp.
{
    // These are all the valid whitespace characters allowed by RFC 4627.
    return ( ch == ' ' || ch == '\n' || ch == '\t' || ch == '\r' );
}
Referenced by JsonIn::eat_whitespace(), JsonIn::error(), and JsonIn::uneat_whitespace().
neg_INT64_MIN()
constexpr static uint64_t neg_INT64_MIN () static constexpr
Definition at line 1226 of file json.cpp.
{
    constexpr int64_t x = std::numeric_limits<int64_t>::min() + std::numeric_limits<int64_t>::max();
    static_assert( x >= 0 || x + std::numeric_limits<int64_t>::max() >= 0,
                   "neg_INT64_MIN assumed INT64_MIN + INT64_MAX >= -INT64_MAX" );
    if( x < 0 ) {
        return static_cast<uint64_t>( std::numeric_limits<int64_t>::max() ) + static_cast<uint64_t>( -x );
    } else {
        return static_cast<uint64_t>( std::numeric_limits<int64_t>::max() ) - static_cast<uint64_t>( x );
    }
}
Referenced by JsonIn::get_int64().
neg_INT_MIN()
constexpr static uint64_t neg_INT_MIN () static constexpr
Definition at line 1213 of file json.cpp.
{
    static_assert( sizeof( int ) <= sizeof( int64_t ),
                   "neg_INT_MIN() assumed sizeof( int ) <= sizeof( int64_t )" );
    constexpr int x = std::numeric_limits<int>::min() + std::numeric_limits<int>::max();
    static_assert( x >= 0 || x + std::numeric_limits<int>::max() >= 0,
                   "neg_INT_MIN assumed INT_MIN + INT_MAX >= -INT_MAX" );
    if( x < 0 ) {
        return static_cast<uint64_t>( std::numeric_limits<int>::max() ) + static_cast<uint64_t>( -x );
    } else {
        return static_cast<uint64_t>( std::numeric_limits<int>::max() ) - static_cast<uint64_t>( x );
    }
}
Referenced by JsonIn::get_int().
normalize_relative_path()
static std::string normalize_relative_path (const std::string & path) static
Get the normal form of a relative path.
Does not work on absolute paths. Slash and backslash are both treated as path separators and replaced with slash. Trailing slashes are always removed. TODO: figure out how to use std::filesystem on android ndk
Definition at line 1711 of file json.cpp.
{
    if( path.empty() ) {
        // normal form of an empty path is an empty path
        return path;
    }
    std::vector<std::string> names;
    for( size_t name_start = 0; name_start < path.size(); ) {
        const size_t name_end = std::min( path.find_first_of( "\\/", name_start ),
                                          path.size() );
        if( name_start < name_end ) {
            const std::string name = path.substr( name_start, name_end - name_start );
            if( name == "." ) {
                // do nothing
            } else if( name == ".." ) {
                if( names.empty() || names.back() == ".." ) {
                    names.emplace_back( name );
                } else {
                    names.pop_back();
                }
            } else {
                names.emplace_back( name );
            }
        }
        name_start = std::min( path.find_first_not_of( "\\/", name_end ),
                               path.size() );
    }
    if( names.empty() ) {
        return ".";
    } else {
        std::string normpath;
        for( auto it = names.begin(); it != names.end(); ++it ) {
            if( it != names.begin() ) {
                normpath += "/";
            }
            normpath += *it;
        }
        return normpath;
    }
}
References om_direction::name(), and Name::names.
Referenced by JsonIn::line_number().
operator<<()
std::ostream & operator<< (std::ostream & stream, const JsonError & err)
Definition at line 2252 of file json.cpp.
{
    return stream << err.what();
}
utf16_to_utf8()
static std::string utf16_to_utf8 (uint32_t ch) static
Definition at line 36 of file json.cpp.
{
    char out[5];
    char *buf = out;
    static const unsigned char utf8FirstByte[7] = { 0x00, 0x00, 0xC0, 0xE0, 0xF0, 0xF8, 0xFC };
    int utf8Bytes;
    if( ch < 0x80 ) {
        utf8Bytes = 1;
    } else if( ch < 0x800 ) {
        utf8Bytes = 2;
    } else if( ch < 0x10000 ) {
        utf8Bytes = 3;
    } else if( ch <= 0x10FFFF ) {
        utf8Bytes = 4;
    } else {
        std::stringstream err;
        err << "unknown unicode: " << ch;
        throw std::runtime_error( err.str() );
    }
    buf += utf8Bytes;
    switch( utf8Bytes ) {
        case 4:
            *--buf = ( ch | 0x80 ) & 0xBF;
            ch >>= 6;
        /* fallthrough */
        case 3:
            *--buf = ( ch | 0x80 ) & 0xBF;
            ch >>= 6;
        /* fallthrough */
        case 2:
            *--buf = ( ch | 0x80 ) & 0xBF;
            ch >>= 6;
        /* fallthrough */
        case 1:
            *--buf = ch | utf8FirstByte[utf8Bytes];
    }
    out[utf8Bytes] = '\0';
    return out;
}
Referenced by get_escaped_or_unicode().