Cataclysm BN: src/messages.cpp File Reference
messages.cpp File Reference
#include "messages.h"
#include "calendar.h"
#include "catacharset.h"
#include "color.h"
#include "cursesdef.h"
#include "debug.h"
#include "enums.h"
#include "game.h"
#include "ime.h"
#include "input.h"
#include "json.h"
#include "output.h"
#include "point.h"
#include "string_formatter.h"
#include "string_input_popup.h"
#include "string_utils.h"
#include "translations.h"
#include "ui_manager.h"
#include "uistate.h"
#include "options.h"
#include <algorithm>
#include <deque>
#include <iterator>
#include <memory>
Classes
struct anonymous_namespace{messages.cpp}::game_message
class anonymous_namespace{messages.cpp}::messages_impl
class Messages::dialog
Namespaces
namespace anonymous_namespace{messages.cpp}
namespace Messages
Functions
bool anonymous_namespace{messages.cpp}::message_exceeds_ttl (const game_message &message)
static const std::vector< std::pair< game_message_type, const char * > > & msg_type_and_names ()
static bool msg_type_from_name (game_message_type &type, const std::string &name)
void add_msg (std::string msg)
void add_msg (const game_message_params &params, std::string msg)
Variables
messages_impl anonymous_namespace{messages.cpp}::player_messages
Function Documentation
add_msg() [1/2]
void add_msg (const game_message_params & params, std::string msg)
Definition at line 915 of file messages.cpp.
{
    Messages::add_msg( params, std::move( msg ) );
}
References Messages::add_msg(), and avatar_action::move().
add_msg() [2/2]
void add_msg (std::string msg)
Definition at line 910 of file messages.cpp.
{
    Messages::add_msg( std::move( msg ) );
}
References Messages::add_msg(), and avatar_action::move().
Referenced by basecamp::abandon_camp(), monster::absorb_hit(), mattack::absorb_meat(), weather_effect::acid(), mdeath::acid(), mattack::acid(), mdefense::acidsplash(), vehicle::act_on_map(), act_vehicle_siphon(), act_vehicle_unload_fuel(), computer_session::action_miss_disarm(), advanced_inventory::action_move_item(), computer_session::action_srcf_seal(), Character::activate_bionic(), activity_on_turn_move_loot(), timed_event::actualize(), Character::add_addiction(), monexamine::add_armor(), game::add_artifact_dreams(), game::add_artifact_messages(), Creature::add_effect(), monexamine::add_leash(), add_msg(), monster::add_msg_if_npc(), npc::add_msg_if_npc(), monster::add_msg_player_or_npc(), npc::add_msg_player_or_npc(), avatar_funcs::add_or_drop_with_msg(), iexamine::aggie_plant(), mdeath::amigara(), mattack::antqueen(), grid_furn_transform_queue::apply(), iexamine::arcfurnace_empty(), iexamine::arcfurnace_full(), iuse::artifact(), talk_function::assign_camp(), monexamine::attach_bag_to(), monexamine::attach_or_remove_saddle(), iexamine::autoclave_empty(), iexamine::autoclave_full(), iexamine::autodoc(), vehicle::automatic_fire_turret(), iexamine::bars(), trapfunc::beartrap(), debug_menu::benchmark(), best_installer(), mattack::bio_op_disarm(), mattack::bio_op_impale(), mattack::bio_op_takedown(), Character::bionics_install_failure(), Character::bionics_uninstall_failure(), trapfunc::blade(), blobify(), mdeath::blobsplit(), Character::block_hit(), Character::block_ranged_hit(), trapfunc::board(), mattack::boomer(), mattack::boomer_glow(), mattack::brandish(), vehicle::break_off(), mdeath::broken(), mdeath::broken_ammo(), trapfunc::bubble(), activity_handlers::build_do_turn(), Character::burn_move_stamina(), game::butcher(), activity_handlers::butcher_finish(), talk_function::buy_100_logs(), talk_function::buy_10_logs(), talk_function::buy_haircut(), talk_function::buy_shave(), iuse::cable_attach(), leap_actor::call(), mon_spellcasting_actor::call(), melee_actor::call(), gun_actor::call(), iuse::call_of_tindalos(), trapfunc::caltrops(), trapfunc::caltrops_glass(), player::can_continue_craft(), vehicle::can_enable(), can_fire_turret(), avatar_action::can_fire_weapon(), iuse::can_goo(), cancel_auto_move(), iuse::capture_monster_act(), defense_game::caravan(), iexamine::cardreader(), iexamine::cardreader_foodplace(), iexamine::cardreader_robofac(), cast_spell(), iexamine::chainfence(), npc::character_danger(), debug_menu::character_edit_menu(), game::chat(), Character::check_and_recover_morale(), check_butcher_cbm(), monster::check_mech_powered(), mattack::check_money_left(), npc::check_or_reload_cbm(), Character::check_outbounds_activity(), iexamine::check_power(), game::check_safe_mode_allowed(), mattack::chickenbot(), choose_adjacent(), choose_adjacent_highlight(), choose_direction(), iexamine::choose_fertilizer(), iuse::chop_logs(), iuse::chop_tree(), iuse::clear_rubble(), vehicle::coeff_air_drag(), vehicle::collision(), complete_construction(), complete_craft(), crafting::complete_disassemble(), veh_interact::complete_vehicle(), npc::confident_gun_mode_range(), npc::confident_throw_range(), Character::consume(), Character::consume_effects(), vehicle::consume_fuel(), vehicle::control_engines(), game::control_vehicle(), trapfunc::cot(), Character::cough(), player::craft_skill_gain(), crafting_allowed(), trapfunc::crossbow(), salvage_actor::cut_up(), iexamine::cvdmachine(), damage_targets(), mattack::dance(), mdeath::darkman(), mattack::darkman(), dead_plant(), Character::deal_damage(), debug_menu::debug(), vehicle::decrement_summon_timer(), mission_end::deposit_box(), mattack::dermatik(), mattack::dermatik_growth(), mdeath::detonate(), npc::die(), monster::die_if_drowning(), iuse::dig(), iuse::dig_channel(), iexamine::dimensional_portal(), iuse::directional_antenna(), iexamine::dirtmound(), game::disable_robot(), mdeath::disappear(), map::disarm_trap(), mdeath::disintegrate(), Character::dismount(), map::displace_vehicle(), game::display_scent(), trapfunc::dissector(), anonymous_namespace{iexamine.cpp}::atm_menu::do_deposit_money(), vehicle::do_engine_damage(), npc::do_npc_read(), pickup::do_pickup(), npc::do_player_activity(), avatar::do_read(), npc::do_reload(), veh_interact::do_remove(), veh_interact::do_repair(), vehicle::do_towing_move(), mattack::dogthing(), construct::done_deconstruct(), construct::done_digormine_stair(), construct::done_extract_maybe_revert_to_dirt(), construct::done_grave(), construct::done_mine_upstair(), mattack::doot(), drink_nectar(), Character::drop(), npc::drop_items(), drop_or_embed_projectile(), monexamine::dump_items(), avatar_action::eat(), avatar_action::eat_here(), iexamine::egg_sack_generic(), iuse::ehandcuffs(), explosion_handler::emp_blast(), talk_function::end_conversation(), mattack::evolve_kill_strike(), game::exam_vehicle(), game::examine(), npc::execute_action(), extract_or_wreck_cbms(), computer_session::failure_damage(), construct::failure_deconstruct(), computer_session::failure_manhacks(), computer_session::failure_pump_explode(), computer_session::failure_pump_leak(), computer_session::failure_secubots(), computer_session::failure_shutdown(), construct::failure_standard(), mattack::fear_paralyze(), iexamine::fertilize_plant(), activity_handlers::fertilize_plot_do_turn(), fetch_activity(), talk_function::field_harvest(), activity_handlers::fill_liquid_do_turn(), iuse::fill_pit(), game::find_or_make_stairs(), npc::find_reloadable(), anonymous_namespace{iexamine.cpp}::atm_menu::finish_interaction(), npc::finish_read(), heal_actor::finish_using(), fire(), avatar_action::fire_wielded_weapon(), mdeath::fireball(), mattack::flame(), mattack::flamethrower(), talk_function::flee(), mattack::flesh_golem(), mattack::flesh_tendril(), game::fling_creature(), iexamine::flower_cactus(), iexamine::flower_marloss(), iexamine::flower_poppy(), mdeath::focused_beam(), vehicle::fold_up(), activity_handlers::forage_finish(), game::forced_door_closing(), known_magic::forget_spell(), npc::form_opinion(), mattack::frag(), iexamine::fswitch(), mdeath::fungalburst(), fungal_effects::fungalize(), iuse::fungicide(), mattack::fungus(), iexamine::fungus(), mattack::fungus_big_blossom(), mattack::fungus_bristle(), mattack::fungus_fortify(), mattack::fungus_growth(), mattack::fungus_haze(), mattack::fungus_inject(), mattack::fungus_sprout(), map::furn_set(), iexamine::fvat_empty(), iexamine::fvat_full(), activity_handlers::game_do_turn(), mdeath::gameover(), iexamine::gaspump(), iuse::geiger(), generic_barber(), liquid_handler::get_liquid_target(), get_patient(), get_signal_for_hordes(), give_item_to(), monexamine::give_items_to(), trapfunc::glow(), npc::go_to_omt_destination(), talk_function::goto_location(), grab(), game::grabbed_furn_move(), game::grabbed_move(), game::grabbed_veh_move(), grenade_helper(), vehicle::ground_acceleration(), mdeath::guilt(), npc_ai::gun_value(), activity_handlers::gunmod_add_finish(), iuse::gunmod_attach(), activity_handlers::hand_crank_do_turn(), handbrake(), game::handle_action(), liquid_handler::handle_liquid(), npc::handle_sound(), vehicle::handle_trap(), Character::hardcoded_effects(), iexamine::harvest_plant(), haul(), npc::heal_player(), npc::heal_self(), Character::healing_rate(), map::hit_with_acid(), vehicle::honk_horn(), talk_function::hostile(), activity_handlers::hotwire_finish(), Character::i_add_to_container(), vehicle::idle(), Character::impact(), talk_function::insult_combat(), vehicle::interact_vehicle_locked(), vehicle::interact_with(), inscribe_actor::item_inscription(), iuse::jackhammer(), mdeath::jackson(), mattack::jackson(), vehicle::k_traction(), mattack::kamikaze(), iexamine::keg(), iexamine::kiln_empty(), iexamine::kiln_full(), monster::knock_back_to(), game::knockback(), trapfunc::lava(), character_martial_arts::learn_current_style_CQB(), character_martial_arts::learn_style(), talk_function::leave(), trapfunc::ledge(), iexamine::ledge(), mattack::leech_spawner(), explosion_handler::legacy_blast(), vehicle::lift_thrust_of_rotorcraft(), weather_effect::light_acid(), weather_effect::lightning(), game::list_items(), game::list_items_monsters(), game::list_monsters(), game::load_npcs(), iexamine::locked_object(), iexamine::locked_object_pickable(), npc::long_term_goal_action(), activity_handlers::longsalvage_finish(), game::look_around(), loot(), mattack::lunge(), magic_train(), monster::make_fungus(), activity_handlers::make_zlave_finish(), vehicle::max_ground_velocity(), vehicle::max_water_velocity(), monexamine::mech_hack(), Character::melee_attack(), monster::melee_attack(), npc_ai::melee_value(), mdeath::melt(), avatar_action::mend(), Character::mend(), avatar_funcs::mend_item(), activity_handlers::mend_item_finish(), vehicle::merge_rackable_vehicle(), npc::method_of_attack(), map_funcs::migo_nerve_cage_removal(), iexamine::migo_nerve_cluster(), monexamine::milk_source(), mill_activate(), mill_load_food(), iuse::mind_splicer(), Creature::mod_stat(), game::mon_info_update(), mattack::mon_leech_evolution(), game::monmove(), talk_function::morale_chat(), talk_function::morale_chat_activity(), Character::mount_creature(), monster::move(), npc::move(), avatar_action::move(), advanced_inventory::move_all_items(), monster::move_effects(), monster::move_to(), npc::move_to_next(), map::move_vehicle(), game::moving_vehicle_dismount(), npc::mug_player(), mattack::multi_robot(), iuse::multicooker(), multicooker_hallu(), Character::mutation_attacks(), npc::mutiny(), vehicle::noise_and_smoke(), iexamine::none(), mdeath::normal(), spell_events::notify(), npc::npc_dismount(), game::npc_menu(), npc_throw(), mattack::nurse_assist(), mattack::nurse_check_up(), mattack::nurse_operate(), monster::nursebot_operate(), Character::on_dodge(), Character::on_hit(), monster::on_load(), npc::on_load(), item::on_wear(), open(), map::open_door(), iexamine::open_safe(), main_menu::opening_screen(), activity_handlers::operation_do_turn(), activity_handlers::operation_finish(), game::overmap_npc_move(), spell_effect::pain_split(), vehicle::part_collision(), iexamine::pay_gas(), iexamine::pedestal_temple(), iexamine::pedestal_wyrm(), timed_event::per_turn(), Character::perform_install(), Character::perform_technique(), Character::perform_uninstall(), perform_zone_activity_turn(), game::perhaps_add_random_npc(), game::phasing_move(), iuse::pheromone(), mattack::photograph(), pick_one_up(), pick_part_to_heal(), pickup::pick_up(), npc::pick_up_item(), iuse::pickaxe(), pickveh(), trapfunc::pit(), iexamine::pit(), iexamine::pit_covered(), trapfunc::pit_glass(), trapfunc::pit_spikes(), place_construction(), mission_start::place_dog(), mission_start::place_npc_software(), game::place_player(), overmap::place_specials(), mattack::plant(), map::player_in_field(), pldrive(), avatar_action::plthrow(), iexamine::portable_structure(), vehicle::possibly_recover_from_skid(), iexamine::pour_into_keg(), vehicle::power_parts(), Character::practice(), defense_game::pre_action(), mdeath::preg_roach(), npc::pretend_fire(), npc::pretend_heal(), print_action(), print_damage_info(), ranged::print_dmg_msg(), game::debug_hour_timer::print_time(), game::process_artifact(), item::process_corpse(), monster::process_effects_internal(), map::process_falling(), map::process_fields_in_submap(), sounds::process_sound_markers(), monster::process_turn(), process_vehicle_items(), projectile_attack(), game::prompt_dangerous_tile(), prompt_disassemble_in_seq(), prompt_disassemble_single(), monexamine::push(), monster::push_to(), iexamine::quern_examine(), game::quicksave(), avatar_action::ramp_move(), mattack::ranged_pull(), mdeath::ratking(), mattack::ratking(), npc::reach_omt_destination(), read(), avatar::read(), iexamine::recycle_compactor(), explosion_handler::explosion_funcs::regular(), avatar_action::reload(), activity_handlers::reload_finish(), iexamine::reload_furniture(), avatar_action::reload_item(), avatar_action::reload_wielded(), vehicle::remote_controlled(), iuse::remoteveh(), monexamine::remove_armor(), monexamine::remove_bag_from(), vehicle::remove_carried_vehicle(), Creature::remove_effect(), monexamine::remove_harness(), monexamine::remove_leash(), debug_menu::mission_debug::remove_mission(), talk_function::remove_overseer(), DefaultRemovePartHandler::removed(), requirements_map(), mattack::resurrect(), mission_start::reveal_refugee_center(), reveal_target(), mattack::rifle(), mattack::riotbot(), Character::rooted_message(), map::rotten_item_spawn(), iuse::rpgdie(), iexamine::rubble(), examine_item_menu::run(), inventory::rust_iron_items(), iexamine::safe(), game::save_cyborg(), npc::say(), npc::scan_new_items(), mattack::science(), explosion_handler::scrambler_blast(), Creature::select_body_part(), anatomy::select_body_part(), npc::set_attitude(), effect::set_duration(), vehicle::set_electronics_menu_options(), effect::set_intensity(), set_item_inventory(), avatar::set_movement_mode(), talk_effect_fun_t::set_u_buy_monster(), monster::setpos(), map::shake_vehicle(), monexamine::shear_animal(), mattack::shockstorm(), explosion_handler::explosion_funcs::shockwave(), map::shoot(), gun_actor::shoot(), trapfunc::shotgun(), show_pickup_message(), character_funcs::show_skill_capped_notice(), mattack::shriek_alert(), iexamine::shrub_marloss(), iexamine::shrub_wildveggies(), overmap::signal_hordes(), trapfunc::sinkhole(), skim_book_msg(), mattack::slimespring(), game::slip_down(), iexamine::slot_machine(), vehicle::slowdown(), smash(), map::smash_items(), vehicle::smash_security_system(), smoker_activate(), smoker_load_food(), iexamine::smoker_options(), trapfunc::snare_heavy(), trapfunc::snare_light(), Character::sound_hallu(), spawn_animal(), map::spawn_monsters_submap_group(), spell_effect::spawn_summoned_monster(), defense_game::spawn_wave(), fungal_effects::spread_fungus_one_tile(), mattack::stare(), vehicle::start_engine(), vehicle::start_engines(), activity_handlers::start_engines_finish(), activity_handlers::start_fire_do_turn(), game::start_game(), Character::start_hauling(), monexamine::start_leading(), talk_function::start_mugging(), stash_on_pet(), vehicle::stop_engines(), talk_function::stop_following(), talk_function::stop_guard(), Character::stop_hauling(), monexamine::stop_leading(), talk_function::stranger_neutral(), Character::suffer_from_bad_bionics(), Character::suffer_from_schizophrenia(), monexamine::swap(), avatar_action::swim(), monexamine::take_items_from(), takeoff(), Character::takeoff(), npc::talk_to_u(), mattack::tankgun(), trapfunc::telepad(), teleport::teleport(), debug_menu::teleport_long(), debug_menu::teleport_overmap(), debug_menu::teleport_short(), trapfunc::temple_flood(), trapfunc::temple_toggle(), vehicle::thrust(), weather_effect::thunder(), monexamine::tie_pet(), mattack::tindalos_teleport(), game::debug_hour_timer::toggle(), gates::toggle_gate(), vehicle::toggle_tracking(), iexamine::toilet(), iuse::toolmod_attach(), activity_handlers::train_finish(), iexamine::transform(), teleporter_list::translocate(), iexamine::translocator(), iexamine::trap(), iexamine::tree_maple(), iexamine::tree_maple_tapped(), iexamine::tree_marloss(), mattack::triffid_growth(), mdeath::triffid_heart(), mattack::triffid_heartbeat(), trapfunc::tripwire(), avatar_funcs::try_disarm_npc(), game::try_get_right_click_action(), try_remove_bear_trap(), try_remove_grab(), try_remove_heavysnare(), try_remove_lightsnare(), try_remove_webs(), try_start_hacking(), avatar_funcs::try_steal_from_npc(), gun_actor::try_target(), salvage_actor::try_to_cut_up(), character_funcs::try_uncanny_dodge(), vehicle::turrets_aim_and_fire_all_manual(), vehicle::turrets_aim_and_fire_single(), vehicle::turrets_override_automatic_aim(), Character::uninstall_bionic(), avatar_action::unload(), avatar_funcs::unload_item(), monexamine::untie_pet(), Character::update_bodytemp(), Character::update_health(), npc::update_path(), game::update_stair_monsters(), Character::update_stamina(), vehicle::update_time(), mattack::upgrade(), change_scent_iuse::use(), salvage_actor::use(), enzlave_actor::use(), musical_instrument_actor::use(), deploy_tent_actor::use(), sew_advanced_actor::use(), learn_spell_actor::use(), game::use_computer(), vehicle::use_controls(), vehicle::use_dishwasher(), vehicle::use_harness(), heal_actor::use_healing_item(), avatar_action::use_item(), avatar_funcs::use_item(), npc::use_painkiller(), vehicle::use_washing_machine(), map::vehicle_vehicle_collision(), iexamine::vending(), game::vertical_move(), activity_handlers::vibe_do_turn(), avatar::vomit(), wait(), avatar::wake_up(), game::walk_move(), wash_items(), vehicle::water_acceleration(), npc_ai::weapon_value(), wear(), avatar_action::wield(), avatar::wield(), npc::wield_better_weapon(), npc_ai::wielded_value(), mdeath::worm(), mdefense::zapback(), and mattack::zombie_fuse().
msg_type_and_names()
static const std::vector< std::pair< game_message_type, const char * > > & msg_type_and_names () static
Definition at line 373 of file messages.cpp.
{
    static const std::vector<std::pair<game_message_type, const char *>> type_n_names = {
        { m_good, translate_marker_context( "message type", "good" ) },
        { m_bad, translate_marker_context( "message type", "bad" ) },
        { m_mixed, translate_marker_context( "message type", "mixed" ) },
        { m_warning, translate_marker_context( "message type", "warning" ) },
        { m_info, translate_marker_context( "message type", "info" ) },
        { m_neutral, translate_marker_context( "message type", "neutral" ) },
        { m_debug, translate_marker_context( "message type", "debug" ) },
    };
    return type_n_names;
}
References m_bad, m_debug, m_good, m_info, m_mixed, m_neutral, m_warning, and translate_marker_context.
Referenced by Messages::dialog::filter_help_text(), and msg_type_from_name().
msg_type_from_name()
static bool msg_type_from_name (game_message_type & type, const std::string & name) static
Definition at line 388 of file messages.cpp.
{
    for( const auto &p : msg_type_and_names() ) {
        if( name == pgettext( "message type", p.second ) ) {
            type = p.first;
            return true;
        }
    }
    return false;
}
References msg_type_and_names(), om_direction::name(), and pgettext().
Referenced by Messages::dialog::do_filter().