Cataclysm BN: anonymous_namespace{grab.cpp} Namespace Reference
anonymous_namespace{grab.cpp} Namespace Reference
Functions
auto make_scraping_noise (const tripoint &pos, const int volume) -> void
auto base_str_req (vehicle *veh) -> int
auto offroad_str_req_cap (vehicle *veh) -> int
auto get_grabbed_vehicle_movecost (vehicle *veh) -> int
auto get_effective_wheels (vehicle *veh) -> int
auto get_vehicle_str_requirement (vehicle *veh) -> int
Function Documentation
base_str_req()
auto anonymous_namespace{grab.cpp}::base_str_req (vehicle * veh) -> int
Definition at line 35 of file grab.cpp.
{
    return veh->total_mass() / 100_kilogram;
}
Referenced by get_grabbed_vehicle_movecost(), and get_vehicle_str_requirement().
get_effective_wheels()
auto anonymous_namespace{grab.cpp}::get_effective_wheels (vehicle * veh) -> int
Definition at line 69 of file grab.cpp.
{
    const auto &wheels = veh->wheelcache;
    return ( wheels.size() > 4 || wheels.size() == 1 ) ? 4 : wheels.size();
}
Referenced by get_vehicle_str_requirement().
get_grabbed_vehicle_movecost()
auto anonymous_namespace{grab.cpp}::get_grabbed_vehicle_movecost (vehicle * veh) -> int
Definition at line 47 of file grab.cpp.
{
    const int str_req = base_str_req( veh );
    const auto &map = get_map();
    const tripoint &vehpos = veh->global_pos3();
    static const auto get_wheel_pos = [&]( const int p ) {
        return vehpos + veh->part( p ).precalc[0];
    };
    const auto &wheel_indices = veh->wheelcache;
    return std::accumulate( wheel_indices.begin(), wheel_indices.end(), 0,
    [&]( const int sum, const int p ) {
        const tripoint wheel_pos = get_wheel_pos( p );
        const int mapcost = map.move_cost( wheel_pos, veh );
        const int movecost = str_req / static_cast<int>( wheel_indices.size() ) * mapcost;
        return sum + movecost;
    } );
}
References base_str_req(), and get_map().
Referenced by get_vehicle_str_requirement().
get_vehicle_str_requirement()
auto anonymous_namespace{grab.cpp}::get_vehicle_str_requirement (vehicle * veh) -> int
Definition at line 77 of file grab.cpp.
{
    if( !veh->valid_wheel_config() ) {
        return base_str_req( veh ) * 10;
    }
    //if vehicle is rollable we modify str_req based on a function of movecost per wheel.
    const int all_movecost = get_grabbed_vehicle_movecost( veh );
    // off-road coefficient (always 1.0 on a road, as low as 0.1 off road.)
    const float traction = veh->k_traction(
                               get_map().vehicle_wheel_traction( *veh ) );
    return int { 1 + all_movecost / get_effective_wheels( veh ) } / traction;
}
References base_str_req(), get_effective_wheels(), get_grabbed_vehicle_movecost(), and get_map().
Referenced by game::grabbed_veh_move().
make_scraping_noise()
auto anonymous_namespace{grab.cpp}::make_scraping_noise (const tripoint & pos, const int volume) -> void
Definition at line 28 of file grab.cpp.
{
    sounds::sound( pos, volume, sounds::sound_t::movement,
                   _( "a scraping noise." ), true, "misc", "scraping" );
}
References _, sounds::movement, and sounds::sound().
Referenced by game::grabbed_veh_move().
offroad_str_req_cap()
auto anonymous_namespace{grab.cpp}::offroad_str_req_cap (vehicle * veh) -> int
Definition at line 41 of file grab.cpp.
{
    return veh->total_mass() / 10_kilogram;
}
Referenced by game::grabbed_veh_move().