Cataclysm BN: init Namespace Reference
init Namespace Reference
Functions
void load_main_lua_scripts (cata::lua_state &state, const std::vector< mod_id > &packs)
Load (or reload) mods' main Lua scripts.
bool is_data_loaded ()
Returns whether the game data is currently loaded.
void load_core_bn_modfiles ()
Load & finalize modlist that consists of single vanilla BN core "mod".
void load_world_modfiles (loading_ui &ui, const std::string &artifacts_file)
Load & finalize modlist needed for the current world.
void load_soundpack_files (const std::string &soundpack_path)
Load soundpack.
bool check_mods_for_errors (loading_ui &ui, const std::vector< mod_id > &opts)
Check mods for errors.
Function Documentation
check_mods_for_errors()
bool init::check_mods_for_errors (loading_ui & ui, const std::vector< mod_id > & opts)
Check mods for errors.
Does so by individually loading & finalizing each mod with all its dependencies.
Parameters
ui structure for load progress display
opts check specific mods (or all if empty)
Returns
whether all mods were successfully loaded and had no errors
Definition at line 968 of file init.cpp.
{
    const dependency_tree &tree = world_generator->get_mod_manager().get_tree();
    // Deduplicated list of mods to check
    std::set<mod_id> to_check;
    for( const mod_id &id : opts ) {
        if( !id.is_valid() ) {
            std::cerr << string_format( "Unknown mod: [%s]\n", id );
            return false;
        }
        if( !tree.is_available( id ) ) {
            std::cerr << string_format(
                          "Missing dependencies: %s %s\n",
                          id, tree.get_node( id )->s_errors()
                      );
            return false;
        }
        if( id->lua_api_version && !cata::has_lua() ) {
            std::cerr << string_format( "Mod requires Lua support: [%s]\n", id );
            return false;
        }
        to_check.emplace( id );
    }
    // If no specific mods specified check all non-obsolete mods
    if( to_check.empty() ) {
        for( const mod_id &mod : world_generator->get_mod_manager().all_mods() ) {
            if( !mod->obsolete && !( !cata::has_lua() && mod->lua_api_version ) ) {
                to_check.emplace( mod );
            }
        }
    }
    // If no mods are available then test core data only
    if( to_check.empty() ) {
        to_check.emplace( mod_management::get_default_core_content_pack() );
    }
    for( const mod_id &id : to_check ) {
        clear_loaded_data();
        world_generator->set_active_world( nullptr );
        world_generator->init();
        const std::vector<mod_id> mods_empty;
        WORLDPTR test_world = world_generator->make_new_world( mods_empty );
        if( !test_world ) {
            std::cerr << "Failed to generate test world." << std::endl;
            return false;
        }
        world_generator->set_active_world( test_world );
        std::cout << string_format( "Checking mod %s [%s]\n", id->name(), id );
        // Load all dependencies first
        std::vector<mod_id> mods_list = tree.get_dependencies_of_X_as_strings( id );
        // Load the mod itself
        mods_list.push_back( id );
        try {
            load_and_finalize_packs( ui, _( "Checking mods" ), mods_list );
        } catch( const std::exception &err ) {
            std::cerr << "Error loading data: " << err.what() << std::endl;
        }
        std::string world_name = world_generator->active_world->world_name;
        world_generator->delete_world( world_name, true );
        // TODO: Why would we need these calls?
        MAPBUFFER.clear();
        overmap_buffer.clear();
    }
    return !debug_has_error_been_observed();
}
References _, mapbuffer::clear(), overmapbuffer::clear(), clear_loaded_data(), debug_has_error_been_observed(), mod_management::get_default_core_content_pack(), dependency_tree::get_dependencies_of_X_as_strings(), dependency_tree::get_node(), cata::has_lua(), int_id< T >::id(), dependency_tree::is_available(), int_id< T >::is_valid(), load_and_finalize_packs(), MAPBUFFER, overmap_buffer, dependency_node::s_errors(), string_format(), and world_generator.
Referenced by main().
is_data_loaded()
bool init::is_data_loaded ()
Returns whether the game data is currently loaded.
Definition at line 912 of file init.cpp.
{
    return DynamicDataLoader::get_instance().is_data_finalized();
}
References DynamicDataLoader::get_instance(), and DynamicDataLoader::is_data_finalized().
load_core_bn_modfiles()
void init::load_core_bn_modfiles ()
Load & finalize modlist that consists of single vanilla BN core "mod".
Exceptions
std::exception if the loaded data is not valid.
Definition at line 922 of file init.cpp.
{
    clear_loaded_data();
    loading_ui ui( false );
    load_and_finalize_packs(
        ui, _( "Loading content packs" ),
    { mod_management::get_default_core_content_pack() }
    );
}
References _, clear_loaded_data(), mod_management::get_default_core_content_pack(), and load_and_finalize_packs().
Referenced by game::dump_stats().
load_main_lua_scripts()
void init::load_main_lua_scripts (cata::lua_state & state, const std::vector< mod_id > & packs)
Load (or reload) mods' main Lua scripts.
Definition at line 902 of file init.cpp.
{
    for( const mod_id &mod : packs ) {
        if( mod.is_valid() && mod->lua_api_version ) {
            cata::set_mod_being_loaded( state, mod );
            cata::run_mod_main_script( state, mod );
        }
    }
}
References cata::run_mod_main_script(), and cata::set_mod_being_loaded().
Referenced by load_and_finalize_packs().
load_soundpack_files()
void init::load_soundpack_files (const std::string & soundpack_path)
Load soundpack.
Parameters
soundpack_path path to soundpack directory.
Exceptions
std::exception if the loaded data is not valid.
Definition at line 1047 of file init.cpp.
{
    // Leverage DynamicDataLoader to load a soundpack.
    // It's not a mod, so we avoid the regular mod loading routines.
    // clear_loaded_data() is not needed here, tileset gets loaded on game init before any mods
    loading_ui ui( false );
    DynamicDataLoader::get_instance().load_data_from_path( soundpack_path, "sound_core", ui );
}
References DynamicDataLoader::get_instance(), and DynamicDataLoader::load_data_from_path().
load_world_modfiles()
void init::load_world_modfiles (loading_ui & ui, const std::string & artifacts_file)
Load & finalize modlist needed for the current world.
Parameters
ui structure for load progress display
artifact_file file with per-world artifact definitions
Exceptions
std::exception if the loaded data is not valid.
Definition at line 933 of file init.cpp.
{
    clear_loaded_data();
    mod_management::t_mod_list &mods = world_generator->active_world->active_mod_order;
    // remove any duplicates whilst preserving order (fixes #19385)
    std::set<mod_id> found;
    mods.erase( std::remove_if( mods.begin(), mods.end(), [&found]( const mod_id & e ) {
        if( found.count( e ) ) {
            return true;
        } else {
            found.insert( e );
            return false;
        }
    } ), mods.end() );
    // require at least one core mod (saves before version 6 may implicitly require dda pack)
    if( std::none_of( mods.begin(), mods.end(), []( const mod_id & e ) {
    return e->core;
})) {
        mods.insert( mods.begin(), mod_management::get_default_core_content_pack() );
    }
    // TODO: get rid of artifacts
    load_artifacts( artifacts_file );
    // this code does not care about mod dependencies,
    // it assumes that those dependencies are static and
    // are resolved during the creation of the world.
    // That means world->active_mod_order contains a list
    // of mods in the correct order.
    load_and_finalize_packs( ui, _( "Loading files" ), mods );
}
References clear_loaded_data(), and world_generator.
Referenced by game::setup().