Cataclysm BN: item_funcs Namespace Reference
item_funcs Namespace Reference
Functions
bool can_be_unloaded (const item &itm)
Returns whether given item (or one of its gunmods) can be unloaded.
int shots_remaining (const Character &who, const item &it)
Number of shots left, considers if a gun uses ups, ammo, or both.
Function Documentation
can_be_unloaded()
bool item_funcs::can_be_unloaded (const item & itm)
Returns whether given item (or one of its gunmods) can be unloaded.
Definition at line 15 of file item_functions.cpp.
{
    if( ( itm.is_container() || itm.is_bandolier() || itm.type->can_use( "holster" ) ) &&
        !itm.contents.empty() &&
        itm.can_unload_liquid() ) {
        return true;
    }
    if( itm.has_flag( flag_NO_UNLOAD ) ) {
        return false;
    }
    if( itm.magazine_current() ) {
        return true;
    }
    for( const item *mod : itm.gunmods() ) {
        if( can_be_unloaded( *mod ) ) {
            return true;
        }
    }
    if( itm.ammo_types().empty() ) {
        return false;
    }
    return itm.ammo_remaining() > 0 || itm.casings_count() > 0;
}
References item::ammo_remaining(), item::ammo_types(), can_be_unloaded(), item::can_unload_liquid(), itype::can_use(), item::casings_count(), item::contents, item_contents::empty(), flag_NO_UNLOAD, item::gunmods(), item::has_flag(), item::is_bandolier(), item::is_container(), item::magazine_current(), and item::type.
Referenced by can_be_unloaded(), examine_item_menu::rate_action_unload(), and avatar_action::unload().
shots_remaining()
int item_funcs::shots_remaining (const Character & who, const item & it)
Number of shots left, considers if a gun uses ups, ammo, or both.
Definition at line 45 of file item_functions.cpp.
{
    if( !it.is_gun() ) {
        return 0;
    }
    int ammo_drain = it.ammo_required();
    int energy_drain = it.get_gun_ups_drain();
    int power = who.charges_of( itype_UPS );
    if( ammo_drain > 0 && energy_drain > 0 ) {
        // Both UPS and ammo, lower is limiting.
        return std::min( it.ammo_remaining() / ammo_drain, power / energy_drain );
    } else if( energy_drain > 0 ) {
        //Only one of the two, it is limiting.
        return power / energy_drain;
    } else if( ammo_drain > 0 ) {
        return it.ammo_remaining() / ammo_drain;
    } else {
        // Effectively infinite ammo.
        return item::INFINITE_CHARGES;
    }
}
References item::ammo_remaining(), item::ammo_required(), visitable< T >::charges_of(), item::get_gun_ups_drain(), item::INFINITE_CHARGES, item::is_gun(), and itype_UPS.
Referenced by npc_ai::best_mode_for_range(), and npc::method_of_attack().