Cataclysm BN: cata Namespace Reference
cata Namespace Reference
Namespaces
namespace detail
namespace event_detail
namespace hash64_detail
namespace tuple_hash_detail
Classes
struct auto_hash
struct auto_hash< std::pair< T, U > >
struct auto_hash< std::tuple< T... > >
class clone_ptr
class colony
class event
class flat_set
A SimpleAssociativeContainer implemented as a sorted vector.
struct is_instance_of
struct is_instance_of< TMPL< T >, TMPL >
class list
class lua_log_handler
struct lua_log_msg
struct lua_state
Lua state handle.
struct lua_state_deleter
struct on_every_x_hooks
class poly_serialized
Copyable unique_ptr that writes and reads objects of derived types.
struct range_hash
class string_formatter
Type-safe and undefined-behavior free wrapper over sprintf.
struct transparent_less_than
struct tuple_hash
class value_ptr
This class is essentially a copyable unique pointer.
Typedefs
template<typename T >
using is_numeric = typename std::conditional< std::is_arithmetic< typename std::decay< T >::type >::value &&!std::is_same< typename std::decay< T >::type, bool >::value, std::true_type, std::false_type >::type
template<typename T >
using is_integer = typename std::conditional< is_numeric< T >::value &&!std::is_floating_point< typename std::decay< T >::type >::value, std::true_type, std::false_type >::type
template<typename T >
using is_char = typename std::conditional< std::is_same< typename std::decay< T >::type, char >::value, std::true_type, std::false_type >::type
template<typename T >
using is_string = typename std::conditional< std::is_same< typename std::decay< T >::type, std::string >::value, std::true_type, std::false_type >::type
template<typename T >
using is_string_view = typename std::conditional< std::is_same< typename std::decay< T >::type, std::string_view >::value, std::true_type, std::false_type >::type
template<typename T >
using is_cstring = typename std::conditional< std::is_same< typename std::decay< T >::type, const char * >::value||std::is_same< typename std::decay< T >::type, char * >::value, std::true_type, std::false_type >::type
template<typename T >
using is_translation = typename std::conditional< std::is_same< typename std::decay< T >::type, translation >::value, std::true_type, std::false_type >::type
template<typename T >
using is_string_id = typename std::conditional< is_instance_of< typename std::decay< T >::type, string_id >::value, std::true_type, std::false_type >::type
Enumerations
enum class LuaLogLevel {
Input , Info , Warn , Error ,
DebugMsg
}
Functions
template<typename Iterator , typename RatingFunction >
void sort_by_rating (Iterator begin, Iterator end, RatingFunction rating_func)
Sort elements of a sequence by their rating (the smaller the better).
template<typename T >
void find_cycles_impl (const std::unordered_map< T, std::vector< T > > &edges, const T &v, std::unordered_set< T > &visited, std::unordered_map< T, T > &on_current_branch, std::vector< std::vector< T > > &result)
template<typename T >
std::vector< std::vector< T > > find_cycles (const std::unordered_map< T, std::vector< T > > &edges)
void unreachable ()
Marks unreachable code.
bool has_lua ()
std::string get_lapi_version_string ()
void startup_lua_test ()
bool generate_lua_docs ()
void show_lua_console ()
void reload_lua_code ()
void debug_write_lua_backtrace (std::ostream &)
bool save_world_lua_state (const std::string &)
bool load_world_lua_state (const std::string &)
std::unique_ptr< lua_state, lua_state_deleter > make_wrapped_state ()
void init_global_state_tables (lua_state &, const std::vector< mod_id > &)
void set_mod_being_loaded (lua_state &, const mod_id &)
void clear_mod_being_loaded (lua_state &)
void run_mod_preload_script (lua_state &, const mod_id &)
void run_mod_finalize_script (lua_state &, const mod_id &)
void run_mod_main_script (lua_state &, const mod_id &)
void reg_lua_iuse_actors (lua_state &, Item_factory &)
template<typename... Args>
void run_hooks (Args &&...)
void run_on_every_x_hooks (lua_state &)
int get_lua_api_version ()
void run_on_game_save_hooks (lua_state &state)
void run_on_game_load_hooks (lua_state &state)
void run_on_mapgen_postprocess_hooks (lua_state &state, map &m, const tripoint &p, const time_point &when)
void reg_all_bindings (sol::state &lua)
void show_lua_console_impl ()
lua_log_handler & get_lua_log_instance ()
sol::table make_readonly_table (sol::state_view &lua, sol::table read_from)
sol::table make_readonly_table (sol::state_view &lua, sol::table read_from, const std::string &error_msg)
void serialize_lua_table (sol::table t, JsonOut &jsout)
void deserialize_lua_table (sol::table t, JsonObject &obj)
template<class element_type , class element_allocator_type , typename element_skipfield_type >
void swap (colony< element_type, element_allocator_type, element_skipfield_type > &a, colony< element_type, element_allocator_type, element_skipfield_type > &b) COLONY_NOEXCEPT_SWAP(element_allocator_type)
Swaps colony A's contents with that of colony B.
template<event_type Type>
static void get_fields_if_match (event_type type, event::fields_type &out)
template<int... I>
static event::fields_type get_fields_helper (event_type type, std::integer_sequence< int, I... >)
template<class T , typename Hash = std::hash<T>>
void hash_combine (std::size_t &seed, const T &v, const Hash &hash=std::hash< T >())
std::size_t hash64 (std::uint64_t val)
template<class swap_element_type , class swap_element_allocator_type >
void swap (list< swap_element_type, swap_element_allocator_type > &a, list< swap_element_type, swap_element_allocator_type > &b) LIST_NOEXCEPT_SWAP(swap_element_allocator_type)
template<class T , class... Args>
poly_serialized< T > make_poly_serialized (Args &&...args)
void throw_error (const string_formatter &, const std::string &)
std::string_view string_formatter_set_temp_buffer (const string_formatter &, std::string_view)
std::string handle_string_format_error ()
template<typename RT , typename T >
std::enable_if< is_integer< RT >::value &&is_integer< T >::value, RT >::type convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< is_integer< RT >::value &&std::is_enum< typenamestd::decay< T >::type >::value, RT >::type convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_floating_point< RT >::value &&is_numeric< T >::value &&!is_integer< T >::value, RT >::type convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, void * >::value &&std::is_pointer< typenamestd::decay< T >::type >::value, void * >::type convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, std::string_view >::value &&is_string< T >::value, std::string_view >::type convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, std::string_view >::value &&is_string_view< T >::value, std::string_view >::type convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, std::string_view >::value &&is_cstring< T >::value, std::string_view >::type convert (RT *, const string_formatter &, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, std::string_view >::value &&is_translation< T >::value, std::string_view >::type convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, std::string_view >::value &&is_string_id< T >::value, std::string_view >::type convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, std::string_view >::value &&is_numeric< T >::value &&!is_char< T >::value, std::string_view >::type convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
std::enable_if< std::is_same< RT, std::string_view >::value &&is_numeric< T >::value &&is_char< T >::value, std::string_view >::type convert (RT *, const string_formatter &sf, T &&value, int)
template<typename RT , typename T >
RT convert (RT *, const string_formatter &sf, T &&,...)
template<class T , class... Args>
value_ptr< T > make_value (Args &&...args)
template<class T >
bool value_ptr_equals (const value_ptr< T > &lhs, const value_ptr< T > &rhs)
Variables
constexpr size_t DEFAULT_LUA_LOG_CAPACITY = 100
Enumeration Type Documentation
LuaLogLevel
enum class cata::LuaLogLevel strong
Enumerator
Input
Info
Warn
Error
DebugMsg
Definition at line 13 of file catalua_log.h.
                       {
    Input,
    Info,
    Warn,
    Error,
    DebugMsg,
};
Function Documentation
clear_mod_being_loaded()
void cata::clear_mod_being_loaded (lua_state &)
Definition at line 83 of file catalua.cpp.
{}
Referenced by load_and_finalize_packs().
convert() [1/10]
template<typename RT , typename T > std::enable_if< is_integer< RT >::value &&std::is_enum< typenamestd::decay< T >::type >::value, RT >::type cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 105 of file string_formatter.h.
{
    return static_cast<RT>( value );
}
convert() [2/10]
template<typename RT , typename T > std::enable_if< std::is_floating_point< RT >::value &&is_numeric< T >::value &&!is_integer< T >::value, RT >::type cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 111 of file string_formatter.h.
{
    return value;
}
convert() [3/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, void * >::value &&std::is_pointer< typenamestd::decay< T >::type >::value, void * >::type cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 117 of file string_formatter.h.
{
    return const_cast<typename std::remove_const<typename std::remove_pointer<typename std::decay<T>::type>::type>::type *>
           ( value );
}
convert() [4/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, std::string_view >::value &&is_string< T >::value, std::string_view >::type cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 125 of file string_formatter.h.
{
    return value;
}
convert() [5/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, std::string_view >::value &&is_string_view< T >::value, std::string_view >::type cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 132 of file string_formatter.h.
{
    return value;
}
convert() [6/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, std::string_view >::value &&is_cstring< T >::value, std::string_view >::type cata::convert (RT * , const string_formatter & , T && value, int) inline
Definition at line 138 of file string_formatter.h.
{
    return value;
}
convert() [7/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, std::string_view >::value &&is_translation< T >::value, std::string_view >::type cata::convert (RT * , const string_formatter & sf, T && value, int) inline
Definition at line 145 of file string_formatter.h.
{
    return string_formatter_set_temp_buffer( sf, value.translated() );
}
References string_formatter_set_temp_buffer().
convert() [8/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, std::string_view >::value &&is_string_id< T >::value, std::string_view >::type cata::convert (RT * , const string_formatter & sf, T && value, int) inline
Definition at line 151 of file string_formatter.h.
{
    return string_formatter_set_temp_buffer( sf, value.str() );
}
References string_formatter_set_temp_buffer().
convert() [9/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, std::string_view >::value &&is_numeric< T >::value &&!is_char< T >::value, std::string_view >::type cata::convert (RT * , const string_formatter & sf, T && value, int) inline
Definition at line 157 of file string_formatter.h.
{
    return string_formatter_set_temp_buffer( sf, std::to_string( value ) );
}
References string_formatter_set_temp_buffer(), and to_string().
convert() [10/10]
template<typename RT , typename T > std::enable_if< std::is_same< RT, std::string_view >::value &&is_numeric< T >::value &&is_char< T >::value, std::string_view >::type cata::convert (RT * , const string_formatter & sf, T && value, int) inline
Definition at line 164 of file string_formatter.h.
{
    return string_formatter_set_temp_buffer( sf, std::string( 1, value ) );
}
References string_formatter_set_temp_buffer().
debug_write_lua_backtrace()
void cata::debug_write_lua_backtrace (std::ostream &)
Definition at line 59 of file catalua.cpp.
{
    // Nothing to do here
}
Referenced by detail::realDebugLog().
deserialize_lua_table()
void cata::deserialize_lua_table (sol::table t, JsonObject & obj)
find_cycles()
template<typename T > std::vector< std::vector< T > > cata::find_cycles (const std::unordered_map< T, std::vector< T > > & edges)
Definition at line 105 of file cata_algo.h.
{
    std::unordered_set<T> visited;
    std::unordered_map<T, T> on_current_branch;
    std::vector<std::vector<T>> result;
    for( const auto &p : edges ) {
        const T &root = p.first;
        on_current_branch.emplace( root, root );
        find_cycles_impl( edges, root, visited, on_current_branch, result );
        on_current_branch.erase( root );
        assert( on_current_branch.empty() );
    }
    return result;
}
References find_cycles_impl().
Referenced by recipe_dictionary::find_items_on_loops().
find_cycles_impl()
template<typename T > void cata::find_cycles_impl (const std::unordered_map< T, std::vector< T > > & edges, const T & v, std::unordered_set< T > & visited, std::unordered_map< T, T > & on_current_branch, std::vector< std::vector< T > > & result)
Definition at line 50 of file cata_algo.h.
{
    bool new_vertex = visited.insert( v ).second;
    if( !new_vertex ) {
        return;
    }
    auto it = edges.find( v );
    if( it == edges.end() ) {
        return;
    }
    for( const T &next_v : it->second ) {
        if( next_v == v ) {
            // Trivial self-loop
            result.push_back( { v } );
            continue;
        }
        auto previous_match = on_current_branch.find( next_v );
        if( previous_match != on_current_branch.end() ) {
            // We have looped back to somewhere along the branch we took to
            // reach this vertex, so reconstruct the loop and save it.
            std::vector<T> loop;
            T on_path = v;
            while( true ) {
                loop.push_back( on_path );
                if( on_path == next_v ) {
                    break;
                }
                on_path = on_current_branch[on_path];
            }
            std::reverse( loop.begin(), loop.end() );
            result.push_back( loop );
        } else {
            on_current_branch.emplace( next_v, v );
            find_cycles_impl( edges, next_v, visited, on_current_branch, result );
            on_current_branch.erase( next_v );
        }
    }
}
References find_cycles_impl().
Referenced by find_cycles(), and find_cycles_impl().
generate_lua_docs()
bool cata::generate_lua_docs ()
Definition at line 35 of file catalua.cpp.
{
    // Nothing to do here
    return false;
}
Referenced by main().
get_fields_helper()
template<int... I> static event::fields_type cata::get_fields_helper (event_type type, std::integer_sequence< int, I... >) static
Definition at line 154 of file event.cpp.
{
    event::fields_type result;
    bool discard[] = {
        ( get_fields_if_match<static_cast<event_type>( I )>( type, result ), true )...
    };
    ( void ) discard;
    return result;
}
Referenced by cata::event::get_fields().
get_fields_if_match()
template<event_type Type> static void cata::get_fields_if_match (event_type type, event::fields_type & out) static
Definition at line 143 of file event.cpp.
{
    if( Type == type ) {
        out = { event_detail::event_spec<Type>::fields.begin(),
                event_detail::event_spec<Type>::fields.end()
              };
    }
}
get_lapi_version_string()
std::string cata::get_lapi_version_string ()
Definition at line 25 of file catalua.cpp.
{
    return "<none>";
}
Referenced by game_info::game_report(), and main().
get_lua_api_version()
int cata::get_lua_api_version ()
Definition at line 405 of file catalua.cpp.
{
    return LUA_API_VERSION;
}
References LUA_API_VERSION.
Referenced by load_and_finalize_packs().
get_lua_log_instance()
lua_log_handler & cata::get_lua_log_instance ()
handle_string_format_error()
std::string cata::handle_string_format_error ()
Definition at line 120 of file string_formatter.cpp.
{
    try {
        throw;
    } catch( const std::exception &err ) {
        return err.what();
    }
}
Referenced by string_format().
has_lua()
bool cata::has_lua ()
Definition at line 20 of file catalua.cpp.
{
    return false;
}
Referenced by init::check_mods_for_errors(), debug_menu::debug_menu_uilist(), main_menu::display_sub_menu(), worldfactory::draw_mod_list(), load_and_finalize_packs(), main_menu::load_character_tab(), and worldfactory::pick_world().
hash64()
std::size_t cata::hash64 (std::uint64_t val) inline
Definition at line 113 of file hash_utils.h.
{
    return hash64_detail::maybe_mix_bits<std::size_t>( val );
}
Referenced by node_address_hasher::operator()().
hash_combine()
template<class T , typename Hash = std::hash<T>> void cata::hash_combine (std::size_t & seed, const T & v, const Hash & hash = std::hash<T>()) inline
Definition at line 20 of file hash_utils.h.
{
    seed ^= hash( v ) + 0x9e3779b9 + ( seed << 6 ) + ( seed >> 2 );
}
References iuse::seed().
Referenced by cata::tuple_hash_detail::Impl< Tuple, Index >::apply(), cata::tuple_hash_detail::Impl< Tuple, 0 >::apply(), mongroup_hash::operator()(), cata::range_hash::operator()(), and cata::tuple_hash::operator()().
init_global_state_tables()
void cata::init_global_state_tables (lua_state & , const std::vector< mod_id > &)
Definition at line 81 of file catalua.cpp.
{}
Referenced by load_and_finalize_packs().
load_world_lua_state()
bool cata::load_world_lua_state (const std::string &)
Definition at line 69 of file catalua.cpp.
{
    return true;
}
Referenced by game::load().
make_poly_serialized()
template<class T , class... Args> poly_serialized< T > cata::make_poly_serialized (Args &&... args)
Definition at line 61 of file poly_serialized.h.
{
    return poly_serialized<T>( new T( std::forward<Args>( args )... ) );
}
make_readonly_table() [1/2]
sol::table cata::make_readonly_table (sol::state_view & lua, sol::table read_from)
Referenced by luna::finalize_enum(), and luna::finalize_lib().
make_readonly_table() [2/2]
sol::table cata::make_readonly_table (sol::state_view & lua, sol::table read_from, const std::string & error_msg)
make_value()
template<class T , class... Args> value_ptr< T > cata::make_value (Args &&... args)
Definition at line 51 of file value_ptr.h.
{
    return value_ptr<T>( new T( std::forward<Args>( args )... ) );
}
make_wrapped_state()
std::unique_ptr< lua_state, lua_state_deleter > cata::make_wrapped_state ()
Definition at line 74 of file catalua.cpp.
{
    return std::unique_ptr<lua_state, lua_state_deleter>(
               new lua_state{}, lua_state_deleter{}
           );
}
Referenced by load_and_finalize_packs().
reg_all_bindings()
void cata::reg_all_bindings (sol::state & lua)
reg_lua_iuse_actors()
void cata::reg_lua_iuse_actors (lua_state & , Item_factory &)
Definition at line 87 of file catalua.cpp.
{}
Referenced by load_and_finalize_packs().
reload_lua_code()
void cata::reload_lua_code ()
Definition at line 50 of file catalua.cpp.
{
    query_popup()
    .default_color( c_red )
    .allow_anykey( true )
    .message( "%s", "Can't reload Lua code:\nthe game was compiled without Lua support." )
    .query();
}
References query_popup::allow_anykey(), c_red, query_popup::default_color(), query_popup::message(), and query_popup::query().
Referenced by game::handle_action().
run_hooks()
template<typename... Args> void cata::run_hooks (Args && ...)
Definition at line 90 of file catalua.cpp.
{}
Referenced by run_on_game_load_hooks(), run_on_game_save_hooks(), and run_on_mapgen_postprocess_hooks().
run_mod_finalize_script()
void cata::run_mod_finalize_script (lua_state & , const mod_id &)
Definition at line 85 of file catalua.cpp.
{}
Referenced by load_and_finalize_packs().
run_mod_main_script()
void cata::run_mod_main_script (lua_state & , const mod_id &)
Definition at line 86 of file catalua.cpp.
{}
Referenced by init::load_main_lua_scripts().
run_mod_preload_script()
void cata::run_mod_preload_script (lua_state & , const mod_id &)
Definition at line 84 of file catalua.cpp.
{}
Referenced by load_and_finalize_packs().
run_on_every_x_hooks()
void cata::run_on_every_x_hooks (lua_state &)
Definition at line 92 of file catalua.cpp.
{}
Referenced by game::do_turn().
run_on_game_load_hooks()
void cata::run_on_game_load_hooks (lua_state & state)
Definition at line 420 of file catalua.cpp.
{
    run_hooks( state, "on_game_load" );
}
References run_hooks().
Referenced by game::load().
run_on_game_save_hooks()
void cata::run_on_game_save_hooks (lua_state & state)
Definition at line 415 of file catalua.cpp.
{
    run_hooks( state, "on_game_save" );
}
References run_hooks().
Referenced by game::save().
run_on_mapgen_postprocess_hooks()
void cata::run_on_mapgen_postprocess_hooks (lua_state & state, map & m, const tripoint & p, const time_point & when)
Definition at line 425 of file catalua.cpp.
{
    run_hooks( state, "on_mapgen_postprocess", m, p, when );
}
References run_hooks().
Referenced by map::generate().
save_world_lua_state()
bool cata::save_world_lua_state (const std::string &)
Definition at line 64 of file catalua.cpp.
{
    return true;
}
Referenced by game::save().
serialize_lua_table()
void cata::serialize_lua_table (sol::table t, JsonOut & jsout)
set_mod_being_loaded()
void cata::set_mod_being_loaded (lua_state & , const mod_id &)
Definition at line 82 of file catalua.cpp.
{}
Referenced by load_and_finalize_packs(), and init::load_main_lua_scripts().
show_lua_console()
void cata::show_lua_console ()
Definition at line 41 of file catalua.cpp.
{
    query_popup()
    .default_color( c_red )
    .allow_anykey( true )
    .message( "%s", "Can't open Lua console:\nthe game was compiled without Lua support." )
    .query();
}
References query_popup::allow_anykey(), c_red, query_popup::default_color(), query_popup::message(), and query_popup::query().
Referenced by debug_menu::debug(), and game::handle_action().
show_lua_console_impl()
void cata::show_lua_console_impl ()
sort_by_rating()
template<typename Iterator , typename RatingFunction > void cata::sort_by_rating (Iterator begin, Iterator end, RatingFunction rating_func)
Sort elements of a sequence by their rating (the smaller the better).
Parameters
begin An input/output iterator.
end An input/output iterator.
rating_func A functor which calculates ratings (the outcome must be comparable using '<' operator).
The rating is calculated only once per each element.
Definition at line 25 of file cata_algo.h.
{
    using value_t = typename Iterator::value_type;
    using pair_t = std::pair<value_t, decltype( rating_func( *begin ) )>;
    std::vector<pair_t> rated_entries;
    rated_entries.reserve( std::distance( begin, end ) );
    std::transform( begin, end, std::back_inserter( rated_entries ),
    [ &rating_func ]( const value_t &elem ) {
        return std::make_pair( elem, rating_func( elem ) );
    } );
    std::sort( rated_entries.begin(), rated_entries.end(), []( const pair_t &lhs, const pair_t &rhs ) {
        return lhs.second < rhs.second;
    } );
    std::transform( rated_entries.begin(), rated_entries.end(), begin, []( const pair_t &elem ) {
        return elem.first;
    } );
}
References iexamine::transform().
Referenced by npc::move_away_from().
startup_lua_test()
void cata::startup_lua_test ()
Definition at line 30 of file catalua.cpp.
{
    // Nothing to do here
}
Referenced by main().
string_formatter_set_temp_buffer()
std::string_view cata::string_formatter_set_temp_buffer (const string_formatter & , std::string_view)
This is used for printing non-strings through "%s". It only works because this prints each format specifier separately, so the content of temp_buffer is only used once.
Definition at line 264 of file string_formatter.h.
{
            sf.temp_buffer = text;
            return std::string_view( sf.temp_buffer );
        }
Referenced by convert().
swap() [1/2]
template<class element_type , class element_allocator_type , typename element_skipfield_type > void cata::swap (colony< element_type, element_allocator_type, element_skipfield_type > & a, colony< element_type, element_allocator_type, element_skipfield_type > & b) inline
Swaps colony A's contents with that of colony B.
Assumes both colonies have same element type, allocator type, etc.
Definition at line 3496 of file colony.h.
{
    a.swap( b );
}
Referenced by approx_orientation(), assign(), closest_points_first(), consolidate(), vehicle::coord_translate(), vehicle::coord_translate_reverse(), vehicle::damage_all(), draw_square(), detail::fallback_uintptr::fallback_uintptr(), Item_factory::finalize_pre(), CellularAutomata::generate_cellular_automaton(), item::io(), mutation_branch::load(), editmap::mapgen_preview(), monexamine::mfriend_menu(), monexamine::pet_menu(), rng(), rng_float(), rng_normal(), map::rotate(), auto_pickup::user_interface::show(), Messages::dialog::show(), safemode::show(), panel_manager::show_adm(), show_bionics_ui(), detail::show_mutations_ui_internal(), cata::list< element_type, element_allocator_type >::splice(), zone_manager::swap(), advanced_inventory::swap_panes(), maptile_soa< sx, sy >::swap_soa_tile(), and Character::update_fuel_storage().
swap() [2/2]
template<class swap_element_type , class swap_element_allocator_type > void cata::swap (list< swap_element_type, swap_element_allocator_type > & a, list< swap_element_type, swap_element_allocator_type > & b) inline
Definition at line 2446 of file list.h.
{
    a.swap( b );
}
throw_error()
void cata::throw_error (const string_formatter & , const std::string &)
Definition at line 257 of file string_formatter.h.
{
            sf.throw_error( msg );
        }
Referenced by convert(), and cata::string_formatter::read_number_or_argument_index().
unreachable()
void cata::unreachable () inline
Marks unreachable code.
Utility function to mark unreachable code to help compiler with optimizations.
Usage: void (bool always_true) { if (always_true) { return; } else { // If always_true happens to be false, this will cause Undefined Behavior. cata::unreachable(); } }
Source: https://stackoverflow.com/a/65258501
Definition at line 37 of file cata_unreachable.h.
{}
Referenced by cast_zlight_segment(), castLight(), relic_funcs::check_recharge_reqs(), and iexamine::ledge().
value_ptr_equals()
template<class T > bool cata::value_ptr_equals (const value_ptr< T > & lhs, const value_ptr< T > & rhs)
Definition at line 57 of file value_ptr.h.
{
    return ( !lhs && !rhs ) || ( lhs && rhs && *lhs == *rhs );
}
Referenced by translation::operator==().
Variable Documentation
DEFAULT_LUA_LOG_CAPACITY
constexpr size_t cata::DEFAULT_LUA_LOG_CAPACITY = 100 constexpr
Definition at line 11 of file catalua_log.h.