Cataclysm BN: luna Namespace Reference
luna Namespace Reference
Namespaces
namespace detail
Classes
struct no_bases_t
struct userenum
struct userlib
Typedefs
template<typename ... Args>
using bases = sol::bases< Args... >
template<typename ... Args>
using constructors = sol::constructors< Args... >
Functions
template<typename Class , typename ConstructorScheme , typename Bases >
sol::usertype< Class > new_usertype (sol::state_view &lua, Bases &&bases, ConstructorScheme &&constructor)
template<typename Class , typename Key , typename Func >
void set_fx (sol::usertype< Class > &ut, Key &&key, Func value)
template<typename Class , typename Key , typename Value >
void set (sol::usertype< Class > &ut, Key &&key, Value &&value)
template<typename Enum >
userenum< Enum > begin_enum (sol::state_view &lua)
template<typename Enum , typename Key >
void add_val (userenum< Enum > &e, const Key &key, const Enum &value)
template<typename Enum >
void finalize_enum (userenum< Enum > &e)
userlib begin_lib (sol::state_view &lua, std::string_view name)
template<typename Key , typename Func >
void set_fx (userlib &lib, Key &&key, Func value)
template<typename Key , typename Value >
void set (userlib &lib, Key &&key, Value &&value)
void finalize_lib (userlib &lib)
void doc (std::string_view doc)
Variables
constexpr static no_bases_t no_bases
constexpr sol::no_construction no_constructor
Typedef Documentation
bases
template<typename ... Args> using luna::bases = typedef sol::bases<Args...>
Definition at line 41 of file catalua_luna.h.
constructors
template<typename ... Args> using luna::constructors = typedef sol::constructors<Args...>
Definition at line 46 of file catalua_luna.h.
Function Documentation
add_val()
template<typename Enum , typename Key > void luna::add_val (userenum< Enum > & e, const Key & key, const Enum & value)
Definition at line 475 of file catalua_luna.h.
{
    e.t[key] = value;
}
References luna::userenum< E >::t.
begin_enum()
template<typename Enum > userenum< Enum > luna::begin_enum (sol::state_view & lua)
Definition at line 464 of file catalua_luna.h.
{
    static_assert( detail::luna_traits<Enum>::impl, "Type must implement luna_traits<T>" );
    sol::table ut = lua.create_table();
    return userenum<Enum> { ut };
}
begin_lib()
userlib luna::begin_lib (sol::state_view & lua, std::string_view name) inline
Definition at line 525 of file catalua_luna.h.
{
    // Ensure global doctable exists
    sol::table global_dt = detail::get_global_doctable( lua );
    // Create doctable for this lib
    sol::table lib_dt = lua.create_table();
    global_dt[detail::KEY_LIBS][name] = lib_dt;
    // Init members table
    lib_dt[detail::KEY_MEMBER] = std::vector<sol::object>();
    // Library comment
    detail::add_comment( lib_dt, detail::KEY_LIB_COMMENT );
    // Create library itself
    sol::table t = lua.create_table();
    // Link to original library from docs
    lib_dt[detail::KEY_LIB_IMPL] = t;
    return userlib { t, name, lib_dt };
}
References luna::detail::add_comment(), luna::detail::get_global_doctable(), luna::detail::KEY_LIB_COMMENT, luna::detail::KEY_LIB_IMPL, luna::detail::KEY_LIBS, and luna::detail::KEY_MEMBER.
doc()
void luna::doc (std::string_view doc) inline
Definition at line 599 of file catalua_luna.h.
{
    detail::current_comment = doc;
}
References luna::detail::current_comment, and doc().
Referenced by doc().
finalize_enum()
template<typename Enum > void luna::finalize_enum (userenum< Enum > & e)
Definition at line 485 of file catalua_luna.h.
{
    sol::state_view lua( e.t.lua_state() );
    constexpr std::string_view name = detail::luna_traits<Enum>::name;
    // Ensure global doctable exists
    sol::table global_dt = detail::get_global_doctable( lua );
    // Create doctable for this enum
    sol::table enum_dt = lua.create_table();
    global_dt[detail::KEY_ENUMS][name] = enum_dt;
    // Link to original list of entries
    enum_dt[detail::KEY_ENUM_ENTRIES] = e.t;
    // Make read-only so Lua code doesn't mess with it
    sol::table et = cata::make_readonly_table(
                        lua, e.t,
                        string_format( "Tried to modify enum table %s.", name )
                    );
    lua.globals()[name] = et;
    e.finalized = true;
}
References luna::userenum< E >::finalized, luna::detail::get_global_doctable(), luna::detail::KEY_ENUM_ENTRIES, luna::detail::KEY_ENUMS, cata::make_readonly_table(), string_format(), and luna::userenum< E >::t.
finalize_lib()
void luna::finalize_lib (userlib & lib) inline
Definition at line 584 of file catalua_luna.h.
{
    sol::state_view lua( lib.t.lua_state() );
    // Make read-only so Lua code doesn't mess with it
    sol::table et = cata::make_readonly_table(
                        lua, lib.t,
                        string_format( "Tried to modify library %s.", lib.name )
                    );
    lua.globals()[lib.name] = et;
    lib.finalized = true;
}
References luna::userlib::finalized, cata::make_readonly_table(), luna::userlib::name, string_format(), and luna::userlib::t.
new_usertype()
template<typename Class , typename ConstructorScheme , typename Bases > sol::usertype< Class > luna::new_usertype (sol::state_view & lua, Bases && bases, ConstructorScheme && constructor)
Definition at line 367 of file catalua_luna.h.
{
    static_assert( detail::luna_traits<Class>::impl, "Type must implement luna_traits<T>" );
    // Ensure global doctable exists
    sol::table global_dt = detail::get_global_doctable( lua );
    constexpr std::string_view name = detail::luna_traits<Class>::name;
    // Register Sol usertype
    sol::usertype<Class> ut;
    using BasesBare = detail::remove_cv_ref_t<Bases>;
    if constexpr( std::is_same_v<BasesBare, no_bases_t> ) {
        ut = lua.new_usertype<Class>( name, constructor );
    } else {
        ut = lua.new_usertype<Class>( name, constructor, sol::base_classes, bases );
    }
    // Create doctable for this type
    sol::table type_dt = lua.create_table();
    global_dt[detail::KEY_TYPES][name] = type_dt;
    // Link relevant Sol usertype in docs
    type_dt[detail::KEY_TYPE_IMPL] = ut;
    // Doc comment
    detail::add_comment( type_dt, detail::KEY_USERTYPE_COMMENT );
    // Init members table
    type_dt[detail::KEY_MEMBER] = std::vector<sol::object>();
    // Document constructors (or lack thereof)
    detail::doc_constructors( type_dt, constructor );
    // Document bases (or lack thereof)
    detail::doc_bases( type_dt, bases );
    // Add helper method to get name under which usertype is bound in Lua
    ut[detail::KEY_GET_TYPE] = []() -> std::string_view {
        return detail::luna_traits<Class>::name;
    };
    return ut;
}
References luna::detail::add_comment(), luna::detail::doc_bases(), luna::detail::doc_constructors(), luna::detail::get_global_doctable(), luna::detail::KEY_GET_TYPE, luna::detail::KEY_MEMBER, luna::detail::KEY_TYPE_IMPL, luna::detail::KEY_TYPES, and luna::detail::KEY_USERTYPE_COMMENT.
set() [1/2]
template<typename Class , typename Key , typename Value > void luna::set (sol::usertype< Class > & ut, Key && key, Value && value)
Definition at line 436 of file catalua_luna.h.
{
    ut[ key ] = std::forward<Value>( value );
    sol::state_view lua( ut.lua_state() );
    sol::table type_dt = detail::get_type_doctable<Class>( lua );
    sol::table member_dt = detail::make_type_member_doctable( type_dt, key );
    detail::doc_member<Class>( member_dt, sol::types<Value>() );
}
References luna::detail::make_type_member_doctable().
Referenced by draw_circle(), draw_line(), draw_rough_circle(), draw_square(), erase_if(), basic_memory_buffer< T, SIZE, Allocator >::grow(), Creature::set_all_parts_hp_cur(), bodypart::set_damage_bandaged(), bodypart::set_damage_disinfected(), bodypart::set_healed_total(), bodypart::set_hp_cur(), bodypart::set_hp_max(), mongroup::set_interest(), Creature::set_part_healed_total(), Creature::set_part_hp_cur(), Creature::set_part_hp_max(), setupDebug(), shift_tripoint_set(), stats_tracker::unwatch(), and stats_tracker::unwatch_all().
set() [2/2]
template<typename Key , typename Value > void luna::set (userlib & lib, Key && key, Value && value)
Definition at line 571 of file catalua_luna.h.
{
    lib.t[ key ] = value;
    sol::state_view lua( lib.t.lua_state() );
    sol::table member_dt = detail::make_type_member_doctable( lib.dt, key );
    detail::doc_free( member_dt, value );
}
References luna::detail::doc_free(), luna::userlib::dt, luna::detail::make_type_member_doctable(), and luna::userlib::t.
set_fx() [1/2]
template<typename Class , typename Key , typename Func > void luna::set_fx (sol::usertype< Class > & ut, Key && key, Func value)
Definition at line 417 of file catalua_luna.h.
{
    // Due to a bug in sol2, on GCC build protected function call may call wrong lambda
    // https://github.com/ThePhD/sol2/issues/1444
    // This happens if we register with table.set( key, func ), but for
    // some reason table[key] = func makes it work fine.
    ut[ key ] = std::forward<Func>( value );
    sol::state_view lua( ut.lua_state() );
    sol::table type_dt = detail::get_type_doctable<Class>( lua );
    sol::table member_dt = detail::make_type_member_doctable( type_dt, key );
    detail::doc_member_fx<Class>( member_dt, sol::types<Func>() );
}
References luna::detail::make_type_member_doctable().
Referenced by reg_serde_functions().
set_fx() [2/2]
template<typename Key , typename Func > void luna::set_fx (userlib & lib, Key && key, Func value)
Definition at line 553 of file catalua_luna.h.
{
    // Due to a bug in sol2, on GCC build protected function call may call wrong lambda
    // https://github.com/ThePhD/sol2/issues/1444
    // This happens if we register with table.set( key, func ), but for
    // some reason table[key] = func makes it work fine.
    lib.t[ key ] = std::forward<Func>( value );
    sol::state_view lua( lib.t.lua_state() );
    sol::table member_dt = detail::make_type_member_doctable( lib.dt, key );
    detail::doc_free_fx( member_dt, sol::types<Func>() );
}
References luna::detail::doc_free_fx(), luna::userlib::dt, luna::detail::make_type_member_doctable(), and luna::userlib::t.
Variable Documentation
no_bases
constexpr static no_bases_t luna::no_bases static constexpr
Definition at line 38 of file catalua_luna.h.
no_constructor
constexpr sol::no_construction luna::no_constructor constexpr
Definition at line 43 of file catalua_luna.h.