Cataclysm BN: luna::detail Namespace Reference
luna::detail Namespace Reference
Classes
struct luna_traits
Typedefs
template<typename T >
using remove_cv_ref_t = typename std::remove_cv< typename std::remove_reference< T >::type >::type
template<typename Signature >
using fx_traits = sol::meta::meta_detail::fx_traits< Signature >
Functions
void add_comment (sol::table &dt, std::string_view key)
template<typename Val >
std::string doc_value_impl ()
template<typename Val >
std::string doc_value (sol::types< Val >)
template<typename ... Args>
std::string doc_value (sol::types< std::tuple< Args... > >)
template<typename Val >
std::string doc_value (sol::types< sol::optional< Val > >)
template<typename ... Args>
std::vector< std::string > doc_arg_list ()
template<typename RetVal , typename ... Args>
std::vector< std::string > doc_one_constructor (std::function< RetVal(Args...)>)
template<typename ... Args>
void doc_constructors (sol::table &dt, const sol::constructor_list< Args... > &)
void doc_constructors (sol::table &dt, const sol::no_construction &)
template<typename ... Args>
void doc_bases (sol::table &dt, const sol::bases< Args... > &)
void doc_bases (sol::table &dt, const no_bases_t &)
sol::table get_global_doctable (sol::state_view &lua)
template<typename Class >
sol::table get_type_doctable (sol::state_view &lua)
template<typename Class >
sol::table get_enum_doctable (sol::state_view &lua)
template<typename Class , typename Value >
void doc_member (sol::table &dt, sol::types< Value Class::* > &&)
template<typename Class , bool add_self_arg, typename RetVal , typename ... Args>
void doc_member_fx_impl2 (sol::table &dt, sol::types< RetVal > &&, sol::types< Args... > &&)
template<typename Class , typename Function >
void doc_member_fx_overload (sol::table &dt, std::vector< sol::table > &overloads)
template<typename Class , typename ... Functions>
void doc_member_fx_impl (sol::table &dt, sol::types< Functions... > &&)
template<typename Class , typename ... Functions>
void doc_member_fx (sol::table &dt, sol::types< sol::overload_set< Functions... > > &&)
template<typename Class , typename Func >
void doc_member_fx (sol::table &dt, sol::types< Func > &&)
template<typename Value >
void doc_free (sol::table &dt, Value val)
template<typename RetVal , typename ... Args>
void doc_free_fx_impl2 (sol::table &dt, sol::types< RetVal > &&, sol::types< Args... > &&)
template<typename Function >
void doc_free_fx_overload (sol::table &dt, std::vector< sol::table > &overloads)
template<typename ... Functions>
void doc_free_fx_impl (sol::table &dt, sol::types< Functions... > &&)
template<typename ... Functions>
void doc_free_fx (sol::table &dt, sol::types< sol::overload_set< Functions... > > &&)
template<typename Func >
void doc_free_fx (sol::table &dt, sol::types< Func > &&)
template<typename Key >
sol::table make_type_member_doctable (sol::table type_dt, const Key &key)
Variables
constexpr std::string_view KEY_TYPES = "#types"
constexpr std::string_view KEY_ENUMS = "#enums"
constexpr std::string_view KEY_LIBS = "#libs"
constexpr std::string_view KEY_LIB_IMPL = "#lib_impl"
constexpr std::string_view KEY_LIB_COMMENT = "lib_comment"
constexpr std::string_view KEY_ENUM_ENTRIES = "entries"
constexpr std::string_view KEY_TYPE_IMPL = "#type_impl"
constexpr std::string_view KEY_DOCTABLE = "catadoc"
constexpr std::string_view KEY_BASES = "#bases"
constexpr std::string_view KEY_CONSTRUCT = "#construct"
constexpr std::string_view KEY_MEMBER = "#member"
constexpr std::string_view KEY_MEMBER_TYPE = "type"
constexpr std::string_view KEY_MEMBER_COMMENT = "comment"
constexpr std::string_view KEY_MEMBER_VARIABLE_TYPE = "vartype"
constexpr std::string_view KEY_MEMBER_VARIABLE_HAS_VALUE = "hasval"
constexpr std::string_view KEY_MEMBER_VARIABLE_VALUE = "varval"
constexpr std::string_view KEY_MEMBER_ARGS = "args"
constexpr std::string_view KEY_MEMBER_OVERLOADS = "overloads"
constexpr std::string_view KEY_MEMBER_RETVAL = "retval"
constexpr std::string_view KEY_MEMBER_NAME = "name"
constexpr std::string_view KEY_GET_TYPE = "get_luna_type"
constexpr std::string_view KEY_USERTYPE_COMMENT = "type_comment"
constexpr std::string_view MEMBER_IS_VAR = "var"
constexpr std::string_view MEMBER_IS_FUNC = "func"
constexpr std::string_view MEMBER_IS_CONST_FUNC = "const_func"
std::string_view current_comment
Typedef Documentation
fx_traits
template<typename Signature > using luna::detail::fx_traits = typedef sol::meta::meta_detail::fx_traits<Signature>
Definition at line 90 of file catalua_luna.h.
remove_cv_ref_t
template<typename T > using luna::detail::remove_cv_ref_t = typedef typename std::remove_cv<typename std::remove_reference<T>::type>::type
Definition at line 87 of file catalua_luna.h.
Function Documentation
add_comment()
void luna::detail::add_comment (sol::table & dt, std::string_view key) inline
Definition at line 92 of file catalua_luna.h.
{
    if( !current_comment.empty() ) {
        dt[key] = current_comment;
        current_comment = "";
    }
}
References current_comment.
Referenced by luna::begin_lib(), doc_free(), doc_free_fx_impl(), doc_member(), doc_member_fx_impl(), and luna::new_usertype().
doc_arg_list()
template<typename ... Args> std::vector< std::string > luna::detail::doc_arg_list ()
Definition at line 156 of file catalua_luna.h.
{
    std::vector<std::string> ret;
    ( (
          ret.push_back(
              doc_value( sol::types<Args>() ) )
      ), ... );
    return ret;
}
References doc_value(), and cata::hash64_detail::ret.
Referenced by doc_free_fx_impl2(), doc_member_fx_impl2(), and doc_one_constructor().
doc_bases() [1/2]
void luna::detail::doc_bases (sol::table & dt, const no_bases_t &) inline
Definition at line 204 of file catalua_luna.h.
{
    std::vector<std::string> ctors;
    dt[KEY_BASES] = ctors;
}
References KEY_BASES.
doc_bases() [2/2]
template<typename ... Args> void luna::detail::doc_bases (sol::table & dt, const sol::bases< Args... > &)
Definition at line 193 of file catalua_luna.h.
{
    std::vector<std::string> bases;
    ( (
          bases.push_back( doc_value( sol::types<Args>() ) )
      ), ... );
    dt[KEY_BASES] = bases;
}
References doc_value(), and KEY_BASES.
Referenced by luna::new_usertype().
doc_constructors() [1/2]
template<typename ... Args> void luna::detail::doc_constructors (sol::table & dt, const sol::constructor_list< Args... > &)
Definition at line 175 of file catalua_luna.h.
{
    std::vector<std::vector<std::string>> ctors;
    ( (
          ctors.push_back( doc_one_constructor( std::function<Args>( nullptr ) ) )
      ), ... );
    dt[KEY_CONSTRUCT] = ctors;
}
References doc_one_constructor(), and KEY_CONSTRUCT.
Referenced by luna::new_usertype().
doc_constructors() [2/2]
void luna::detail::doc_constructors (sol::table & dt, const sol::no_construction &) inline
Definition at line 186 of file catalua_luna.h.
{
    std::vector<std::vector<std::string>> ctors;
    dt[KEY_CONSTRUCT] = ctors;
}
References KEY_CONSTRUCT.
doc_free()
template<typename Value > void luna::detail::doc_free (sol::table & dt, Value val)
Definition at line 301 of file catalua_luna.h.
{
    dt[KEY_MEMBER_TYPE] = MEMBER_IS_VAR;
    add_comment( dt, KEY_MEMBER_COMMENT );
    dt[KEY_MEMBER_VARIABLE_TYPE] = doc_value( sol::types<Value>() );
    dt[KEY_MEMBER_VARIABLE_HAS_VALUE] = true;
    dt[KEY_MEMBER_VARIABLE_VALUE] = val;
}
References add_comment(), doc_value(), KEY_MEMBER_COMMENT, KEY_MEMBER_TYPE, KEY_MEMBER_VARIABLE_HAS_VALUE, KEY_MEMBER_VARIABLE_TYPE, KEY_MEMBER_VARIABLE_VALUE, and MEMBER_IS_VAR.
Referenced by luna::set().
doc_free_fx() [1/2]
template<typename Func > void luna::detail::doc_free_fx (sol::table & dt, sol::types< Func > &&)
Definition at line 348 of file catalua_luna.h.
{
    doc_free_fx_impl( dt, sol::types<Func>() );
}
References doc_free_fx_impl().
doc_free_fx() [2/2]
template<typename ... Functions> void luna::detail::doc_free_fx (sol::table & dt, sol::types< sol::overload_set< Functions... > > &&)
Definition at line 342 of file catalua_luna.h.
{
    doc_free_fx_impl( dt, sol::types<Functions...>() );
}
References doc_free_fx_impl().
Referenced by luna::set_fx().
doc_free_fx_impl()
template<typename ... Functions> void luna::detail::doc_free_fx_impl (sol::table & dt, sol::types< Functions... > &&)
Definition at line 329 of file catalua_luna.h.
{
    dt[KEY_MEMBER_TYPE] = MEMBER_IS_FUNC;
    add_comment( dt, KEY_MEMBER_COMMENT );
    std::vector<sol::table> overloads;
    ( [&]() {
        doc_free_fx_overload<Functions>( dt, overloads );
    }
    (), ... );
    dt[KEY_MEMBER_OVERLOADS] = overloads;
}
References add_comment(), KEY_MEMBER_COMMENT, KEY_MEMBER_OVERLOADS, KEY_MEMBER_TYPE, and MEMBER_IS_FUNC.
Referenced by doc_free_fx().
doc_free_fx_impl2()
template<typename RetVal , typename ... Args> void luna::detail::doc_free_fx_impl2 (sol::table & dt, sol::types< RetVal > && , sol::types< Args... > &&)
Definition at line 311 of file catalua_luna.h.
{
    dt[KEY_MEMBER_RETVAL] = doc_value( sol::types<RetVal>() );
    dt[KEY_MEMBER_ARGS] = doc_arg_list<Args...>();
}
References doc_arg_list(), doc_value(), KEY_MEMBER_ARGS, and KEY_MEMBER_RETVAL.
Referenced by doc_free_fx_overload().
doc_free_fx_overload()
template<typename Function > void luna::detail::doc_free_fx_overload (sol::table & dt, std::vector< sol::table > & overloads)
Definition at line 318 of file catalua_luna.h.
{
    sol::state_view lua( dt.lua_state() );
    sol::table overload = lua.create_table();
    overloads.push_back( overload );
    using RetVal = typename fx_traits<Function>::return_type;
    using Args = typename fx_traits<Function>::args_list;
    doc_free_fx_impl2( overload, sol::types<RetVal>(), Args() );
}
References doc_free_fx_impl2().
doc_member()
template<typename Class , typename Value > void luna::detail::doc_member (sol::table & dt, sol::types< Value Class::* > &&)
Definition at line 244 of file catalua_luna.h.
{
    dt[KEY_MEMBER_TYPE] = MEMBER_IS_VAR;
    add_comment( dt, KEY_MEMBER_COMMENT );
    dt[KEY_MEMBER_VARIABLE_TYPE] = doc_value( sol::types<Value>() );
}
References add_comment(), doc_value(), KEY_MEMBER_COMMENT, KEY_MEMBER_TYPE, KEY_MEMBER_VARIABLE_TYPE, and MEMBER_IS_VAR.
doc_member_fx() [1/2]
template<typename Class , typename Func > void luna::detail::doc_member_fx (sol::table & dt, sol::types< Func > &&)
Definition at line 295 of file catalua_luna.h.
{
    doc_member_fx_impl<Class>( dt, sol::types<Func>() );
}
doc_member_fx() [2/2]
template<typename Class , typename ... Functions> void luna::detail::doc_member_fx (sol::table & dt, sol::types< sol::overload_set< Functions... > > &&)
Definition at line 289 of file catalua_luna.h.
{
    doc_member_fx_impl<Class>( dt, sol::types<Functions...>() );
}
doc_member_fx_impl()
template<typename Class , typename ... Functions> void luna::detail::doc_member_fx_impl (sol::table & dt, sol::types< Functions... > &&)
Definition at line 275 of file catalua_luna.h.
{
    dt[KEY_MEMBER_TYPE] = MEMBER_IS_FUNC;
    add_comment( dt, KEY_MEMBER_COMMENT );
    std::vector<sol::table> overloads;
    ( [&]() {
        doc_member_fx_overload<Class, Functions>( dt, overloads );
    }
    (), ... );
    dt[KEY_MEMBER_OVERLOADS] = overloads;
}
References add_comment(), KEY_MEMBER_COMMENT, KEY_MEMBER_OVERLOADS, KEY_MEMBER_TYPE, and MEMBER_IS_FUNC.
doc_member_fx_impl2()
template<typename Class , bool add_self_arg, typename RetVal , typename ... Args> void luna::detail::doc_member_fx_impl2 (sol::table & dt, sol::types< RetVal > && , sol::types< Args... > &&)
Definition at line 252 of file catalua_luna.h.
{
    dt[KEY_MEMBER_RETVAL] = doc_value( sol::types<RetVal>() );
    if constexpr( add_self_arg ) {
        dt[KEY_MEMBER_ARGS] = doc_arg_list<Class, Args...>();
    } else {
        dt[KEY_MEMBER_ARGS] = doc_arg_list<Args...>();
    }
}
References doc_arg_list(), doc_value(), KEY_MEMBER_ARGS, and KEY_MEMBER_RETVAL.
doc_member_fx_overload()
template<typename Class , typename Function > void luna::detail::doc_member_fx_overload (sol::table & dt, std::vector< sol::table > & overloads)
Definition at line 263 of file catalua_luna.h.
{
    sol::state_view lua( dt.lua_state() );
    sol::table overload = lua.create_table();
    overloads.push_back( overload );
    using RetVal = typename fx_traits<Function>::return_type;
    using Args = typename fx_traits<Function>::args_list;
    constexpr bool add_self_arg = !fx_traits<Function>::is_member_function;
    doc_member_fx_impl2<Class, add_self_arg>( overload, sol::types<RetVal>(), Args() );
}
doc_one_constructor()
template<typename RetVal , typename ... Args> std::vector< std::string > luna::detail::doc_one_constructor (std::function< RetVal(Args...)>)
Definition at line 169 of file catalua_luna.h.
{
    return doc_arg_list<Args...>();
}
References doc_arg_list().
Referenced by doc_constructors().
doc_value() [1/3]
template<typename Val > std::string luna::detail::doc_value (sol::types< sol::optional< Val > >)
Definition at line 142 of file catalua_luna.h.
{
    std::string ret = "Opt(";
    ret += doc_value( sol::types<Val>() );
    return ret + ")";
}
References doc_value(), and cata::hash64_detail::ret.
doc_value() [2/3]
template<typename ... Args> std::string luna::detail::doc_value (sol::types< std::tuple< Args... > >)
Definition at line 121 of file catalua_luna.h.
{
    std::string ret = "(";
    bool is_first = true;
    ( [&]() {
        if( is_first ) {
            is_first = false;
        } else {
            ret += ",";
        }
        ret += " ";
        ret += doc_value( sol::types<Args>() );
    }
    (), ... );
    if( !is_first ) {
        ret += " ";
    }
    return ret + ")";
}
References doc_value(), and cata::hash64_detail::ret.
doc_value() [3/3]
template<typename Val > std::string luna::detail::doc_value (sol::types< Val >)
Definition at line 150 of file catalua_luna.h.
{
    return doc_value_impl<Val>();
}
Referenced by doc_arg_list(), doc_bases(), doc_free(), doc_free_fx_impl2(), doc_member(), doc_member_fx_impl2(), and doc_value().
doc_value_impl()
template<typename Val > std::string luna::detail::doc_value_impl ()
Definition at line 101 of file catalua_luna.h.
{
    //static_assert(luna_traits<Val>::impl, "Type must implement luna_traits" );
    if constexpr( luna_traits<Val>::impl ) {
        return std::string( luna_traits<Val>::name );
    } else {
        using ValNoPtr = typename std::remove_pointer<Val>::type;
        using ValBare = remove_cv_ref_t<ValNoPtr>;
        if constexpr( luna_traits<ValBare>::impl ) {
            return std::string( luna_traits<ValBare>::name );
        } else {
            return std::string( "<cppval: " ) + typeid( ValBare ).name() + " >";
        }
    }
}
get_enum_doctable()
template<typename Class > sol::table luna::detail::get_enum_doctable (sol::state_view & lua) inline
Definition at line 235 of file catalua_luna.h.
{
    static_assert( detail::luna_traits<Class>::impl, "Type must implement luna_traits<T>" );
    sol::table gdt = get_global_doctable( lua );
    return gdt[detail::KEY_ENUMS][detail::luna_traits<Class>::name];
}
References get_global_doctable(), and KEY_ENUMS.
get_global_doctable()
sol::table luna::detail::get_global_doctable (sol::state_view & lua) inline
Definition at line 210 of file catalua_luna.h.
{
    sol::object obj = lua[detail::KEY_DOCTABLE];
    if( obj.valid() ) {
        return obj;
    } else {
        sol::table dt = lua.create_table();
        dt[detail::KEY_TYPES] = lua.create_table();
        dt[detail::KEY_ENUMS] = lua.create_table();
        dt[detail::KEY_LIBS] = lua.create_table();
        lua[detail::KEY_DOCTABLE] = dt;
        return dt;
    }
}
References KEY_DOCTABLE, KEY_ENUMS, KEY_LIBS, and KEY_TYPES.
Referenced by luna::begin_lib(), luna::finalize_enum(), get_enum_doctable(), get_type_doctable(), and luna::new_usertype().
get_type_doctable()
template<typename Class > sol::table luna::detail::get_type_doctable (sol::state_view & lua) inline
Definition at line 226 of file catalua_luna.h.
{
    static_assert( detail::luna_traits<Class>::impl, "Type must implement luna_traits<T>" );
    sol::table gdt = get_global_doctable( lua );
    return gdt[detail::KEY_TYPES][detail::luna_traits<Class>::name];
}
References get_global_doctable(), and KEY_TYPES.
make_type_member_doctable()
template<typename Key > sol::table luna::detail::make_type_member_doctable (sol::table type_dt, const Key & key)
Definition at line 354 of file catalua_luna.h.
{
    sol::state_view lua( type_dt.lua_state() );
    std::vector<sol::object> &members = type_dt[ detail::KEY_MEMBER ];
    sol::table member_dt = lua.create_table();
    member_dt[detail::KEY_MEMBER_NAME] = key;
    members.push_back( member_dt );
    return member_dt;
}
References KEY_MEMBER, and KEY_MEMBER_NAME.
Referenced by luna::set(), and luna::set_fx().
Variable Documentation
current_comment
std::string_view luna::detail::current_comment extern
Referenced by add_comment(), and luna::doc().
KEY_BASES
constexpr std::string_view luna::detail::KEY_BASES = "#bases" constexpr
Definition at line 59 of file catalua_luna.h.
Referenced by doc_bases().
KEY_CONSTRUCT
constexpr std::string_view luna::detail::KEY_CONSTRUCT = "#construct" constexpr
Definition at line 60 of file catalua_luna.h.
Referenced by doc_constructors().
KEY_DOCTABLE
constexpr std::string_view luna::detail::KEY_DOCTABLE = "catadoc" constexpr
Definition at line 58 of file catalua_luna.h.
Referenced by get_global_doctable().
KEY_ENUM_ENTRIES
constexpr std::string_view luna::detail::KEY_ENUM_ENTRIES = "entries" constexpr
Definition at line 56 of file catalua_luna.h.
Referenced by luna::finalize_enum().
KEY_ENUMS
constexpr std::string_view luna::detail::KEY_ENUMS = "#enums" constexpr
Definition at line 52 of file catalua_luna.h.
Referenced by luna::finalize_enum(), get_enum_doctable(), and get_global_doctable().
KEY_GET_TYPE
constexpr std::string_view luna::detail::KEY_GET_TYPE = "get_luna_type" constexpr
Definition at line 71 of file catalua_luna.h.
Referenced by luna::new_usertype().
KEY_LIB_COMMENT
constexpr std::string_view luna::detail::KEY_LIB_COMMENT = "lib_comment" constexpr
Definition at line 55 of file catalua_luna.h.
Referenced by luna::begin_lib().
KEY_LIB_IMPL
constexpr std::string_view luna::detail::KEY_LIB_IMPL = "#lib_impl" constexpr
Definition at line 54 of file catalua_luna.h.
Referenced by luna::begin_lib().
KEY_LIBS
constexpr std::string_view luna::detail::KEY_LIBS = "#libs" constexpr
Definition at line 53 of file catalua_luna.h.
Referenced by luna::begin_lib(), and get_global_doctable().
KEY_MEMBER
constexpr std::string_view luna::detail::KEY_MEMBER = "#member" constexpr
Definition at line 61 of file catalua_luna.h.
Referenced by luna::begin_lib(), make_type_member_doctable(), and luna::new_usertype().
KEY_MEMBER_ARGS
constexpr std::string_view luna::detail::KEY_MEMBER_ARGS = "args" constexpr
Definition at line 67 of file catalua_luna.h.
Referenced by doc_free_fx_impl2(), and doc_member_fx_impl2().
KEY_MEMBER_COMMENT
constexpr std::string_view luna::detail::KEY_MEMBER_COMMENT = "comment" constexpr
Definition at line 63 of file catalua_luna.h.
Referenced by doc_free(), doc_free_fx_impl(), doc_member(), and doc_member_fx_impl().
KEY_MEMBER_NAME
constexpr std::string_view luna::detail::KEY_MEMBER_NAME = "name" constexpr
Definition at line 70 of file catalua_luna.h.
Referenced by make_type_member_doctable().
KEY_MEMBER_OVERLOADS
constexpr std::string_view luna::detail::KEY_MEMBER_OVERLOADS = "overloads" constexpr
Definition at line 68 of file catalua_luna.h.
Referenced by doc_free_fx_impl(), and doc_member_fx_impl().
KEY_MEMBER_RETVAL
constexpr std::string_view luna::detail::KEY_MEMBER_RETVAL = "retval" constexpr
Definition at line 69 of file catalua_luna.h.
Referenced by doc_free_fx_impl2(), and doc_member_fx_impl2().
KEY_MEMBER_TYPE
constexpr std::string_view luna::detail::KEY_MEMBER_TYPE = "type" constexpr
Definition at line 62 of file catalua_luna.h.
Referenced by doc_free(), doc_free_fx_impl(), doc_member(), and doc_member_fx_impl().
KEY_MEMBER_VARIABLE_HAS_VALUE
constexpr std::string_view luna::detail::KEY_MEMBER_VARIABLE_HAS_VALUE = "hasval" constexpr
Definition at line 65 of file catalua_luna.h.
Referenced by doc_free().
KEY_MEMBER_VARIABLE_TYPE
constexpr std::string_view luna::detail::KEY_MEMBER_VARIABLE_TYPE = "vartype" constexpr
Definition at line 64 of file catalua_luna.h.
Referenced by doc_free(), and doc_member().
KEY_MEMBER_VARIABLE_VALUE
constexpr std::string_view luna::detail::KEY_MEMBER_VARIABLE_VALUE = "varval" constexpr
Definition at line 66 of file catalua_luna.h.
Referenced by doc_free().
KEY_TYPE_IMPL
constexpr std::string_view luna::detail::KEY_TYPE_IMPL = "#type_impl" constexpr
Definition at line 57 of file catalua_luna.h.
Referenced by luna::new_usertype().
KEY_TYPES
constexpr std::string_view luna::detail::KEY_TYPES = "#types" constexpr
Definition at line 51 of file catalua_luna.h.
Referenced by get_global_doctable(), get_type_doctable(), and luna::new_usertype().
KEY_USERTYPE_COMMENT
constexpr std::string_view luna::detail::KEY_USERTYPE_COMMENT = "type_comment" constexpr
Definition at line 72 of file catalua_luna.h.
Referenced by luna::new_usertype().
MEMBER_IS_CONST_FUNC
constexpr std::string_view luna::detail::MEMBER_IS_CONST_FUNC = "const_func" constexpr
Definition at line 76 of file catalua_luna.h.
MEMBER_IS_FUNC
constexpr std::string_view luna::detail::MEMBER_IS_FUNC = "func" constexpr
Definition at line 75 of file catalua_luna.h.
Referenced by doc_free_fx_impl(), and doc_member_fx_impl().
MEMBER_IS_VAR
constexpr std::string_view luna::detail::MEMBER_IS_VAR = "var" constexpr
Definition at line 74 of file catalua_luna.h.
Referenced by doc_free(), and doc_member().