Cataclysm BN: explosion_handler::explosion_funcs Namespace Reference
explosion_handler::explosion_funcs Namespace Reference
Functions
void regular (const queued_explosion &qe)
void flashbang (const queued_explosion &qe)
void resonance_cascade (const queued_explosion &qe)
void shockwave (const queued_explosion &qe)
Function Documentation
flashbang()
void explosion_handler::explosion_funcs::flashbang (const queued_explosion & qe)
Definition at line 1561 of file explosion.cpp.
{
    const tripoint &p = qe.pos;
    map &here = get_map();
    draw_explosion( p, 8, c_white, qe.graphics_name );
    int dist = rl_dist( g->u.pos(), p );
    if( dist <= 8 && qe.affects_player ) {
        if( !g->u.has_bionic( bio_ears ) && !g->u.is_wearing( itype_rm13_armor_on ) ) {
            g->u.add_effect( effect_deaf, time_duration::from_turns( 40 - dist * 4 ) );
        }
        if( here.sees( g->u.pos(), p, 8 ) ) {
            int flash_mod = 0;
            if( g->u.has_trait( trait_PER_SLIME ) ) {
                if( one_in( 2 ) ) {
                    flash_mod = 3; // Yay, you weren't looking!
                }
            } else if( g->u.has_trait( trait_PER_SLIME_OK ) ) {
                flash_mod = 8; // Just retract those and extrude fresh eyes
            } else if( g->u.has_bionic( bio_sunglasses ) ||
                       g->u.is_wearing( itype_rm13_armor_on ) ) {
                flash_mod = 6;
            } else if( g->u.worn_with_flag( flag_BLIND ) || g->u.worn_with_flag( flag_FLASH_PROTECTION ) ) {
                flash_mod = 3; // Not really proper flash protection, but better than nothing
            }
            g->u.add_env_effect( effect_blind, bp_eyes, ( 12 - flash_mod - dist ) / 2,
                                 time_duration::from_turns( 10 - dist ) );
        }
    }
    for( monster &critter : g->all_monsters() ) {
        if( critter.type->in_species( ROBOT ) ) {
            continue;
        }
        // TODO: can the following code be called for all types of creatures
        dist = rl_dist( critter.pos(), p );
        if( dist <= 8 ) {
            if( dist <= 4 ) {
                critter.add_effect( effect_stunned, time_duration::from_turns( 10 - dist ) );
            }
            if( critter.has_flag( MF_SEES ) && here.sees( critter.pos(), p, 8 ) ) {
                critter.add_effect( effect_blind, time_duration::from_turns( 18 - dist ) );
            }
            if( critter.has_flag( MF_HEARS ) ) {
                critter.add_effect( effect_deaf, time_duration::from_turns( 60 - dist * 4 ) );
            }
        }
    }
    sounds::sound( p, 12, sounds::sound_t::combat, _( "a huge boom!" ), false, "misc", "flashbang" );
    // TODO: Blind/deafen NPC
}
References _, explosion_handler::queued_explosion::affects_player, bio_ears, bio_sunglasses, bp_eyes, c_white, sounds::combat, explosion_handler::draw_explosion(), effect_blind, effect_deaf, effect_stunned, flag_BLIND(), flag_FLASH_PROTECTION(), time_duration::from_turns(), g, get_map(), explosion_handler::queued_explosion::graphics_name, itype_rm13_armor_on, MF_HEARS, MF_SEES, one_in(), explosion_handler::queued_explosion::pos, rl_dist(), ROBOT, map::sees(), sounds::sound(), trait_PER_SLIME, and trait_PER_SLIME_OK.
regular()
void explosion_handler::explosion_funcs::regular (const queued_explosion & qe)
Definition at line 1466 of file explosion.cpp.
{
    const tripoint &p = qe.pos;
    const explosion_data &ex = qe.exp_data;
    const int noise = ex.damage / explosion_handler::power_to_dmg_mult * ( ex.fire ? 2 : 10 );
    if( noise >= 30 ) {
        sounds::sound( p, noise, sounds::sound_t::combat, _( "a huge explosion!" ), false, "explosion",
                       "huge" );
    } else if( noise >= 4 ) {
        sounds::sound( p, noise, sounds::sound_t::combat, _( "an explosion!" ), false, "explosion",
                       "default" );
    } else if( noise > 0 ) {
        sounds::sound( p, 3, sounds::sound_t::combat, _( "a loud pop!" ), false, "explosion", "small" );
    }
    std::map<const Creature *, int> damaged_by_blast;
    std::map<const Creature *, int> damaged_by_shrapnel;
    auto &shr = ex.fragment;
    if( get_option<bool>( "OLD_EXPLOSIONS" ) ) {
        if( shr ) {
            damaged_by_shrapnel = legacy_shrapnel( p, shr.value(), qe.source );
        }
        damaged_by_blast = legacy_blast( p, ex.damage, ex.radius, ex.fire, qe.source );
    } else {
        ExplosionProcess process( p, ex.damage, ex.radius, shr, ex.fire, std::make_optional( qe.source ) );
        process.run();
        damaged_by_blast = process.get_blasted();
        damaged_by_shrapnel = process.get_shrapneled();
    }
    // Not the cleanest way to do it
    std::map<const Creature *, int> total_damaged;
    for( const auto &pr : damaged_by_blast ) {
        total_damaged[pr.first] += pr.second;
    }
    for( const auto &pr : damaged_by_shrapnel ) {
        total_damaged[pr.first] += pr.second;
    }
    const auto print_damage = [&]( const std::pair<const Creature *, int> &pr,
    std::function<bool( const Creature & )> predicate ) {
        if( predicate( *pr.first ) && g->u.sees( *pr.first ) ) {
            const Creature *critter = pr.first;
            bool blasted = damaged_by_blast.find( critter ) != damaged_by_blast.end();
            bool shredded = damaged_by_shrapnel.find( critter ) != damaged_by_shrapnel.end();
            std::string cause_description = ( blasted && shredded ) ? _( "the explosion and shrapnel" ) :
                                            blasted ? _( "the explosion" ) :
                                            _( "the shrapnel" );
            std::string damage_description = ( pr.second > 0 ) ?
                                             string_format( _( "taking %d damage" ), pr.second ) :
                                             _( "but takes no damage" );
            if( critter->is_player() ) {
                add_msg( _( "You are hit by %s, %s." ),
                         cause_description, damage_description );
            } else if( critter->is_npc() ) {
                critter->add_msg_if_npc(
                    _( "<npcname> is hit by %s, %s." ),
                    cause_description, damage_description );
            } else {
                add_msg( _( "%s is hit by %s, %s." ),
                         critter->disp_name( false, true ), cause_description, damage_description );
            }
        }
    };
    // TODO: Clean this up, without affecting the results
    for( const auto &pr : total_damaged ) {
        print_damage( pr, []( const Creature & c ) {
            return c.is_monster();
        } );
    }
    for( const auto &pr : total_damaged ) {
        print_damage( pr, []( const Creature & c ) {
            return c.is_npc();
        } );
    }
    for( const auto &pr : total_damaged ) {
        print_damage( pr, []( const Creature & c ) {
            return c.is_avatar();
        } );
    }
}
References _, add_msg(), Creature::add_msg_if_npc(), c, sounds::combat, explosion_data::damage, Creature::disp_name(), explosion_handler::queued_explosion::exp_data, explosion_data::fire, explosion_data::fragment, g, explosion_handler::ExplosionProcess::get_blasted(), explosion_handler::ExplosionProcess::get_shrapneled(), Creature::is_npc(), Creature::is_player(), explosion_handler::legacy_blast(), explosion_handler::legacy_shrapnel(), explosion_handler::queued_explosion::pos, explosion_handler::power_to_dmg_mult, explosion_data::radius, explosion_handler::ExplosionProcess::run(), sounds::sound(), explosion_handler::queued_explosion::source, and string_format().
Referenced by explosion_handler::explosion_queue::execute(), and item::ideal_ranged_dps().
resonance_cascade()
void explosion_handler::explosion_funcs::resonance_cascade (const queued_explosion & qe)
Definition at line 1804 of file explosion.cpp.
{
    map &here = get_map();
    const tripoint &p = qe.pos;
    const time_duration maxglow = time_duration::from_turns( 100 - 5 * trig_dist( p, g->u.pos() ) );
    if( maxglow > 0_turns ) {
        const time_duration minglow = std::max( 0_turns, time_duration::from_turns( 60 - 5 * trig_dist( p,
                                                g->u.pos() ) ) );
        g->u.add_effect( effect_teleglow, rng( minglow, maxglow ) * 100 );
    }
    constexpr half_open_rectangle<point> map_bounds( point_zero, point( MAPSIZE_X, MAPSIZE_Y ) );
    constexpr point cascade_reach( 8, 8 );
    point start = clamp( p.xy() - cascade_reach, map_bounds );
    point end = clamp( p.xy() + cascade_reach, map_bounds );
    std::vector<int> rolls;
    tripoint dest = p;
    for( dest.y = start.y; dest.y < end.y; dest.y++ ) {
        for( dest.x = start.x; dest.x < end.x; dest.x++ ) {
            switch( rng( 0, 80 ) ) {
                case 1:
                case 2:
                    emp_blast( dest );
                    break;
                case 3:
                case 4:
                case 5:
                    for( int k = -1; k <= 1; k++ ) {
                        for( int l = -1; l <= 1; l++ ) {
                            field_type_id type = fd_null;
                            switch( rng( 1, 7 ) ) {
                                case 1:
                                    type = fd_blood;
                                    break;
                                case 2:
                                    type = fd_bile;
                                    break;
                                case 3:
                                case 4:
                                    type = fd_slime;
                                    break;
                                case 5:
                                    type = fd_fire;
                                    break;
                                case 6:
                                case 7:
                                    type = fd_nuke_gas;
                                    break;
                            }
                            if( !one_in( 3 ) ) {
                                here.add_field( dest + point( k, l ), type, 3 );
                            }
                        }
                    }
                    break;
                case  6:
                case  7:
                case  8:
                case  9:
                case 10:
                    here.trap_set( dest, tr_portal );
                    break;
                case 11:
                case 12:
                    here.trap_set( dest, tr_goo );
                    break;
                case 13:
                case 14:
                case 15: {
                    MonsterGroupResult spawn_details = MonsterGroupManager::GetResultFromGroup( GROUP_NETHER );
                    g->place_critter_at( spawn_details.name, dest );
                    break;
                }
                case 16:
                case 17:
                case 18:
                    here.destroy( dest );
                    break;
                case 19: {
                    explosion_data ex;
                    ex.radius = 1;
                    ex.damage = rng( 1, 10 );
                    ex.fire = one_in( 4 );
                    explosion( dest, ex, qe.source );
                    break;
                }
                default:
                    break;
            }
        }
    }
}
References map::add_field(), clamp(), explosion_data::damage, map::destroy(), effect_teleglow, explosion_handler::emp_blast(), explosion_handler::explosion(), fd_bile, fd_blood, fd_fire, fd_nuke_gas, fd_null, fd_slime, explosion_data::fire, time_duration::from_turns(), g, get_map(), MonsterGroupManager::GetResultFromGroup(), GROUP_NETHER, MAPSIZE_X, MAPSIZE_Y, MonsterGroupResult::name, one_in(), point_zero, explosion_handler::queued_explosion::pos, explosion_data::radius, rng(), explosion_handler::queued_explosion::source, tr_goo, tr_portal, map::trap_set(), trig_dist(), point::x, tripoint::x, tripoint::xy(), point::y, and tripoint::y.
shockwave()
void explosion_handler::explosion_funcs::shockwave (const queued_explosion & qe)
Definition at line 1621 of file explosion.cpp.
{
    const tripoint &p = qe.pos;
    const shockwave_data &sw = qe.swave_data;
    draw_explosion( p, sw.radius, c_blue, qe.graphics_name );
    sounds::sound( p, sw.force * sw.force * sw.dam_mult / 2, sounds::sound_t::combat, _( "Crack!" ),
                   false,
                   "misc", "shockwave" );
    for( monster &critter : g->all_monsters() ) {
        if( critter.posz() != p.z ) {
            continue;
        }
        if( rl_dist( critter.pos(), p ) <= sw.radius ) {
            add_msg( _( "%s is caught in the shockwave!" ), critter.name() );
            g->knockback( p, critter.pos(), sw.force, sw.stun, sw.dam_mult, qe.source );
        }
    }
    // TODO: combine the two loops and the case for g->u using all_creatures()
    for( npc &guy : g->all_npcs() ) {
        if( guy.posz() != p.z ) {
            continue;
        }
        if( rl_dist( guy.pos(), p ) <= sw.radius ) {
            add_msg( _( "%s is caught in the shockwave!" ), guy.name );
            g->knockback( p, guy.pos(), sw.force, sw.stun, sw.dam_mult, qe.source );
        }
    }
    if( rl_dist( g->u.pos(), p ) <= sw.radius && sw.affects_player &&
        ( !g->u.has_trait( trait_LEG_TENT_BRACE ) || g->u.footwear_factor() == 1 ||
          ( g->u.footwear_factor() == .5 && one_in( 2 ) ) ) ) {
        add_msg( m_bad, _( "You're caught in the shockwave!" ) );
        g->knockback( p, g->u.pos(), sw.force, sw.stun, sw.dam_mult, qe.source );
    }
}
References _, add_msg(), shockwave_data::affects_player, c_blue, sounds::combat, shockwave_data::dam_mult, explosion_handler::draw_explosion(), shockwave_data::force, g, explosion_handler::queued_explosion::graphics_name, m_bad, one_in(), explosion_handler::queued_explosion::pos, shockwave_data::radius, rl_dist(), sounds::sound(), explosion_handler::queued_explosion::source, shockwave_data::stun, explosion_handler::queued_explosion::swave_data, trait_LEG_TENT_BRACE, and tripoint::z.