Cataclysm BN: npc_ai Namespace Reference
npc_ai Namespace Reference
Functions
double wielded_value (const Character &who)
Evaluate wielded weapon's ideal value.
double weapon_value (const Character &who, const item &weap, int ammo)
Evaluate item as weapon (melee or gun)
double gun_value (const Character &who, const item &weap, int ammo)
Evaluates item as a gun.
std::pair< gun_mode_id, gun_mode > best_mode_for_range (const Character &who, const item &firing, int dist)
Chooses best gun_mode for range.
double melee_value (const Character &who, const item &weap)
Evaluate item as a melee weapon.
double unarmed_value (const Character &who)
Evaluate unarmed melee value.
Function Documentation
best_mode_for_range()
std::pair< gun_mode_id, gun_mode > npc_ai::best_mode_for_range (const Character & who, const item & firing, int dist)
Chooses best gun_mode for range.
Definition at line 1967 of file ranged.cpp.
{
    std::pair<gun_mode_id, gun_mode> res = std::make_pair( gun_mode_id(), gun_mode() );
    int shots = who.is_wielding( firing ) ? character_funcs::ammo_count_for( who,
                firing ) : item_funcs::shots_remaining( who, firing );
    if( !firing.is_gun() || shots == 0 ) {
        return res;
    }
    int min_recoil = MAX_RECOIL;
    min_recoil = ranged::get_most_accurate_sight( who, firing );
    int range = static_cast<const npc *>( &who )->confident_shoot_range( firing, min_recoil );
    if( dist > range ) {
        return res;
    }
    const auto gun_mode_cmp = []( const std::pair<gun_mode_id, gun_mode> lhs,
    const std::pair<gun_mode_id, gun_mode> rhs ) {
        return lhs.second.qty < rhs.second.qty;
    };
    const std::map<gun_mode_id, gun_mode> &to_add = firing.gun_all_modes();
    std::vector<std::pair<gun_mode_id, gun_mode>> modes;
    std::copy( to_add.begin(), to_add.end(), std::back_inserter( modes ) );
    erase_if( modes, [&]( const std::pair<gun_mode_id, gun_mode> &e ) {
        const auto &m = e.second;
        return m.melee() || !who.can_use( *m.target ) || m.flags.count( "NPC_AVOID" ) || shots < m.qty ||
               ( dist > 0 && static_cast<const npc *>( &who )->confident_gun_mode_range( m, min_recoil ) < dist );
    } );
    if( modes.empty() ) {
        return res;
    }
    const auto g_mode = std::max_element( modes.begin(), modes.end(), gun_mode_cmp );
    res = *g_mode;
    return res;
}
References character_funcs::ammo_count_for(), Character::can_use(), npc::confident_gun_mode_range(), erase_if(), ranged::get_most_accurate_sight(), item::gun_all_modes(), item::is_gun(), Character::is_wielding(), MAX_RECOIL, range, and item_funcs::shots_remaining().
Referenced by npc::check_or_use_weapon_cbm(), gun_value(), and npc::wield_better_weapon().
gun_value()
double npc_ai::gun_value (const Character & who, const item & weap, int ammo)
Evaluates item as a gun.
Definition at line 2009 of file ranged.cpp.
{
    // TODO: Mods
    // TODO: Allow using a specified type of ammo rather than default or current
    if( !weap.type->gun ) {
        add_msg( m_debug, "%s is not a gun, gun_value set to 0", weap.type->get_id().str() );
        return 0.0;
    }
    if( ammo <= 0 ) {
        add_msg( m_debug, "%s has no ammo, gun_value set to 0", weap.type->get_id().str() );
        return 0.0;
    }
    item ideal_weapon = weap;
    if( !ideal_weapon.ammo_default().is_null() ) {
        ideal_weapon.ammo_set( ideal_weapon.ammo_default(), -1 );
    }
    auto [mode_id, mode_] = npc_ai::best_mode_for_range( who, ideal_weapon, -1 );
    // Doesn't use calculate_dispersion because that requires a map
    // TODO: Turn this into a common function.
    dispersion_sources mode_disp = ranged::get_weapon_dispersion( who, ideal_weapon );
    double total_dispersion = mode_disp.max();
    if( ideal_weapon.ammo_current() ) {
        total_dispersion += ideal_weapon.ammo_current()->ammo->dispersion;
    }
    // Necessary so that ideal_ranged_dps will include the reload cost in calc.
    ideal_weapon.ammo_unset();
    double dps = ideal_weapon.ideal_ranged_dps( who, mode_ );
    // "Medium range" below means 9 tiles, "short range" means 4
    // Those are guarantees (assuming maximum time spent aiming)
    static const std::vector<std::pair<float, float>> dispersion_thresholds = {
        {
            // Headshots all the time
            { 0.0f, 2.0f },
            // Critical at medium range
            { 100.0f, 1.8f },
            // Critical at short range or good hit at medium
            { 200.0f, 1.6f },
            // OK hits at medium
            { 300.0f, 1.45f },
            // Point blank headshots
            { 450.0f, 1.30f },
            // OK hits at short
            { 700.0f, 1.15f },
            // Glances at medium, criticals at point blank
            { 1000.0f, 1.0f },
            // Nothing guaranteed, pure gamble
            { 2000.0f, 0.1f },
        }
    };
    float dispersion_factor = multi_lerp( dispersion_thresholds, total_dispersion );
    double gun_value = dps * dispersion_factor;
    add_msg( m_debug, "%s as gun: %.1f total, %.1f dispersion, %.1f dps",
             weap.type->get_id().str(), gun_value, dispersion_factor, dps );
    return std::max( 0.0, gun_value );
}
References add_msg(), itype::ammo, item::ammo_current(), item::ammo_default(), item::ammo_set(), item::ammo_unset(), best_mode_for_range(), itype::get_id(), ranged::get_weapon_dispersion(), itype::gun, gun_value(), item::ideal_ranged_dps(), string_id< T >::is_null(), m_debug, dispersion_sources::max(), multi_lerp(), string_id< T >::str(), and item::type.
Referenced by gun_value(), and weapon_value().
melee_value()
double npc_ai::melee_value (const Character & who, const item & weap)
Evaluate item as a melee weapon.
Definition at line 2348 of file melee.cpp.
{
    // start with average effective dps against a range of enemies
    double my_value = weap.average_dps( *who.as_player() );
    float reach = weap.reach_range( who );
    // value reach weapons more
    if( reach > 1.0f ) {
        my_value *= 1.0f + 0.5f * ( std::sqrt( reach ) - 1.0f );
    }
    // value polearms less to account for the trickiness of keeping the right range
    if( weap.has_flag( "POLEARM" ) ) {
        my_value *= 0.8;
    }
    // value style weapons more
    if( !who.martial_arts_data->enumerate_known_styles( weap.type->get_id() ).empty() ) {
        my_value *= 1.5;
    }
    add_msg( m_debug, "%s as melee: %.1f", weap.type->get_id().str(), my_value );
    return std::max( 0.0, my_value );
}
References add_msg(), Creature::as_player(), item::average_dps(), itype::get_id(), item::has_flag(), m_debug, Character::martial_arts_data, item::reach_range(), string_id< T >::str(), and item::type.
Referenced by npc::average_damage_dealt(), unarmed_value(), weapon_value(), and npc::wield_better_weapon().
unarmed_value()
double npc_ai::unarmed_value (const Character & who)
Evaluate unarmed melee value.
Definition at line 2373 of file melee.cpp.
{
    // TODO: Martial arts
    return melee_value( who, item() );
}
References melee_value().
weapon_value()
double npc_ai::weapon_value (const Character & who, const item & weap, int ammo)
Evaluate item as weapon (melee or gun)
Definition at line 2335 of file melee.cpp.
{
    const double val_gun = gun_value( who, weap, ammo );
    const double val_melee = melee_value( who, weap );
    const double more = std::max( val_gun, val_melee );
    const double less = std::min( val_gun, val_melee );
    // A small bonus for guns you can also use to hit stuff with (bayonets etc.)
    const double my_val = ( more + ( less / 2.0 ) );
    add_msg( m_debug, "%s (%ld ammo) sum value: %.1f", weap.type->get_id().str(), ammo, my_val );
    return my_val;
}
References add_msg(), itype::get_id(), gun_value(), m_debug, melee_value(), detail::digits::more, string_id< T >::str(), and item::type.
Referenced by give_item_to(), npc::value(), and wielded_value().
wielded_value()
double npc_ai::wielded_value (const Character & who)
Evaluate wielded weapon's ideal value.
Definition at line 2319 of file melee.cpp.
{
    const double cached = *who.get_npc_ai_info_cache( npc_ai_info::ideal_weapon_value );
    if( cached >= 0.0 ) {
        add_msg( m_debug, "%s ideal sum value: %.1f", who.primary_weapon().type->get_id().str(), cached );
        return cached;
    }
    item ideal_weapon = who.primary_weapon();
    if( !ideal_weapon.ammo_default().is_null() ) {
        ideal_weapon.ammo_set( ideal_weapon.ammo_default(), -1 );
    }
    double weap_val = weapon_value( who, ideal_weapon, ideal_weapon.ammo_capacity() );
    who.set_npc_ai_info_cache( npc_ai_info::ideal_weapon_value, weap_val );
    return weap_val;
}
References add_msg(), item::ammo_capacity(), item::ammo_default(), item::ammo_set(), itype::get_id(), Character::get_npc_ai_info_cache(), ideal_weapon_value, string_id< T >::is_null(), m_debug, Character::primary_weapon(), Character::set_npc_ai_info_cache(), string_id< T >::str(), item::type, and weapon_value().
Referenced by npc::character_danger(), npc::decide_needs(), npc::form_opinion(), rate_critter(), npc::regen_ai_cache(), and npc::value().