Cataclysm BN: explosion_handler Namespace Reference
explosion_handler Namespace Reference
Namespaces
namespace explosion_funcs
Classes
class explosion_queue
class ExplosionEvent
class ExplosionProcess
struct queued_explosion
Enumerations
enum class ExplosionType { Regular , Flashbang , ResonanceCascade , Shockwave }
Functions
void draw_explosion (const tripoint &p, int radius, const nc_color &col, const std::string &exp_name)
void draw_custom_explosion (const tripoint &p, const std::map< tripoint, nc_color > &area, const std::string &exp_name)
void explosion (const tripoint &p, Creature *source, float power, float factor=0.8f, bool fire=false, int legacy_casing_mass=0, float legacy_frag_mass=0.05)
Legacy explosion function.
void explosion (const tripoint &p, const explosion_data &ex, Creature *source)
static std::map< const Creature *, int > legacy_shrapnel (const tripoint &src, const projectile &fragment, Creature *source)
static std::map< const Creature *, int > legacy_blast (const tripoint &p, const float power, const float radius, const bool fire, Creature *source)
void flashbang (const tripoint &p, bool player_immune, const std::string &exp_name)
Triggers a flashbang explosion at p.
void shockwave (const tripoint &p, const shockwave_data &sw, const std::string &exp_name, Creature *source)
Shockwave applies knockback with given parameters to all targets within radius of p.
void scrambler_blast (const tripoint &p)
Triggers a scrambler blast at p.
void emp_blast (const tripoint &p)
Triggers an EMP blast at p.
void resonance_cascade (const tripoint &p)
Triggers a resonance cascade at p.
projectile shrapnel_from_legacy (int power, float blast_radius)
float blast_radius_from_legacy (int power, float distance_factor)
explosion_queue & get_explosion_queue ()
Variables
constexpr float power_to_dmg_mult = 2.0f / 15.0f
Enumeration Type Documentation
ExplosionType
enum class explosion_handler::ExplosionType strong
Enumerator
Regular
Flashbang
ResonanceCascade
Shockwave
Definition at line 14 of file explosion_queue.h.
{
    Regular,
    Flashbang,
    ResonanceCascade,
    Shockwave
};
Function Documentation
blast_radius_from_legacy()
float explosion_handler::blast_radius_from_legacy (int power, float distance_factor)
Definition at line 1914 of file explosion.cpp.
{
    return std::pow( power * power_to_dmg_mult, ( 1.0 / 4.0 ) ) *
           ( std::log( 0.75f ) / std::log( distance_factor ) );
}
References power_to_dmg_mult.
Referenced by explosion(), and load_explosion_data().
draw_custom_explosion()
void explosion_handler::draw_custom_explosion (const tripoint & p, const std::map< tripoint, nc_color > & area, const std::string & exp_name)
Definition at line 310 of file animation.cpp.
{
#if !defined(TILES)
    ( void )exp_name;
#endif
    if( test_mode ) {
        // avoid segfault from null tilecontext in tests
        return;
    }
    constexpr explosion_neighbors all_neighbors = N_NORTH | N_SOUTH | N_WEST | N_EAST;
    // We will "shell" the explosion area
    // Each phase will strip a single layer of points
    // A layer contains all points that have less than 4 neighbors in cardinal directions
    // Layers will first be generated, then drawn in inverse order
    // Start by getting rid of everything except current z-level
    std::map<tripoint, explosion_tile> neighbors;
#if defined(TILES)
    if( !use_tiles ) {
        for( const auto &pr : all_area ) {
            const tripoint relative_point = relative_view_pos( g->u, pr.first );
            if( relative_point.z == 0 ) {
                neighbors[pr.first] = explosion_tile{ N_NO_NEIGHBORS, pr.second };
            }
        }
    } else {
        // In tiles mode, the coordinates have to be absolute
        const tripoint view_center = relative_view_pos( g->u, g->u.pos() );
        for( const auto &pr : all_area ) {
            // Relative point is only used for z level check
            const tripoint relative_point = relative_view_pos( g->u, pr.first );
            if( relative_point.z == view_center.z ) {
                neighbors[pr.first] = explosion_tile{ N_NO_NEIGHBORS, pr.second };
            }
        }
    }
#else
    for( const auto &pr : all_area ) {
        const tripoint relative_point = relative_view_pos( g->u, pr.first );
        if( relative_point.z == 0 ) {
            neighbors[pr.first] = explosion_tile{ N_NO_NEIGHBORS, pr.second };
        }
    }
#endif
    // Searches for a neighbor, sets the neighborhood flag on current point and on the neighbor
    const auto set_neighbors = [&]( const tripoint & pos,
                                    explosion_neighbors & ngh,
                                    explosion_neighbors here,
    explosion_neighbors there ) {
        if( ( ngh & here ) == N_NO_NEIGHBORS ) {
            auto other = neighbors.find( pos );
            if( other != neighbors.end() ) {
                ngh = ngh | here;
                other->second.neighborhood = other->second.neighborhood | there;
            }
        }
    };
    // If the point we are about to remove has a neighbor in a given direction
    // unset that neighbor's flag that our current point is its neighbor
    const auto unset_neighbor = [&]( const tripoint & pos,
                                     const explosion_neighbors ngh,
                                     explosion_neighbors here,
    explosion_neighbors there ) {
        if( ( ngh & here ) != N_NO_NEIGHBORS ) {
            auto other = neighbors.find( pos );
            if( other != neighbors.end() ) {
                other->second.neighborhood = ( other->second.neighborhood | there ) ^ there;
            }
        }
    };
    // Find all neighborhoods
    for( auto &pr : neighbors ) {
        const tripoint &pt = pr.first;
        explosion_neighbors &ngh = pr.second.neighborhood;
        set_neighbors( pt + point_west, ngh, N_WEST, N_EAST );
        set_neighbors( pt + point_east, ngh, N_EAST, N_WEST );
        set_neighbors( pt + point_north, ngh, N_NORTH, N_SOUTH );
        set_neighbors( pt + point_south, ngh, N_SOUTH, N_NORTH );
    }
    // We need to save the layers because we will draw them in reverse order
    std::list< std::map<tripoint, explosion_tile> > layers;
    while( !neighbors.empty() ) {
        std::map<tripoint, explosion_tile> layer;
        bool changed = false;
        // Find a layer that can be drawn
        for( const auto &pr : neighbors ) {
            if( pr.second.neighborhood != all_neighbors ) {
                changed = true;
                layer.insert( pr );
            }
        }
        if( !changed ) {
            // An error, but a minor one - let it slide
            return;
        }
        // Remove the layer from the area to process
        for( const auto &pr : layer ) {
            const tripoint &pt = pr.first;
            const explosion_neighbors ngh = pr.second.neighborhood;
            unset_neighbor( pt + point_west, ngh, N_WEST, N_EAST );
            unset_neighbor( pt + point_east, ngh, N_EAST, N_WEST );
            unset_neighbor( pt + point_north, ngh, N_NORTH, N_SOUTH );
            unset_neighbor( pt + point_south, ngh, N_SOUTH, N_NORTH );
            neighbors.erase( pr.first );
        }
        layers.push_front( std::move( layer ) );
    }
#if defined(TILES)
    if( !use_tiles ) {
        draw_custom_explosion_curses( *g, layers );
        return;
    }
    explosion_animation anim;
    // We need to draw all explosions up to now
    std::map<tripoint, explosion_tile> combined_layer;
    shared_ptr_fast<game::draw_callback_t> explosion_cb =
    make_shared_fast<game::draw_callback_t>( [&]() {
        tilecontext->init_custom_explosion_layer( combined_layer, exp_name );
    } );
    g->add_draw_callback( explosion_cb );
    for( const auto &layer : layers ) {
        combined_layer.insert( layer.begin(), layer.end() );
        if( is_layer_visible( layer ) ) {
            anim.progress();
        }
    }
    tilecontext->void_custom_explosion();
#else
    draw_custom_explosion_curses( *g, layers );
#endif
}
References anonymous_namespace{animation.cpp}::draw_custom_explosion_curses(), g, anonymous_namespace{animation.cpp}::is_layer_visible(), avatar_action::move(), N_EAST, N_NO_NEIGHBORS, N_NORTH, N_SOUTH, N_WEST, other, point_east, point_north, point_south, point_west, anonymous_namespace{animation.cpp}::relative_view_pos(), test_mode, use_tiles, and tripoint::z.
Referenced by legacy_blast(), legacy_shrapnel(), and spell_effect_area().
draw_explosion()
void explosion_handler::draw_explosion (const tripoint & p, int radius, const nc_color & col, const std::string & exp_name)
Definition at line 303 of file animation.cpp.
{
    draw_explosion_curses( *g, p, r, col );
}
References anonymous_namespace{animation.cpp}::draw_explosion_curses(), and g.
Referenced by explosion_handler::explosion_funcs::flashbang(), iuse::granade_act(), explosion_handler::explosion_funcs::shockwave(), and explosion_iuse::trigger_explosion().
emp_blast()
void explosion_handler::emp_blast (const tripoint & p)
Triggers an EMP blast at p.
Definition at line 1671 of file explosion.cpp.
{
    map &here = get_map();
    Character &u = get_player_character();
    const bool sight = u.sees( p );
    if( here.has_flag( "CONSOLE", p ) ) {
        if( sight ) {
            add_msg( _( "The %s is rendered non-functional!" ), here.tername( p ) );
        }
        here.ter_set( p, t_console_broken );
        return;
    }
    // TODO: More terrain effects.
    if( here.ter( p ) == t_card_science || here.ter( p ) == t_card_military ||
        here.ter( p ) == t_card_industrial ) {
        int rn = rng( 1, 100 );
        if( rn > 92 || rn < 40 ) {
            if( sight ) {
                add_msg( _( "The card reader is rendered non-functional." ) );
            }
            here.ter_set( p, t_card_reader_broken );
        }
        if( rn > 80 ) {
            if( sight ) {
                add_msg( _( "The nearby doors slide open!" ) );
            }
            for( int i = -3; i <= 3; i++ ) {
                for( int j = -3; j <= 3; j++ ) {
                    tripoint p2 = p + tripoint( i, j, 0 );
                    if( here.ter( p2 ) == t_door_metal_locked ) {
                        here.ter_set( p2, t_floor );
                    }
                }
            }
        }
        if( rn >= 40 && rn <= 80 ) {
            if( sight ) {
                add_msg( _( "Nothing happens." ) );
            }
        }
    }
    if( monster *const mon_ptr = g->critter_at<monster>( p ) ) {
        monster &critter = *mon_ptr;
        if( critter.has_flag( MF_ELECTRONIC ) ) {
            int deact_chance = 0;
            const auto mon_item_id = critter.type->revert_to_itype;
            switch( critter.get_size() ) {
                case MS_TINY:
                    deact_chance = 6;
                    break;
                case MS_SMALL:
                    deact_chance = 3;
                    break;
                default:
                    // Currently not used, I have no idea what chances bigger bots should have,
                    // Maybe export this to json?
                    break;
            }
            if( !mon_item_id.is_empty() && deact_chance != 0 && one_in( deact_chance ) ) {
                if( sight ) {
                    add_msg( _( "The %s beeps erratically and deactivates!" ), critter.name() );
                }
                here.add_item_or_charges( p, critter.to_item() );
                for( auto &ammodef : critter.ammo ) {
                    if( ammodef.second > 0 ) {
                        here.spawn_item( p, ammodef.first, 1, ammodef.second, calendar::turn );
                    }
                }
                g->remove_zombie( critter );
            } else {
                if( sight ) {
                    add_msg( _( "The EMP blast fries the %s!" ), critter.name() );
                }
                int dam = dice( 10, 10 );
                critter.apply_damage( nullptr, bodypart_id( "torso" ), dam );
                critter.check_dead_state();
                if( !critter.is_dead() && one_in( 6 ) ) {
                    critter.make_friendly();
                }
            }
        } else if( critter.has_flag( MF_ELECTRIC_FIELD ) ) {
            if( !critter.has_effect( effect_emp ) ) {
                if( sight ) {
                    add_msg( m_good, _( "The %s's electrical field momentarily goes out!" ), critter.name() );
                }
                critter.add_effect( effect_emp, 3_minutes );
            } else if( critter.has_effect( effect_emp ) ) {
                int dam = dice( 3, 5 );
                if( sight ) {
                    add_msg( m_good, _( "The %s's disabled electrical field reverses polarity!" ),
                             critter.name() );
                    add_msg( m_good, _( "It takes %d damage." ), dam );
                }
                critter.add_effect( effect_emp, 1_minutes );
                critter.apply_damage( nullptr, bodypart_id( "torso" ), dam );
                critter.check_dead_state();
            }
        } else if( sight ) {
            add_msg( _( "The %s is unaffected by the EMP blast." ), critter.name() );
        }
    }
    if( u.pos() == p ) {
        if( u.get_power_level() > 0_kJ ) {
            add_msg( m_bad, _( "The EMP blast drains your power." ) );
            int max_drain = ( u.get_power_level() > 1000_kJ ? 1000 : units::to_kilojoule(
                                  u.get_power_level() ) );
            u.mod_power_level( units::from_kilojoule( -rng( 1 + max_drain / 3, max_drain ) ) );
        }
        // TODO: More effects?
        //e-handcuffs effects
        item &cuffs = u.primary_weapon();
        if( cuffs.typeId() == itype_e_handcuffs && cuffs.charges > 0 ) {
            cuffs.unset_flag( "NO_UNWIELD" );
            cuffs.charges = 0;
            cuffs.active = false;
            add_msg( m_good, _( "The %s on your wrists spark briefly, then release your hands!" ),
                     cuffs.tname() );
        }
    }
    // Drain any items of their battery charge
    for( auto &it : here.i_at( p ) ) {
        if( it.is_tool() && it.ammo_current() == itype_battery ) {
            it.charges = 0;
        }
    }
    // TODO: Drain NPC energy reserves
}
References _, item::active, monster::add_effect(), map::add_item_or_charges(), add_msg(), monster::ammo, monster::apply_damage(), item::charges, Creature::check_dead_state(), dice(), effect_emp, units::from_kilojoule(), g, get_map(), get_player_character(), Character::get_power_level(), monster::get_size(), Creature::has_effect(), map::has_flag(), monster::has_flag(), map::i_at(), monster::is_dead(), itype_battery, itype_e_handcuffs, m_bad, m_good, monster::make_friendly(), MF_ELECTRIC_FIELD, MF_ELECTRONIC, Character::mod_power_level(), MS_SMALL, MS_TINY, monster::name(), one_in(), Character::pos(), Character::primary_weapon(), mtype::revert_to_itype, rng(), Character::sees(), map::spawn_item(), t_card_industrial, t_card_military, t_card_reader_broken, t_card_science, t_console_broken, t_door_metal_locked, t_floor, map::ter(), map::ter_set(), map::tername(), item::tname(), monster::to_item(), units::to_kilojoule(), calendar::turn, monster::type, item::typeId(), and item::unset_flag().
Referenced by Character::activate_bionic(), apply_ammo_effects(), monster::process_turn(), explosion_handler::explosion_funcs::resonance_cascade(), and explosion_iuse::trigger_explosion().
explosion() [1/2]
void explosion_handler::explosion (const tripoint & p, const explosion_data & ex, Creature * source)
Definition at line 1096 of file explosion.cpp.
{
    queued_explosion qe( p, ExplosionType::Regular, source );
    qe.exp_data = ex;
    get_explosion_queue().add( std::move( qe ) );
}
References explosion_handler::explosion_queue::add(), explosion_handler::queued_explosion::exp_data, get_explosion_queue(), avatar_action::move(), and Regular.
Referenced by explosion_handler::explosion_funcs::resonance_cascade().
explosion() [2/2]
void explosion_handler::explosion (const tripoint & p, Creature * source, float power, float factor = 0.8f, bool fire = false, int legacy_casing_mass = 0, float legacy_frag_mass = 0.05)
Legacy explosion function.
Updated values are calculated from distance factor. If power > 0, blast is produced. If casing mass > 0, shrapnel is produced.
Definition at line 1079 of file explosion.cpp.
{
    if( factor >= 1.0f ) {
        debugmsg( "called game::explosion with factor >= 1.0 (infinite size)" );
    }
    explosion_data data;
    data.damage = power * explosion_handler::power_to_dmg_mult;
    data.radius = explosion_handler::blast_radius_from_legacy( power, factor );
    data.fire = fire;
    if( legacy_casing_mass > 0 ) {
        data.fragment = explosion_handler::shrapnel_from_legacy( power, data.radius );
    }
    explosion( p, data, source );
}
References blast_radius_from_legacy(), explosion_data::damage, debugmsg, explosion(), explosion_data::fire, fire(), explosion_data::fragment, power_to_dmg_mult, explosion_data::radius, and shrapnel_from_legacy().
Referenced by computer_session::action_irradiator(), computer_session::action_srcf_seal(), apply_ammo_effects(), iuse::artifact(), map::bash_furn_success(), map::bash_ter_success(), trapfunc::boobytrap(), item::detonate(), mdeath::explode(), vehicle::explode_fuel(), spell_effect::explosion(), explosion(), computer_session::failure_amigara(), computer_session::failure_pump_explode(), mdeath::focused_beam(), iuse::grenade_inc_act(), vehicle::handle_trap(), trapfunc::landmine(), monster::process_turn(), projectile_attack(), and explosion_iuse::trigger_explosion().
flashbang()
void explosion_handler::flashbang (const tripoint & p, bool player_immune, const std::string & exp_name)
Triggers a flashbang explosion at p.
Definition at line 1552 of file explosion.cpp.
{
    // flashbangs cannot kill, so skip the source
    queued_explosion qe( p, ExplosionType::Flashbang, nullptr );
    qe.affects_player = !player_immune;
    qe.graphics_name = exp_name;
    get_explosion_queue().add( std::move( qe ) );
}
References explosion_handler::explosion_queue::add(), explosion_handler::queued_explosion::affects_player, get_explosion_queue(), explosion_handler::queued_explosion::graphics_name, and avatar_action::move().
Referenced by Character::activate_bionic(), apply_ammo_effects(), iuse::artifact(), explosion_handler::explosion_queue::execute(), spell_effect::flashbang(), trapfunc::glow(), and explosion_iuse::trigger_explosion().
get_explosion_queue()
explosion_queue & explosion_handler::get_explosion_queue ()
Definition at line 1920 of file explosion.cpp.
{
    static explosion_queue singleton;
    return singleton;
}
Referenced by game::do_turn(), mdeath::explode(), explosion(), flashbang(), mdeath::focused_beam(), resonance_cascade(), game::setup(), and shockwave().
legacy_blast()
static std::map< const Creature *, int > explosion_handler::legacy_blast (const tripoint & p, const float power, const float radius, const bool fire, Creature * source) static
Definition at line 1277 of file explosion.cpp.
{
    std::map<const Creature *, int> blasted;
    if( radius <= 0.0f ) {
        return blasted; // Just return an empty one
    }
    const float tile_dist = 1.0f;
    const float diag_dist = trigdist ? M_SQRT2 * tile_dist : 1.0f * tile_dist;
    const float zlev_dist = 4.0f; // Penalty for going up/down
    // 7 3 5
    // 1 . 2
    // 6 4 8
    // 9 and 10 are up and down
    static const int x_offset[10] = { -1, 1,  0, 0,  1, -1, -1, 1, 0, 0 };
    static const int y_offset[10] = { 0, 0, -1, 1, -1,  1, -1, 1, 0, 0 };
    static const int z_offset[10] = { 0, 0,  0, 0,  0,  0,  0, 0, 1, -1 };
    map &here = get_map();
    const size_t max_index = here.has_zlevels() ? 10 : 8;
    here.bash( p, fire ? power : ( 2 * power ), true, false, false );
    std::priority_queue< std::pair<float, tripoint>, std::vector< std::pair<float, tripoint> >, pair_greater_cmp_first >
    open;
    std::set<tripoint> closed;
    std::map<tripoint, float> dist_map;
    open.push( std::make_pair( 0.0f, p ) );
    dist_map[p] = 0.0f;
    // Find all points to blast
    while( !open.empty() ) {
        const float distance = open.top().first;
        const tripoint pt = open.top().second;
        open.pop();
        if( closed.count( pt ) != 0 ) {
            continue;
        }
        closed.insert( pt );
        const float force = power * obstacle_blast_percentage( radius, distance );
        if( force <= 1.0f ) {
            continue;
        }
        if( here.impassable( pt ) && pt != p ) {
            // Don't propagate further
            continue;
        }
        // Iterate over all neighbors. Bash all of them, propagate to some
        for( size_t i = 0; i < max_index; i++ ) {
            tripoint dest( pt + tripoint( x_offset[i], y_offset[i], z_offset[i] ) );
            if( closed.count( dest ) != 0 || !here.inbounds( dest ) ||
                here.obstructed_by_vehicle_rotation( pt, dest ) ) {
                continue;
            }
            if( z_offset[i] == 0 ) {
                // Horizontal - no floor bashing
                here.bash( dest, force, true, false, false );
            } else if( z_offset[i] > 0 ) {
                // Should actually bash through the floor first, but that's not really possible yet
                here.bash( dest, force, true, false, true );
            } else if( !here.valid_move( pt, dest, false, true ) ) {
                // Only bash through floor if it doesn't exist
                // Bash the current tile's floor, not the one's below
                here.bash( pt, force, true, false, true );
            }
            float next_dist = distance;
            next_dist += ( x_offset[i] == 0 || y_offset[i] == 0 ) ? tile_dist : diag_dist;
            if( z_offset[i] != 0 ) {
                if( !here.valid_move( pt, dest, false, true ) ) {
                    continue;
                }
                next_dist += zlev_dist;
            }
            if( dist_map.count( dest ) == 0 || dist_map[dest] > next_dist ) {
                open.push( std::make_pair( next_dist, dest ) );
                dist_map[dest] = next_dist;
            }
        }
    }
    // Draw the explosion
    std::map<tripoint, nc_color> explosion_colors;
    for( auto &pt : closed ) {
        if( here.impassable( pt ) ) {
            continue;
        }
        float percentage = obstacle_blast_percentage( radius, dist_map.at( pt ) );
        if( percentage > 0.0f ) {
            static const std::array<nc_color, 3> colors = { {
                    c_red, c_yellow, c_white
                }
            };
            size_t color_index = ( power > 30 ? 1 : 0 ) + ( percentage > 0.5f ? 1 : 0 );
            explosion_colors[pt] = colors[color_index];
        }
    }
    draw_custom_explosion( g->u.pos(), explosion_colors, "explosion" );
    for( const tripoint &pt : closed ) {
        const float force = power * obstacle_blast_percentage( radius, dist_map.at( pt ) );
        if( force < 1.0f ) {
            // Too weak to matter
            continue;
        }
        here.smash_items( pt, force, _( "force of the explosion" ), true );
        if( fire ) {
            int intensity = 1 + ( force > 10.0f ) + ( force > 30.0f );
            if( !here.has_zlevels() && here.is_outside( pt ) && intensity == 2 ) {
                // In 3D mode, it would have fire fields above, which would then fall
                // and fuel the fire on this tile
                intensity++;
            }
            here.add_field( pt, fd_fire, intensity );
        }
        if( const optional_vpart_position vp = here.veh_at( pt ) ) {
            // TODO: Make this weird unit used by vehicle::damage more sensible
            vp->vehicle().damage( vp->part_index(), force, fire ? DT_HEAT : DT_BASH, false );
        }
        Creature *critter = g->critter_at( pt, true );
        if( critter == nullptr ) {
            continue;
        }
        player *pl = dynamic_cast<player *>( critter );
        if( pl == nullptr ) {
            const double dmg = std::max( force - critter->get_armor_bash( bodypart_id( "torso" ) ) / 3.0, 0.0 );
            const int actual_dmg = rng_float( dmg, dmg * 2 );
            critter->apply_damage( source, bodypart_id( "torso" ), actual_dmg );
            critter->check_dead_state();
            blasted[critter] = actual_dmg;
            continue;
        }
        // Print messages for all NPCs
        pl->add_msg_if_player( m_bad, _( "You're caught in the explosion!" ) );
        struct blastable_part {
            bodypart_id bp;
            float low_mul;
            float high_mul;
            float armor_mul;
        };
        static const std::array<blastable_part, 6> blast_parts = { {
                { bodypart_id( "torso" ), 0.5f, 1.0f, 0.5f },
                { bodypart_id( "head" ),  0.5f, 1.0f, 0.5f },
                // Hit limbs harder so that it hurts more without being much more deadly
                { bodypart_id( "leg_l" ), 0.75f, 1.25f, 0.4f },
                { bodypart_id( "leg_r" ), 0.75f, 1.25f, 0.4f },
                { bodypart_id( "arm_l" ), 0.75f, 1.25f, 0.4f },
                { bodypart_id( "arm_r" ), 0.75f, 1.25f, 0.4f },
            }
        };
        for( const auto &blp : blast_parts ) {
            const int part_dam = rng( force * blp.low_mul, force * blp.high_mul );
            const std::string hit_part_name = body_part_name_accusative( blp.bp->token );
            const auto dmg_instance = damage_instance( DT_BASH, part_dam, 0, blp.armor_mul );
            const auto result = pl->deal_damage( source, blp.bp, dmg_instance );
            const int res_dmg = result.total_damage();
            add_msg( m_debug, "%s for %d raw, %d actual", hit_part_name, part_dam, res_dmg );
            if( res_dmg > 0 ) {
                blasted[critter] += res_dmg;
            }
        }
    }
    return blasted;
}
References _, map::add_field(), add_msg(), player::add_msg_if_player(), Creature::apply_damage(), map::bash(), body_part_name_accusative(), c_red, c_white, c_yellow, Creature::check_dead_state(), PATH_INFO::colors(), Character::deal_damage(), draw_custom_explosion(), DT_BASH, DT_HEAT, fd_fire, fire(), g, Creature::get_armor_bash(), get_map(), map::has_zlevels(), map::impassable(), map::inbounds(), map::is_outside(), m_bad, m_debug, M_SQRT2, obstacle_blast_percentage(), map::obstructed_by_vehicle_rotation(), open(), rng(), rng_float(), map::smash_items(), trigdist, map::valid_move(), and map::veh_at().
Referenced by explosion_handler::explosion_funcs::regular().
legacy_shrapnel()
static std::map< const Creature *, int > explosion_handler::legacy_shrapnel (const tripoint & src, const projectile & fragment, Creature * source) static
Definition at line 1103 of file explosion.cpp.
{
    std::map<const Creature *, int> damaged;
    projectile proj = fragment;
    proj.add_effect( ammo_effect_NULL_SOURCE );
    float obstacle_cache[MAPSIZE_X][MAPSIZE_Y] = {};
    float visited_cache[MAPSIZE_X][MAPSIZE_Y] = {};
    map &here = get_map();
    diagonal_blocks( &blocked_cache )[MAPSIZE_X][MAPSIZE_Y] = here.access_cache(
                src.z ).vehicle_obstructed_cache;
    // TODO: Calculate range based on max effective range for projectiles.
    // Basically bisect between 0 and map diameter using shrapnel_calc().
    // Need to update shadowcasting to support limiting range without adjusting initial distance.
    const tripoint_range<tripoint> area = here.points_on_zlevel( src.z );
    here.build_obstacle_cache( area.min(), area.max() + tripoint_south_east, obstacle_cache );
    // Shadowcasting normally ignores the origin square,
    // so apply it manually to catch monsters standing on the explosive.
    // This "blocks" some fragments, but does not apply deceleration.
    visited_cache[src.x][src.y] = 1.0f;
    // This is used to limit radius
    // By default, the radius is 60, so negative values can be helpful here
    const int offset_distance = 60 - 1 - fragment.range;
    castLightAll<float, float, shrapnel_calc, shrapnel_check,
                 update_fragment_cloud, accumulate_fragment_cloud>
                 ( visited_cache, obstacle_cache, blocked_cache, src.xy(),
                   offset_distance, fragment.range + 1.0f );
    // Now visited_caches are populated with density and velocity of fragments.
    for( const tripoint &target : area ) {
        if( visited_cache[target.x][target.y] <= 0.0f || rl_dist( src, target ) > fragment.range ) {
            continue;
        }
        auto critter = g->critter_at( target );
        if( critter && !critter->is_dead_state() ) {
            // dealt_dag->m.total_damage() == 0 means armor block
            // dealt_dag->m.total_damage() > 0 means took damage
            // Need to diffentiate target among player, npc, and monster
            int damage_taken = 0;
            auto bps = critter->get_all_body_parts( true );
            // Humans get hit in all body parts
            if( critter->is_player() ) {
                for( bodypart_id bp : bps ) {
                    // TODO: This shouldn't be needed, get_bps should do it
                    if( Character::bp_to_hp( bp->token ) == num_hp_parts ) {
                        continue;
                    }
                    // TODO: Apply projectile effects
                    // TODO: Penalize low coverage armor
                    // Halve damage to be closer to what monsters take
                    damage_instance half_impact = proj.impact;
                    half_impact.mult_damage( 0.5f );
                    dealt_damage_instance dealt = critter->deal_damage( source, bp, proj.impact );
                    if( dealt.total_damage() > 0 ) {
                        damage_taken += dealt.total_damage();
                    }
                }
            } else {
                dealt_damage_instance dealt = critter->deal_damage( source, bps[0], proj.impact );
                if( dealt.total_damage() > 0 ) {
                    damage_taken += dealt.total_damage();
                }
            }
            damaged[critter] = damage_taken;
        }
        if( here.impassable( target ) ) {
            int damage = proj.impact.total_damage();
            if( optional_vpart_position vp = here.veh_at( target ) ) {
                vp->vehicle().damage( vp->part_index(), damage / 100 );
            } else {
                here.bash( target, damage / 100, true );
            }
        }
    }
    const tripoint &blast_center = src;
    const float raw_blast_radius = fragment.range;
    using dist_point_pair = std::pair<float, tripoint>;
    const int Z_LEVEL_DIST = 4;
    const int z_levels_affected = raw_blast_radius / Z_LEVEL_DIST;
    const tripoint_range<tripoint> affected_block(
        blast_center + tripoint( -raw_blast_radius, -raw_blast_radius, -z_levels_affected ),
        blast_center + tripoint( raw_blast_radius, raw_blast_radius, z_levels_affected )
    );
    static std::vector<dist_point_pair> blast_map( MAPSIZE_X * MAPSIZE_Y );
    static std::map<tripoint, nc_color> explosion_colors;
    blast_map.clear();
    explosion_colors.clear();
    for( const tripoint &target : affected_block ) {
        if( !get_map().inbounds( target ) ) {
            continue;
        }
        // Uses this ternany check instead of rl_dist because it converts trig_dist's distance to int implicitly
        const float distance = (
                                   trigdist ?
                                   trig_dist( blast_center, target ) :
                                   square_dist( blast_center, target )
                               );
        const float z_distance = abs( target.z - blast_center.z );
        const float z_aware_distance = distance + ( Z_LEVEL_DIST - 1 ) * z_distance;
        if( z_aware_distance <= raw_blast_radius ) {
            blast_map.emplace_back( std::make_pair( z_aware_distance, target ) );
        }
    }
    std::stable_sort( blast_map.begin(), blast_map.end(), []( dist_point_pair pair1,
    dist_point_pair pair2 ) {
        return pair1.first < pair2.first;
    } );
    int animated_explosion_range = 0.0f;
    std::map<const Creature *, int> blasted;
    int i = 0;
    for( const dist_point_pair &pair : blast_map ) {
        float distance;
        tripoint position;
        tripoint last_position = blast_center;
        std::tie( distance, position ) = pair;
        const std::vector<tripoint> line_of_movement = line_to( blast_center, position );
        const bool has_obstacles = std::any_of( line_of_movement.begin(),
        line_of_movement.end(), [position, &last_position]( tripoint ray_position ) {
            if( get_map().obstructed_by_vehicle_rotation( last_position, ray_position ) ) {
                return true;
            }
            last_position = ray_position;
            return ray_position != position && get_map().impassable( ray_position );
        } );
        // Don't bother animating explosions that are on other levels
        const bool to_animate = get_player_character().posz() == position.z;
        // Animate the explosion by drawing the shock wave rather than the whole explosion
        if( to_animate && distance > animated_explosion_range ) {
            // Draw only 1/2 rings to speed up the animation
            if( i % 2 == 0 ) {
                draw_custom_explosion( blast_center, explosion_colors, "fd_smoke" );
            }
            i++;
            explosion_colors.clear();
            animated_explosion_range++;
        }
        if( has_obstacles ) {
            continue;
        }
        if( to_animate ) {
            explosion_colors[position] = c_white;
        }
    }
    // Final blast wave points
    draw_custom_explosion( blast_center, explosion_colors, "fd_smoke" );
    // END DRAWING EXPLOSION
    return damaged;
}
References map::access_cache(), accumulate_fragment_cloud(), projectile::add_effect(), ammo_effect_NULL_SOURCE, map::bash(), Character::bp_to_hp(), map::build_obstacle_cache(), c_white, castLightAll(), draw_custom_explosion(), g, get_map(), get_player_character(), projectile::impact, map::impassable(), line_to(), MAPSIZE_X, MAPSIZE_Y, tripoint_range< Tripoint >::max(), tripoint_range< Tripoint >::min(), damage_instance::mult_damage(), num_hp_parts, map::points_on_zlevel(), Character::posz(), projectile::range, rl_dist(), shrapnel_calc(), shrapnel_check(), square_dist(), damage_instance::total_damage(), dealt_damage_instance::total_damage(), trig_dist(), trigdist, tripoint_south_east, update_fragment_cloud(), map::veh_at(), level_cache::vehicle_obstructed_cache, tripoint::x, tripoint::xy(), tripoint::y, tripoint::z, and ExplosionConstants::Z_LEVEL_DIST.
Referenced by explosion_handler::explosion_funcs::regular().
resonance_cascade()
void explosion_handler::resonance_cascade (const tripoint & p)
Triggers a resonance cascade at p.
Definition at line 1799 of file explosion.cpp.
{
    get_explosion_queue().add( queued_explosion( p, ExplosionType::ResonanceCascade, nullptr ) );
}
References explosion_handler::explosion_queue::add(), and get_explosion_queue().
Referenced by computer_session::action_cascade(), and explosion_handler::explosion_queue::execute().
scrambler_blast()
void explosion_handler::scrambler_blast (const tripoint & p)
Triggers a scrambler blast at p.
Definition at line 1659 of file explosion.cpp.
{
    if( monster *const mon_ptr = g->critter_at<monster>( p ) ) {
        monster &critter = *mon_ptr;
        if( critter.has_flag( MF_ELECTRONIC ) ) {
            critter.make_friendly();
        }
        add_msg( m_warning, _( "The %s sparks and begins searching for a target!" ),
                 critter.name() );
    }
}
References _, add_msg(), g, monster::has_flag(), m_warning, monster::make_friendly(), MF_ELECTRONIC, and monster::name().
Referenced by explosion_iuse::trigger_explosion().
shockwave()
void explosion_handler::shockwave (const tripoint & p, const shockwave_data & sw, const std::string & exp_name, Creature * source)
Shockwave applies knockback with given parameters to all targets within radius of p.
Definition at line 1612 of file explosion.cpp.
{
    queued_explosion qe( p, ExplosionType::Shockwave, source );
    qe.swave_data = sw;
    qe.graphics_name = exp_name;
    get_explosion_queue().add( std::move( qe ) );
}
References explosion_handler::explosion_queue::add(), get_explosion_queue(), explosion_handler::queued_explosion::graphics_name, avatar_action::move(), and explosion_handler::queued_explosion::swave_data.
Referenced by Character::activate_bionic(), and explosion_handler::explosion_queue::execute().
shrapnel_from_legacy()
projectile explosion_handler::shrapnel_from_legacy (int power, float blast_radius)
Definition at line 1901 of file explosion.cpp.
{
    int range = 2 * blast_radius;
    // Damage approximately equal to blast damage at epicenter
    int damage = power * power_to_dmg_mult;
    projectile proj;
    proj.speed = 1000;
    proj.range = range;
    proj.impact.add_damage( DT_CUT, damage, 0.0f, 3.0f );
    return proj;
}
References damage_instance::add_damage(), DT_CUT, projectile::impact, power_to_dmg_mult, range, projectile::range, and projectile::speed.
Referenced by explosion(), and load_explosion_data().
Variable Documentation
power_to_dmg_mult
constexpr float explosion_handler::power_to_dmg_mult = 2.0f / 15.0f constexpr
Definition at line 49 of file explosion.h.
Referenced by blast_radius_from_legacy(), explosion(), load_explosion_data(), explosion_handler::explosion_funcs::regular(), and shrapnel_from_legacy().