Cataclysm BN: game_info Namespace Reference
game_info Namespace Reference
Used to generate game report information.
Functions
std::string operating_system ()
Return the name of the current operating system.
std::string operating_system_version ()
Return a detailed version of the operating system; e.g.
std::optional< int > bitness ()
Return the "bitness" of the game (not necessarily of the operating system); either: 64, 32 or nullopt.
std::string bitness_string ()
Return the "bitness" string of the game (not necessarily of the operating system); either: 64-bit, 32-bit or Unknown.
std::string game_version ()
Return the game version, as in the entry screen.
std::string graphics_version ()
Return the underlying graphics version used by the game; either Tiles or Curses.
std::string mods_loaded ()
Return a list of the loaded mods, including the mod full name and its id name in brackets, e.g.
std::string game_report ()
Generate a game report, including the information returned by all of the other functions.
Detailed Description
Used to generate game report information.
Function Documentation
bitness()
std::optional< int > game_info::bitness ()
Return the "bitness" of the game (not necessarily of the operating system); either: 64, 32 or nullopt.
Definition at line 1732 of file debug.cpp.
{
    if( sizeof( void * ) == 8 ) {
        return 64;
    }
    if( sizeof( void * ) == 4 ) {
        return 32;
    }
    return std::nullopt;
}
Referenced by bitness_string(), and main_menu::opening_screen().
bitness_string()
std::string game_info::bitness_string ()
Return the "bitness" string of the game (not necessarily of the operating system); either: 64-bit, 32-bit or Unknown.
Definition at line 1745 of file debug.cpp.
{
    auto b = bitness();
    if( b && *b == 32 ) {
        return "32-bit";
    }
    if( b && *b == 64 ) {
        return "64-bit";
    }
    return "Unknown";
}
References b, and bitness().
Referenced by game_report(), and DebugFile::init().
game_report()
std::string game_info::game_report ()
Generate a game report, including the information returned by all of the other functions.
Definition at line 1793 of file debug.cpp.
{
    std::string os_version = operating_system_version();
    if( os_version.empty() ) {
        os_version = "<unknown>";
    }
    std::stringstream report;
    std::string lang = get_option<std::string>( "USE_LANG" );
    std::string lang_translated;
    for( const language_info &info : list_available_languages() ) {
        if( lang == info.id ) {
            lang_translated = info.name;
            break;
        }
    }
    // Note: We shorten 'Lua API' to 'LAPI' so that 'Lua' word does not show up
    //       in every issue out there and pollute GitHub issue search results.
    report <<
           "- OS: " << operating_system() << "\n" <<
           "    - OS Version: " << os_version << "\n" <<
           "- Game Version: " << game_version() << " [" << bitness_string() << "]\n" <<
           "- Graphics Version: " << graphics_version() << "\n" <<
           "- LAPI Version: " << cata::get_lapi_version_string() << "\n" <<
           "- Game Language: " << lang_translated << " [" << lang << "]\n" <<
           "- Mods loaded: [\n    " << mods_loaded() << "\n]\n";
    return report.str();
}
References bitness_string(), game_version(), cata::get_lapi_version_string(), graphics_version(), list_available_languages(), mods_loaded(), operating_system(), and operating_system_version().
Referenced by debug_menu::debug().
game_version()
std::string game_info::game_version ()
Return the game version, as in the entry screen.
Definition at line 1757 of file debug.cpp.
{
    return getVersionString();
}
References getVersionString().
Referenced by game_report().
graphics_version()
std::string game_info::graphics_version ()
Return the underlying graphics version used by the game; either Tiles or Curses.
Definition at line 1762 of file debug.cpp.
{
#if defined(TILES)
    return "Tiles";
#else
    return "Curses";
#endif
}
Referenced by game_report().
mods_loaded()
std::string game_info::mods_loaded ()
Return a list of the loaded mods, including the mod full name and its id name in brackets, e.g.
"Dark Days Ahead [dda]".
Definition at line 1771 of file debug.cpp.
{
    if( world_generator->active_world == nullptr ) {
        return "No active world";
    }
    const std::vector<mod_id> &mod_ids = world_generator->active_world->active_mod_order;
    if( mod_ids.empty() ) {
        return "No loaded mods";
    }
    std::vector<std::string> mod_names;
    mod_names.reserve( mod_ids.size() );
    std::transform( mod_ids.begin(), mod_ids.end(),
    std::back_inserter( mod_names ), []( const mod_id mod ) -> std::string {
        // e.g. "Dark Days Ahead [dda]".
        return string_format( "%s [%s]", remove_color_tags( mod->name() ), mod->ident.str() );
    } );
    return join( mod_names, ",\n    " ); // note: 4 spaces for a slight offset.
}
References join(), iexamine::transform(), and world_generator.
Referenced by game_report().
operating_system()
std::string game_info::operating_system ()
Return the name of the current operating system.
Definition at line 1433 of file debug.cpp.
{
#if defined(__ANDROID__)
    return "Android";
#elif defined(_WIN32)
    return "Windows";
#elif defined(__linux__)
    return "Linux";
#elif defined(unix) || defined(__unix__) || defined(__unix) || (defined(__APPLE__) && defined(__MACH__)) // unix; BSD; MacOs
#if defined(__APPLE__) && defined(__MACH__)
    // The following include is **only** needed for the TARGET_xxx defines below and is only included if both of the above defines are true.
    // The whole function only relying on compiler defines, it is probably more meaningful to include it here and not mingle with the
    // headers at the top of the .cpp file.
#include <TargetConditionals.h>
#if TARGET_IPHONE_SIMULATOR == 1
    /* iOS in Xcode simulator */
    return "iOS Simulator";
#elif TARGET_OS_IPHONE == 1
    /* iOS on iPhone, iPad, etc. */
    return "iOS";
#elif TARGET_OS_MAC == 1
    /* OSX */
    return "MacOs";
#endif // TARGET_IPHONE_SIMULATOR
#elif defined(BSD)
    return "BSD";
#else
    return "Unix";
#endif // __APPLE__
#else
    return "Unknown";
#endif
}
Referenced by game_report().
operating_system_version()
std::string game_info::operating_system_version ()
Return a detailed version of the operating system; e.g.
"Ubuntu 18.04" or "(Windows) 10 1809".
Definition at line 1715 of file debug.cpp.
{
#if defined(__ANDROID__)
    return android_version();
#elif defined(BSD)
    return bsd_version();
#elif defined(__linux__)
    return linux_version();
#elif defined(__APPLE__) && defined(__MACH__) && !defined(BSD)
    return mac_os_version();
#elif defined(_WIN32)
    return windows_version();
#else
    return "<unknown>";
#endif
}
Referenced by game_report().