Cataclysm BN: anonymous_namespace{action.cpp} Namespace Reference
anonymous_namespace{action.cpp} Namespace Reference
Functions
auto make_register_actions (std::vector< uilist_entry > &entries, const input_context &ctxt)
auto make_register_categories (std::vector< uilist_entry > &entries, std::map< int, std::string > &categories_by_int, int &last_category)
Function Documentation
make_register_actions()
auto anonymous_namespace{action.cpp}::make_register_actions (std::vector< uilist_entry > & entries, const input_context & ctxt)
Definition at line 669 of file action.cpp.
{
    return [&]( std::vector<action_id> &&names ) -> void {
        const auto fn = [&]( action_id name ) -> uilist_entry {
            return { name, true, hotkey_for_action( name ), ctxt.get_action_name( action_ident( name ) ) };
        };
        std::transform( names.begin(), names.end(), std::back_inserter( entries ), fn );
    };
}
References action_ident(), input_context::get_action_name(), hotkey_for_action(), om_direction::name(), Name::names, and iexamine::transform().
Referenced by handle_action_menu(), and handle_main_menu().
make_register_categories()
auto anonymous_namespace{action.cpp}::make_register_categories (std::vector< uilist_entry > & entries, std::map< int, std::string > & categories_by_int, int & last_category)
Definition at line 679 of file action.cpp.
{
    return [&]( std::vector<std::string> &&names ) -> void {
        const auto fn = [&]( const std::string & name ) -> uilist_entry {
            categories_by_int[last_category] = name;
            return { last_category++, true, -1, name + "…" };
        };
        std::transform( names.begin(), names.end(), std::back_inserter( entries ),  fn );
    };
}
References om_direction::name(), Name::names, and iexamine::transform().
Referenced by handle_action_menu().