Cataclysm BN: anonymous_namespace{character.cpp} Namespace Reference
anonymous_namespace{character.cpp} Namespace Reference
Enumerations
enum class ShieldLevel { None , Block1 , Block2 , Block3 }
Functions
auto is_foot_hit (const bodypart_id &bp_hit) -> bool
auto is_leg_hit (const bodypart_id &bp_hit) -> bool
auto is_covered_by_shield (const bodypart_id &bp_hit, const item &shield) -> bool
Check if the given shield can protect the given bodypart.
auto shield_level (const item &shield) -> ShieldLevel
auto coverage_modifier_by_technic (ShieldLevel level, bool leg_hit) -> float
auto is_valid_hallucination (Creature *source) -> bool
auto get_shield_resist (const item &shield, const damage_unit &damage) -> int
auto get_block_amount (const item &shield, const damage_unit &unit) -> int
Enumeration Type Documentation
ShieldLevel
enum class anonymous_namespace{character.cpp}::ShieldLevel strong
Enumerator
None
Block1
Block2
Block3
Definition at line 10690 of file character.cpp.
{ None, Block1, Block2, Block3 };
Function Documentation
coverage_modifier_by_technic()
auto anonymous_namespace{character.cpp}::coverage_modifier_by_technic (ShieldLevel level, bool leg_hit) -> float
Definition at line 10703 of file character.cpp.
{
    switch( level ) {
        case ShieldLevel::Block3:
            return leg_hit ? 0.75f : 0.9f;
        case ShieldLevel::Block2:
            return leg_hit ? 0.5f : 0.8f;
        case ShieldLevel::Block1:
            return leg_hit ? 0.25f : 0.7f;
        default:
            return 0.0f;
    }
}
Referenced by Character::block_ranged_hit().
get_block_amount()
auto anonymous_namespace{character.cpp}::get_block_amount (const item & shield, const damage_unit & unit) -> int
Definition at line 10737 of file character.cpp.
{
    const int resist = get_shield_resist( shield, unit );
    return std::max( 0.0f, ( resist - unit.res_pen ) * unit.res_mult );
}
References get_shield_resist().
Referenced by Character::block_ranged_hit().
get_shield_resist()
auto anonymous_namespace{character.cpp}::get_shield_resist (const item & shield, const damage_unit & damage) -> int
Definition at line 10722 of file character.cpp.
{
    // *INDENT-OFF*
    switch( damage.type ) {
        case DT_BASH:   return shield.bash_resist();
        case DT_CUT:    return shield.cut_resist();
        case DT_STAB:   return shield.stab_resist();
        case DT_BULLET: return shield.bullet_resist();
        case DT_HEAT:   return shield.fire_resist();
        case DT_ACID:   return shield.acid_resist();
        default:        return 0;
    }
    // *INDENT-ON*
}
References DT_ACID, DT_BASH, DT_BULLET, DT_CUT, DT_HEAT, and DT_STAB.
Referenced by get_block_amount().
is_covered_by_shield()
auto anonymous_namespace{character.cpp}::is_covered_by_shield (const bodypart_id & bp_hit, const item & shield) -> bool
Check if the given shield can protect the given bodypart.
Best item available doesn't count as a shield.
Shield already protects the part we're interested in.
Targeted bodypart is a foot, unlikely to ever successfully block that low.
Definition at line 10683 of file character.cpp.
{
    return shield.has_flag( "BLOCK_WHILE_WORN" )
           && !shield.covers( bp_hit->token )
           && !is_foot_hit( bp_hit );
}
References is_foot_hit().
Referenced by Character::block_ranged_hit().
is_foot_hit()
auto anonymous_namespace{character.cpp}::is_foot_hit (const bodypart_id & bp_hit) -> bool
Definition at line 10666 of file character.cpp.
{
    return bp_hit == bodypart_str_id( "foot_l" ) || bp_hit == bodypart_str_id( "foot_r" );
}
Referenced by is_covered_by_shield().
is_leg_hit()
auto anonymous_namespace{character.cpp}::is_leg_hit (const bodypart_id & bp_hit) -> bool
Definition at line 10671 of file character.cpp.
{
    return bp_hit == bodypart_str_id( "leg_l" ) || bp_hit == bodypart_str_id( "leg_r" );
}
Referenced by Character::block_ranged_hit().
is_valid_hallucination()
auto anonymous_namespace{character.cpp}::is_valid_hallucination (Creature * source) -> bool
Definition at line 10717 of file character.cpp.
{
    return source != nullptr && source->is_hallucination();
}
Referenced by Character::block_ranged_hit().
shield_level()
auto anonymous_namespace{character.cpp}::shield_level (const item & shield) -> ShieldLevel
Definition at line 10691 of file character.cpp.
{
    if( shield.has_technique( WBLOCK_3 ) ) {
        return ShieldLevel::Block3;
    } else if( shield.has_technique( WBLOCK_2 ) ) {
        return ShieldLevel::Block2;
    } else if( shield.has_technique( WBLOCK_1 ) ) {
        return ShieldLevel::Block1;
    }
    return ShieldLevel::None;
}
References WBLOCK_1, WBLOCK_2, and WBLOCK_3.
Referenced by Character::block_ranged_hit().