Cataclysm BN: anonymous_namespace{vehicle_export.cpp} Namespace Reference
anonymous_namespace{vehicle_export.cpp} Namespace Reference
Typedefs
using refs = std::vector< vpart_reference >
Functions
auto grouped_refs (const class vehicle &v) -> std::vector< refs >
auto is_plain_id (const vpart_reference &vpr) -> bool
auto json_part_write (JsonOut &json, const vpart_reference &vpr) -> void
auto json_parts_write (JsonOut &json, const refs &parts) -> void
Typedef Documentation
refs
using anonymous_namespace{vehicle_export.cpp}::refs = typedef std::vector<vpart_reference>
Definition at line 14 of file vehicle_export.cpp.
Function Documentation
grouped_refs()
auto anonymous_namespace{vehicle_export.cpp}::grouped_refs (const class vehicle & v) -> std::vector<refs>
Definition at line 16 of file vehicle_export.cpp.
{
    std::vector<refs> part_group;
    for( const auto &p : v.get_all_parts() ) {
        const auto &last = part_group.rbegin();
        if( last != part_group.rend() && p.mount() == last->begin()->mount() ) {
            last->emplace_back( p );
        } else {
            part_group.emplace_back( refs{ p } );
        }
    }
    return part_group;
}
References last.
is_plain_id()
auto anonymous_namespace{vehicle_export.cpp}::is_plain_id (const vpart_reference & vpr) -> bool
Definition at line 30 of file vehicle_export.cpp.
{
    const auto &p = vpr.part();
    return !p.is_turret() && ( !p.is_tank() || p.ammo_current().is_null() );
}
Referenced by json_parts_write().
json_part_write()
auto anonymous_namespace{vehicle_export.cpp}::json_part_write (JsonOut & json, const vpart_reference & vpr) -> void
Definition at line 36 of file vehicle_export.cpp.
{
    const auto &p = vpr.part();
    const auto &id  = p.info().get_id();
    const auto &ammo_type = p.ammo_current();
    json.member( "part", id );
    if( p.is_tank() ) {
        json.member( "fuel", ammo_type );
    } else if( p.is_turret() ) {
        json.member( "ammo", 50 );
        json.member( "ammo_types", std::array{ ammo_type } );
        json.member( "ammo_qty", std::array{ 0, p.ammo_capacity() } );
    }
}
Referenced by json_parts_write().
json_parts_write()
auto anonymous_namespace{vehicle_export.cpp}::json_parts_write (JsonOut & json, const refs & parts) -> void
Definition at line 52 of file vehicle_export.cpp.
{
    const auto &first = parts.front();
    if( parts.size() == 1 ) {
        json_part_write( json, first );
    } else {
        json.member( "parts" );
        json.start_array();
        for( const auto &p : parts ) {
            if( is_plain_id( p ) ) {
                json.write( p.info().get_id() );
            } else {
                json.start_object();
                json_part_write( json, p );
                json.end_object();
            }
        }
        json.end_array();
    }
}
References is_plain_id(), and json_part_write().