Cataclysm BN: src/npcmove.cpp File Reference
npcmove.cpp File Reference
#include "npc.h"
#include <algorithm>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <iterator>
#include <memory>
#include <numeric>
#include <ostream>
#include <tuple>
#include "active_item_cache.h"
#include "activity_handlers.h"
#include "basecamp.h"
#include "bionics.h"
#include "bodypart.h"
#include "cata_algo.h"
#include "character.h"
#include "character_functions.h"
#include "character_turn.h"
#include "character_id.h"
#include "clzones.h"
#include "coordinate_conversions.h"
#include "damage.h"
#include "debug.h"
#include "dispersion.h"
#include "effect.h"
#include "enums.h"
#include "explosion.h"
#include "field.h"
#include "field_type.h"
#include "game.h"
#include "game_constants.h"
#include "gates.h"
#include "gun_mode.h"
#include "item.h"
#include "item_contents.h"
#include "item_functions.h"
#include "itype.h"
#include "iuse.h"
#include "iuse_actor.h"
#include "line.h"
#include "map.h"
#include "map_iterator.h"
#include "mapdata.h"
#include "messages.h"
#include "mission.h"
#include "monster.h"
#include "mtype.h"
#include "npctalk.h"
#include "options.h"
#include "overmap.h"
#include "overmap_location.h"
#include "overmapbuffer.h"
#include "player_activity.h"
#include "pldata.h"
#include "projectile.h"
#include "ranged.h"
#include "ret_val.h"
#include "rng.h"
#include "sounds.h"
#include "stomach.h"
#include "translations.h"
#include "units.h"
#include "value_ptr.h"
#include "veh_type.h"
#include "vehicle.h"
#include "visitable.h"
#include "vpart_position.h"
#include "vpart_range.h"
Classes
struct ratio_index
Namespaces
namespace anonymous_namespace{npcmove.cpp}
Enumerations
enum npc_action : int {
npc_undecided = 0 , npc_pause , npc_reload , npc_sleep ,
npc_pickup , npc_heal , npc_use_painkiller , npc_drop_items ,
npc_flee , npc_melee , npc_shoot , npc_look_for_player ,
npc_heal_player , npc_follow_player , npc_follow_embarked , npc_talk_to_player ,
npc_mug_player , npc_goto_to_this_pos , npc_goto_destination , npc_avoid_friendly_fire ,
npc_escape_explosion , npc_noop , npc_reach_attack , npc_aim ,
npc_investigate_sound , npc_return_to_guard_pos , npc_player_activity , npc_worker_downtime ,
num_npc_actions
}
Functions
static const std::string flag_SPLINT ("SPLINT")
std::string npc_action_name (npc_action action)
void print_action (const char *prepend, npc_action action)
bool compare_sound_alert (const dangerous_sound &sound_a, const dangerous_sound &sound_b)
hp_part most_damaged_hp_part (const Character &c)
static bool clear_shot_reach (const tripoint &from, const tripoint &to, bool check_ally=true)
static bool too_close (const tripoint &critter_pos, const tripoint &ally_pos, const int def_radius)
static bool wants_to_reload (const npc &who, const item &it)
static bool wants_to_reload_with (const item &weap, const item &ammo, bool danger)
static std::optional< tripoint > nearest_passable (const tripoint &p, const tripoint &closest_to)
template<typename T >
std::list< item > npc_pickup_from_stack (npc &who, T &items)
static void npc_throw (npc &np, item &it, int index, const tripoint &pos)
static float rate_food (const item &it, int want_nutr, int want_quench)
static body_part bp_affected (npc &who, const efftype_id &effect_type)
static std::string distance_string (int range)
Variables
static const activity_id ACT_PULP ("ACT_PULP")
static const skill_id skill_firstaid ("firstaid")
static const bionic_id bio_ads ("bio_ads")
static const bionic_id bio_advreactor ("bio_advreactor")
static const bionic_id bio_faraday ("bio_faraday")
static const bionic_id bio_furnace ("bio_furnace")
static const bionic_id bio_heat_absorb ("bio_heat_absorb")
static const bionic_id bio_heatsink ("bio_heatsink")
static const bionic_id bio_hydraulics ("bio_hydraulics")
static const bionic_id bio_leukocyte ("bio_leukocyte")
static const bionic_id bio_nanobots ("bio_nanobots")
static const bionic_id bio_ods ("bio_ods")
static const bionic_id bio_painkiller ("bio_painkiller")
static const bionic_id bio_plutfilter ("bio_plutfilter")
static const bionic_id bio_radscrubber ("bio_radscrubber")
static const bionic_id bio_reactor ("bio_reactor")
static const bionic_id bio_shock ("bio_shock")
static const bionic_id bio_soporific ("bio_soporific")
static const efftype_id effect_asthma ("asthma")
static const efftype_id effect_bandaged ("bandaged")
static const efftype_id effect_bite ("bite")
static const efftype_id effect_bleed ("bleed")
static const efftype_id effect_bouldering ("bouldering")
static const efftype_id effect_catch_up ("catch_up")
static const efftype_id effect_disinfected ("disinfected")
static const efftype_id effect_hallu ("hallu")
static const efftype_id effect_hit_by_player ("hit_by_player")
static const efftype_id effect_infected ("infected")
static const efftype_id effect_lying_down ("lying_down")
static const efftype_id effect_no_sight ("no_sight")
static const efftype_id effect_npc_fire_bad ("npc_fire_bad")
static const efftype_id effect_npc_flee_player ("npc_flee_player")
static const efftype_id effect_npc_player_looking ("npc_player_still_looking")
static const efftype_id effect_npc_run_away ("npc_run_away")
static const efftype_id effect_onfire ("onfire")
static const efftype_id effect_stunned ("stunned")
static const flag_str_id flag_NO_UNWIELD ("NO_UNWIELD")
static const itype_id itype_battery ("battery")
static const itype_id itype_chem_ethanol ("chem_ethanol")
static const itype_id itype_chem_methanol ("chem_methanol")
static const itype_id itype_denat_alcohol ("denat_alcohol")
static const itype_id itype_inhaler ("inhaler")
static const itype_id itype_lsd ("lsd")
static const itype_id itype_smoxygen_tank ("smoxygen_tank")
static const itype_id itype_thorazine ("thorazine")
static const itype_id itype_oxygen_tank ("oxygen_tank")
static const itype_id itype_UPS ("UPS")
static constexpr float NPC_DANGER_VERY_LOW = 5.0f
static constexpr float NPC_DANGER_MAX = 150.0f
static constexpr float MAX_FLOAT = 5000000000.0f
const std::vector< bionic_id > anonymous_namespace{npcmove.cpp}::power_cbms
const std::vector< bionic_id > anonymous_namespace{npcmove.cpp}::defense_cbms
const std::vector< bionic_id > anonymous_namespace{npcmove.cpp}::health_cbms
const int anonymous_namespace{npcmove.cpp}::avoidance_vehicles_radius = 5
Enumeration Type Documentation
npc_action
enum npc_action : int
Enumerator
npc_undecided
npc_pause
npc_reload
npc_sleep
npc_pickup
npc_heal
npc_use_painkiller
npc_drop_items
npc_flee
npc_melee
npc_shoot
npc_look_for_player
npc_heal_player
npc_follow_player
npc_follow_embarked
npc_talk_to_player
npc_mug_player
npc_goto_to_this_pos
npc_goto_destination
npc_avoid_friendly_fire
npc_escape_explosion
npc_noop
npc_reach_attack
npc_aim
npc_investigate_sound
npc_return_to_guard_pos
npc_player_activity
npc_worker_downtime
num_npc_actions
Definition at line 133 of file npcmove.cpp.
                : int {
    npc_undecided = 0,
    npc_pause,
    npc_reload, npc_sleep,
    npc_pickup,
    npc_heal, npc_use_painkiller, npc_drop_items,
    npc_flee, npc_melee, npc_shoot,
    npc_look_for_player, npc_heal_player, npc_follow_player, npc_follow_embarked,
    npc_talk_to_player, npc_mug_player,
    npc_goto_to_this_pos,
    npc_goto_destination,
    npc_avoid_friendly_fire,
    npc_escape_explosion,
    npc_noop,
    npc_reach_attack,
    npc_aim,
    npc_investigate_sound,
    npc_return_to_guard_pos,
    npc_player_activity,
    npc_worker_downtime,
    num_npc_actions
};
Function Documentation
bp_affected()
static body_part bp_affected (npc & who, const efftype_id & effect_type) static
Definition at line 4487 of file npcmove.cpp.
{
    body_part ret = num_bp;
    int highest_intensity = INT_MIN;
    for( const body_part bp : all_body_parts ) {
        const auto &eff = who.get_effect( effect_type, bp );
        if( !eff.is_null() && eff.get_intensity() > highest_intensity ) {
            ret = bp;
            highest_intensity = eff.get_intensity();
        }
    }
    return ret;
}
References all_body_parts, Creature::get_effect(), num_bp, and cata::hash64_detail::ret.
Referenced by npc::complain().
clear_shot_reach()
static bool clear_shot_reach (const tripoint & from, const tripoint & to, bool check_ally = true) static
Definition at line 200 of file npcmove.cpp.
{
    std::vector<tripoint> path = line_to( from, to );
    tripoint target_point = path.back();
    path.pop_back();
    if( path.empty() ) {
        return true;
    }
    tripoint &last_point = path[0];
    for( const tripoint &p : path ) {
        Creature *inter = g->critter_at( p );
        if( check_ally && inter != nullptr ) {
            return false;
        } else if( get_map().impassable( p ) ) {
            return false;
        } else if( get_map().obstructed_by_vehicle_rotation( last_point, p ) ) {
            return false;
        }
        last_point = p;
    }
    return !get_map().obstructed_by_vehicle_rotation( last_point, target_point );
}
References g, get_map(), line_to(), and map::obstructed_by_vehicle_rotation().
Referenced by npc::assess_danger(), and npc::method_of_attack().
compare_sound_alert()
bool compare_sound_alert (const dangerous_sound & sound_a, const dangerous_sound & sound_b)
Definition at line 192 of file npcmove.cpp.
{
    if( sound_a.type != sound_b.type ) {
        return sound_a.type < sound_b.type;
    }
    return sound_a.volume < sound_b.volume;
}
References dangerous_sound::type, and dangerous_sound::volume.
Referenced by npc::move().
distance_string()
static std::string distance_string (int range) static
Definition at line 4502 of file npcmove.cpp.
{
    if( range < 6 ) {
        return "<danger_close_distance>";
    } else if( range < 11 ) {
        return "<close_distance>";
    } else if( range < 26 ) {
        return "<medium_distance>";
    } else {
        return "<far_distance>";
    }
}
References range.
Referenced by npc::warn_about().
flag_SPLINT()
static const std::string flag_SPLINT ("SPLINT") static
Referenced by npc::adjust_worn().
most_damaged_hp_part()
hp_part most_damaged_hp_part (const Character & c)
nearest_passable()
static std::optional< tripoint > nearest_passable (const tripoint & p, const tripoint & closest_to) static
Definition at line 2737 of file npcmove.cpp.
{
    map &here = get_map();
    if( here.passable( p ) ) {
        return p;
    }
    // We need to path to adjacent tile, not the exact one
    // Let's pick the closest one to us that is passable
    std::vector<tripoint> candidates = closest_points_first( p, 1 );
    std::sort( candidates.begin(), candidates.end(), [ closest_to ]( const tripoint & l,
    const tripoint & r ) {
        return rl_dist( closest_to, l ) < rl_dist( closest_to, r );
    } );
    auto iter = std::find_if( candidates.begin(), candidates.end(), [&here, &p]( const tripoint & pt ) {
        return here.passable( pt ) && !here.obstructed_by_vehicle_rotation( p, pt );
    } );
    if( iter != candidates.end() ) {
        return *iter;
    }
    return std::nullopt;
}
References closest_points_first(), get_map(), and map::passable().
Referenced by npc::find_item(), and npc::pick_up_item().
npc_action_name()
std::string npc_action_name (npc_action action)
Definition at line 4391 of file npcmove.cpp.
{
    switch( action ) {
        case npc_undecided:
            return "Undecided";
        case npc_pause:
            return "Pause";
        case npc_worker_downtime:
            return "Relaxing";
        case npc_reload:
            return "Reload";
        case npc_investigate_sound:
            return "Investigate sound";
        case npc_return_to_guard_pos:
            return "Returning to guard position";
        case npc_sleep:
            return "Sleep";
        case npc_pickup:
            return "Pick up items";
        case npc_heal:
            return "Heal self";
        case npc_use_painkiller:
            return "Use painkillers";
        case npc_drop_items:
            return "Drop items";
        case npc_flee:
            return "Flee";
        case npc_melee:
            return "Melee";
        case npc_reach_attack:
            return "Reach attack";
        case npc_aim:
            return "Aim";
        case npc_shoot:
            return "Shoot";
        case npc_look_for_player:
            return "Look for player";
        case npc_heal_player:
            return "Heal player or ally";
        case npc_follow_player:
            return "Follow player";
        case npc_follow_embarked:
            return "Follow player (embarked)";
        case npc_talk_to_player:
            return "Talk to player";
        case npc_mug_player:
            return "Mug player";
        case npc_goto_to_this_pos:
            return "Go to position";
        case npc_goto_destination:
            return "Go to destination";
        case npc_avoid_friendly_fire:
            return "Avoid friendly fire";
        case npc_escape_explosion:
            return "Escape explosion";
        case npc_player_activity:
            return "Performing activity";
        default:
            return "Unnamed action";
    }
}
References action, npc_aim, npc_avoid_friendly_fire, npc_drop_items, npc_escape_explosion, npc_flee, npc_follow_embarked, npc_follow_player, npc_goto_destination, npc_goto_to_this_pos, npc_heal, npc_heal_player, npc_investigate_sound, npc_look_for_player, npc_melee, npc_mug_player, npc_pause, npc_pickup, npc_player_activity, npc_reach_attack, npc_reload, npc_return_to_guard_pos, npc_shoot, npc_sleep, npc_talk_to_player, npc_undecided, npc_use_painkiller, and npc_worker_downtime.
Referenced by npc::execute_action(), npc::move(), and print_action().
npc_pickup_from_stack()
template<typename T > std::list< item > npc_pickup_from_stack (npc & who, T & items)
Definition at line 3114 of file npcmove.cpp.
{
    const bool whitelisting = who.has_item_whitelist();
    auto volume_allowed = who.volume_capacity() - who.volume_carried();
    auto weight_allowed = who.weight_capacity() - who.weight_carried();
    auto min_value = whitelisting ? 0 : who.minimum_item_value();
    std::list<item> picked_up;
    for( auto iter = items.begin(); iter != items.end(); ) {
        const item &it = *iter;
        if( it.made_of( LIQUID ) ) {
            iter++;
            continue;
        }
        if( whitelisting && !who.item_whitelisted( it ) ) {
            iter++;
            continue;
        }
        auto volume = it.volume();
        if( volume > volume_allowed ) {
            iter++;
            continue;
        }
        auto weight = it.weight();
        if( weight > weight_allowed ) {
            iter++;
            continue;
        }
        int itval = whitelisting ? 1000 : who.value( it );
        if( itval < min_value ) {
            iter++;
            continue;
        }
        volume_allowed -= volume;
        weight_allowed -= weight;
        picked_up.push_back( it );
        iter = items.erase( iter );
    }
    return picked_up;
}
References npc::has_item_whitelist(), npc::item_whitelisted(), LIQUID, item::made_of(), npc::minimum_item_value(), npc::value(), item::volume(), Character::volume_capacity(), Character::volume_carried(), item::weight(), Character::weight_capacity(), and Character::weight_carried().
Referenced by npc::pick_up_item_map(), and npc::pick_up_item_vehicle().
npc_throw()
static void npc_throw (npc & np, item & it, int index, const tripoint & pos) static
Definition at line 3594 of file npcmove.cpp.
{
    if( get_player_character().sees( np ) ) {
        add_msg( _( "%1$s throws a %2$s." ), np.name, it.tname() );
    }
    int stack_size = -1;
    if( it.count_by_charges() ) {
        stack_size = it.charges;
        it.charges = 1;
    }
    if( !np.is_hallucination() ) { // hallucinations only pretend to throw
        ranged::throw_item( np, pos, it, std::nullopt );
    }
    // Throw a single charge of a stacking object.
    if( stack_size == -1 || stack_size == 1 ) {
        np.i_rem( index );
    } else {
        it.charges = stack_size - 1;
    }
    np.clear_npc_ai_info_cache( npc_ai_info::range );
}
References _, add_msg(), item::charges, Character::clear_npc_ai_info_cache(), item::count_by_charges(), get_player_character(), Character::i_rem(), npc::is_hallucination(), Character::name, range, ranged::throw_item(), and item::tname().
Referenced by npc::alt_attack().
print_action()
void print_action (const char * prepend, npc_action action)
Definition at line 4453 of file npcmove.cpp.
{
    if( action != npc_undecided ) {
        add_msg( m_debug, prepend, npc_action_name( action ) );
    }
}
References action, add_msg(), m_debug, npc_action_name(), and npc_undecided.
Referenced by npc::move().
rate_food()
static float rate_food (const item & it, int want_nutr, int want_quench) static
Definition at line 3878 of file npcmove.cpp.
{
    const auto &food = it.get_comestible();
    if( !food ) {
        return 0.0f;
    }
    if( food->parasites && !it.has_flag( "NO_PARASITES" ) ) {
        return 0.0;
    }
    int nutr = food->get_default_nutr();
    int quench = food->quench;
    if( nutr <= 0 && quench <= 0 ) {
        // Not food - may be salt, drugs etc.
        return 0.0f;
    }
    if( !it.type->use_methods.empty() ) {
        // TODO: Get a good method of telling apart:
        // raw meat (parasites - don't eat unless mutant)
        // zed meat (poison - don't eat unless mutant)
        // alcohol (debuffs, health drop - supplement diet but don't bulk-consume)
        // caffeine (fine to consume, but expensive and prevents sleep)
        // hallucination mushrooms (NPCs don't hallucinate, so don't eat those)
        // honeycomb (harmless iuse)
        // royal jelly (way too expensive to eat as food)
        // mutagenic crap (don't eat, we want player to micromanage muties)
        // marloss (NPCs don't turn fungal)
        // weed brownies (small debuff)
        // seeds (too expensive)
        // For now skip all of those
        return 0.0f;
    }
    double relative_rot = it.get_relative_rot();
    if( relative_rot >= 1.0f ) {
        // TODO: Allow sapro mutants to eat it anyway and make them prefer it
        return 0.0f;
    }
    float weight = std::max( 1.0, 10.0 * relative_rot );
    if( it.get_comestible_fun() < 0 ) {
        // This helps to avoid eating stuff like flour
        weight /= ( -it.get_comestible_fun() ) + 1;
    }
    if( food->healthy < 0 ) {
        weight /= ( -food->healthy ) + 1;
    }
    // Avoid wasting quench values unless it's about to rot away
    if( relative_rot < 0.9f && quench > want_quench ) {
        weight -= ( 1.0f - relative_rot ) * ( quench - want_quench );
    }
    if( quench < 0 && want_quench > 0 && want_nutr < want_quench ) {
        // Avoid stuff that makes us thirsty when we're more thirsty than hungry
        weight = weight * want_nutr / want_quench;
    }
    if( nutr > want_nutr ) {
        // TODO: Allow overeating in some cases
        if( nutr >= 5 ) {
            return 0.0f;
        }
        if( relative_rot < 0.9f ) {
            weight /= nutr - want_nutr;
        }
    }
    if( it.poison > 0 ) {
        weight -= it.poison;
    }
    return weight;
}
References item::get_comestible(), item::get_comestible_fun(), item::get_relative_rot(), item::has_flag(), item::poison, item::type, and itype::use_methods.
Referenced by npc::consume_food().
too_close()
static bool too_close (const tripoint & critter_pos, const tripoint & ally_pos, const int def_radius) static
Definition at line 354 of file npcmove.cpp.
{
    return rl_dist( critter_pos, ally_pos ) <= def_radius;
}
References rl_dist().
Referenced by npc::assess_danger().
wants_to_reload()
static bool wants_to_reload (const npc & who, const item & it) static
Definition at line 1438 of file npcmove.cpp.
{
    if( !who.can_reload( it ) ) {
        return false;
    }
    const int required = it.ammo_required();
    // TODO: Add bandolier check here, once they can be reloaded
    if( required < 1 && !it.is_magazine() ) {
        return false;
    }
    const int remaining = it.ammo_remaining();
    return remaining < required || remaining < it.ammo_capacity();
}
References item::ammo_capacity(), item::ammo_remaining(), item::ammo_required(), Character::can_reload(), and item::is_magazine().
Referenced by npc::can_reload_current(), and npc::find_reloadable().
wants_to_reload_with()
static bool wants_to_reload_with (const item & weap, const item & ammo, bool danger) static
Definition at line 1454 of file npcmove.cpp.
{
    // Only reload loose ammo if gun has integral magazine or not in danger.
    bool combat_reload = !ammo.is_magazine() && ( danger || weap.magazine_integral() );
    // If in danger, only swap magazines if ammo is both greater and it's sufficient for a shot
    // To prevent them from constantly swapping magazines while entering range.
    // If not in danger, swap magazines if ammo is greater than current.
    bool want_swap = ammo.ammo_remaining() > weap.ammo_remaining() && ( !danger ||
                     ammo.ammo_remaining() > weap.ammo_required() );
    return combat_reload || want_swap;
}
References item::ammo_remaining(), item::ammo_required(), item::is_magazine(), and item::magazine_integral().
Referenced by npc::check_or_reload_cbm(), npc::find_reloadable(), and npc::find_usable_ammo().
Variable Documentation
ACT_PULP
const activity_id ACT_PULP("ACT_PULP") ("ACT_PULP") static
Referenced by npc::do_pulp().
bio_ads
const bionic_id bio_ads("bio_ads") ("bio_ads") static
bio_advreactor
const bionic_id bio_advreactor("bio_advreactor") ("bio_advreactor") static
bio_faraday
const bionic_id bio_faraday("bio_faraday") ("bio_faraday") static
bio_furnace
const bionic_id bio_furnace("bio_furnace") ("bio_furnace") static
Referenced by npc::recharge_cbm().
bio_heat_absorb
const bionic_id bio_heat_absorb("bio_heat_absorb") ("bio_heat_absorb") static
Referenced by Character::melee_special_effects().
bio_heatsink
const bionic_id bio_heatsink("bio_heatsink") ("bio_heatsink") static
bio_hydraulics
const bionic_id bio_hydraulics("bio_hydraulics") ("bio_hydraulics") static
Referenced by npc::deactivate_combat_cbms(), and npc::execute_action().
bio_leukocyte
const bionic_id bio_leukocyte("bio_leukocyte") ("bio_leukocyte") static
bio_nanobots
const bionic_id bio_nanobots("bio_nanobots") ("bio_nanobots") static
Referenced by npc::address_needs().
bio_ods
const bionic_id bio_ods("bio_ods") ("bio_ods") static
bio_painkiller
const bionic_id bio_painkiller("bio_painkiller") ("bio_painkiller") static
Referenced by npc::address_needs().
bio_plutfilter
const bionic_id bio_plutfilter("bio_plutfilter") ("bio_plutfilter") static
bio_radscrubber
const bionic_id bio_radscrubber("bio_radscrubber") ("bio_radscrubber") static
Referenced by npc::complain().
bio_reactor
const bionic_id bio_reactor("bio_reactor") ("bio_reactor") static
bio_shock
const bionic_id bio_shock("bio_shock") ("bio_shock") static
bio_soporific
const bionic_id bio_soporific("bio_soporific") ("bio_soporific") static
Referenced by npc::execute_action(), and npc::move_pause().
effect_asthma
const efftype_id effect_asthma("asthma") ("asthma") static
Referenced by npc::heal_self(), and npc::move().
effect_bandaged
const efftype_id effect_bandaged("bandaged") ("bandaged") static
Referenced by npc::patient_assessment().
effect_bite
const efftype_id effect_bite("bite") ("bite") static
Referenced by npc::complain(), and npc::patient_assessment().
effect_bleed
const efftype_id effect_bleed("bleed") ("bleed") static
Referenced by npc::complain(), and npc::patient_assessment().
effect_bouldering
const efftype_id effect_bouldering("bouldering") ("bouldering") static
Referenced by npc::move_to().
effect_catch_up
const efftype_id effect_catch_up("catch_up") ("catch_up") static
Referenced by npc::address_player().
effect_disinfected
const efftype_id effect_disinfected("disinfected") ("disinfected") static
Referenced by npc::patient_assessment().
effect_hallu
const efftype_id effect_hallu("hallu") ("hallu") static
Referenced by npc::address_needs().
effect_hit_by_player
const efftype_id effect_hit_by_player("hit_by_player") ("hit_by_player") static
Referenced by npc::assess_danger().
effect_infected
const efftype_id effect_infected("infected") ("infected") static
Referenced by npc::complain(), and npc::patient_assessment().
effect_lying_down
const efftype_id effect_lying_down("lying_down") ("lying_down") static
Referenced by npc::execute_action().
effect_no_sight
const efftype_id effect_no_sight("no_sight") ("no_sight") static
Referenced by npc::move_to().
effect_npc_fire_bad
const efftype_id effect_npc_fire_bad("npc_fire_bad") ("npc_fire_bad") static
Referenced by npc::assess_danger(), and npc::move().
effect_npc_flee_player
const efftype_id effect_npc_flee_player("npc_flee_player") ("npc_flee_player") static
Referenced by npc::move().
effect_npc_player_looking
const efftype_id effect_npc_player_looking("npc_player_still_looking") ("npc_player_still_looking") static
Referenced by npc::regen_ai_cache().
effect_npc_run_away
const efftype_id effect_npc_run_away("npc_run_away") ("npc_run_away") static
Referenced by npc::assess_danger(), and npc::move().
effect_onfire
const efftype_id effect_onfire("onfire") ("onfire") static
Referenced by npc::move_pause().
effect_stunned
const efftype_id effect_stunned("stunned") ("stunned") static
Referenced by npc::move_to().
flag_NO_UNWIELD
const flag_str_id flag_NO_UNWIELD("NO_UNWIELD") ("NO_UNWIELD") static
Referenced by npc::wield_better_weapon().
itype_battery
const itype_id itype_battery("battery") ("battery") static
Referenced by npc::recharge_cbm().
itype_chem_ethanol
const itype_id itype_chem_ethanol("chem_ethanol") ("chem_ethanol") static
Referenced by npc::recharge_cbm().
itype_chem_methanol
const itype_id itype_chem_methanol("chem_methanol") ("chem_methanol") static
Referenced by npc::recharge_cbm().
itype_denat_alcohol
const itype_id itype_denat_alcohol("denat_alcohol") ("denat_alcohol") static
Referenced by npc::recharge_cbm().
itype_inhaler
const itype_id itype_inhaler("inhaler") ("inhaler") static
Referenced by npc::heal_self(), and npc::move().
itype_lsd
const itype_id itype_lsd("lsd") ("lsd") static
Referenced by npc::find_item().
itype_oxygen_tank
const itype_id itype_oxygen_tank("oxygen_tank") ("oxygen_tank") static
Referenced by npc::heal_self(), and npc::move().
itype_smoxygen_tank
const itype_id itype_smoxygen_tank("smoxygen_tank") ("smoxygen_tank") static
Referenced by npc::heal_self(), and npc::move().
itype_thorazine
const itype_id itype_thorazine("thorazine") ("thorazine") static
Referenced by npc::find_item().
itype_UPS
const itype_id itype_UPS("UPS") ("UPS") static
MAX_FLOAT
constexpr float MAX_FLOAT = 5000000000.0f static constexpr
Definition at line 131 of file npcmove.cpp.
Referenced by npc::good_escape_direction().
NPC_DANGER_MAX
constexpr float NPC_DANGER_MAX = 150.0f static constexpr
Definition at line 130 of file npcmove.cpp.
Referenced by npc::assess_danger(), and npc::evaluate_enemy().
NPC_DANGER_VERY_LOW
constexpr float NPC_DANGER_VERY_LOW = 5.0f static constexpr
Definition at line 129 of file npcmove.cpp.
Referenced by npc::address_needs(), npc::assess_danger(), npc::avoid_friendly_fire(), and npc::regen_ai_cache().
skill_firstaid
const skill_id skill_firstaid("firstaid") ("firstaid") static
Referenced by npc::address_needs().