Cataclysm BN: bionic Struct Reference
bionic Struct Reference
#include <bionics.h>
Public Member Functions
bionic ()
bionic (bionic_id pid, char pinvlet)
const bionic_data & info () const
void set_flag (const std::string &flag)
void remove_flag (const std::string &flag)
bool has_flag (const std::string &flag) const
int get_quality (const quality_id &quality) const
bool is_this_fuel_powered (const itype_id &this_fuel) const
void toggle_safe_fuel_mod ()
void toggle_auto_start_mod ()
void set_auto_start_thresh (float val)
float get_auto_start_thresh () const
bool is_auto_start_on () const
bool is_auto_start_keep_full () const
void serialize (JsonOut &json) const
void deserialize (JsonIn &jsin)
Public Attributes
bionic_id id
int charge_timer = 0
char invlet = 'a'
bool powered = false
itype_id ammo_loaded = itype_id::NULL_ID()
unsigned int ammo_count = 0
time_duration incapacitated_time
units::energy energy_stored = 0_kJ
Private Attributes
cata::flat_set< std::string > bionic_tags
float auto_start_threshold = -1.0
Detailed Description
Definition at line 155 of file bionics.h.
Constructor & Destructor Documentation
bionic() [1/2]
bionic::bionic () inline
Definition at line 168 of file bionics.h.
            : id( "bio_batteries" ), incapacitated_time( 0_turns ) {
        }
bionic() [2/2]
bionic::bionic (bionic_id pid, char pinvlet) inline
Definition at line 171 of file bionics.h.
            : id( pid ), invlet( pinvlet ), incapacitated_time( 0_turns ) { }
Member Function Documentation
deserialize()
void bionic::deserialize (JsonIn & jsin)
Definition at line 2862 of file bionics.cpp.
{
    JsonObject jo = jsin.get_object();
    id = bionic_id( jo.get_string( "id" ) );
    invlet = jo.get_int( "invlet" );
    powered = jo.get_bool( "powered" );
    charge_timer = jo.get_int( "charge" );
    jo.read( "energy_stored", energy_stored, true );
    if( jo.has_string( "ammo_loaded" ) ) {
        jo.read( "ammo_loaded", ammo_loaded, true );
    }
    if( jo.has_int( "ammo_count" ) ) {
        ammo_count = jo.get_int( "ammo_count" );
    }
    if( jo.has_int( "incapacitated_time" ) ) {
        incapacitated_time = 1_turns * jo.get_int( "incapacitated_time" );
    }
    if( jo.has_float( "auto_start_threshold" ) ) {
        auto_start_threshold = jo.get_float( "auto_start_threshold" );
    }
    if( jo.has_array( "bionic_tags" ) ) {
        for( const std::string line : jo.get_array( "bionic_tags" ) ) {
            bionic_tags.insert( line );
        }
    }
}
References ammo_count, ammo_loaded, auto_start_threshold, bionic_id, bionic_tags, charge_timer, energy_stored, JsonObject::get_array(), JsonObject::get_bool(), JsonObject::get_float(), JsonObject::get_int(), JsonIn::get_object(), JsonObject::get_string(), JsonObject::has_array(), JsonObject::has_float(), JsonObject::has_int(), JsonObject::has_string(), incapacitated_time, cata::flat_set< T, Compare, Data >::insert(), invlet, line(), powered, and JsonObject::read().
get_auto_start_thresh()
float bionic::get_auto_start_thresh () const
Definition at line 2824 of file bionics.cpp.
{
    return auto_start_threshold;
}
References auto_start_threshold.
Referenced by build_bionic_poweronly_string(), is_auto_start_keep_full(), is_auto_start_on(), and Character::process_bionic().
get_quality()
int bionic::get_quality (const quality_id & quality) const
Definition at line 2752 of file bionics.cpp.
{
    const auto &i = info();
    if( i.fake_item.is_empty() ) {
        return INT_MIN;
    }
    return item( i.fake_item ).get_quality( quality );
}
References item::get_quality(), and info().
has_flag()
bool bionic::has_flag (const std::string & flag) const
Definition at line 2747 of file bionics.cpp.
{
    return bionic_tags.find( flag ) != bionic_tags.end();
}
References bionic_tags, cata::flat_set< T, Compare, Data >::end(), and cata::flat_set< T, Compare, Data >::find().
Referenced by build_bionic_poweronly_string(), Character::burn_fuel(), and toggle_safe_fuel_mod().
info()
const bionic_data & bionic::info () const inline
Definition at line 174 of file bionics.h.
{
            return *id;
        }
References id.
Referenced by Character::absorb_hit(), Character::activate_bionic(), attempt_recharge(), build_bionic_poweronly_string(), Character::burn_fuel(), npc::check_or_use_weapon_cbm(), Character::deactivate_bionic(), deactivate_weapon_cbm(), draw_bionics_titlebar(), find_reloadable_cbms(), Character::fuel_bionic_with(), Character::get_effective_efficiency(), get_quality(), Character::heat_emission(), is_this_fuel_powered(), anonymous_namespace{bionics_ui.cpp}::bionic_sort_less::operator()(), Character::passive_power_gen(), Character::process_bionic(), show_bionics_ui(), sleep(), toggle_auto_start_mod(), toggle_safe_fuel_mod(), and Character::uninstall_bionic().
is_auto_start_keep_full()
bool bionic::is_auto_start_keep_full () const
Definition at line 2834 of file bionics.cpp.
{
    return get_auto_start_thresh() > 0.99;
}
References get_auto_start_thresh().
Referenced by Character::activate_bionic(), and Character::burn_fuel().
is_auto_start_on()
bool bionic::is_auto_start_on () const
Definition at line 2829 of file bionics.cpp.
{
    return get_auto_start_thresh() > -1.0;
}
References get_auto_start_thresh().
Referenced by build_bionic_poweronly_string(), Character::process_bionic(), serialize(), and toggle_auto_start_mod().
is_this_fuel_powered()
bool bionic::is_this_fuel_powered (const itype_id & this_fuel) const
Definition at line 2762 of file bionics.cpp.
{
    const std::vector<itype_id> fuel_op = info().fuel_opts;
    return std::find( fuel_op.begin(), fuel_op.end(), this_fuel ) != fuel_op.end();
}
References detail::find(), bionic_data::fuel_opts, and info().
Referenced by Character::burn_fuel(), and Character::passive_power_gen().
remove_flag()
void bionic::remove_flag (const std::string & flag)
Definition at line 2742 of file bionics.cpp.
{
    bionic_tags.erase( flag );
}
References bionic_tags, and cata::flat_set< T, Compare, Data >::erase().
Referenced by toggle_safe_fuel_mod().
serialize()
void bionic::serialize (JsonOut & json) const
Definition at line 2839 of file bionics.cpp.
{
    json.start_object();
    json.member( "id", id );
    json.member( "invlet", static_cast<int>( invlet ) );
    json.member( "powered", powered );
    json.member( "charge", charge_timer );
    json.member( "ammo_loaded", ammo_loaded );
    json.member( "ammo_count", ammo_count );
    json.member( "bionic_tags", bionic_tags );
    if( incapacitated_time > 0_turns ) {
        json.member( "incapacitated_time", incapacitated_time );
    }
    if( is_auto_start_on() ) {
        json.member( "auto_start_threshold", auto_start_threshold );
    }
    if( energy_stored > 0_kJ ) {
        json.member( "energy_stored", energy_stored );
    }
    json.end_object();
}
References ammo_count, ammo_loaded, auto_start_threshold, bionic_tags, charge_timer, JsonOut::end_object(), energy_stored, incapacitated_time, invlet, is_auto_start_on(), JsonOut::member(), powered, and JsonOut::start_object().
set_auto_start_thresh()
void bionic::set_auto_start_thresh (float val)
Definition at line 2819 of file bionics.cpp.
{
    auto_start_threshold = val;
}
References auto_start_threshold.
Referenced by toggle_auto_start_mod().
set_flag()
void bionic::set_flag (const std::string & flag)
Definition at line 2737 of file bionics.cpp.
{
    bionic_tags.insert( flag );
}
References bionic_tags, and cata::flat_set< T, Compare, Data >::insert().
Referenced by toggle_safe_fuel_mod().
toggle_auto_start_mod()
void bionic::toggle_auto_start_mod ()
Definition at line 2780 of file bionics.cpp.
{
    if( info().fuel_opts.empty() && !info().is_remote_fueled ) {
        return;
    }
    if( !is_auto_start_on() ) {
        uilist tmenu;
        tmenu.text = _( "Chose Start Power Level Threshold" );
        tmenu.addentry( 1, true, 'o', _( "No Power Left" ) );
        tmenu.addentry( 2, true, 't', _( "Below 25 %%" ) );
        tmenu.addentry( 3, true, 'f', _( "Below 50 %%" ) );
        tmenu.addentry( 4, true, 's', _( "Below 75 %%" ) );
        tmenu.addentry( 5, true, 'a', _( "Below 99 %%" ) );
        tmenu.query();
        switch( tmenu.ret ) {
            case 1:
                set_auto_start_thresh( 0.0 );
                break;
            case 2:
                set_auto_start_thresh( 0.25 );
                break;
            case 3:
                set_auto_start_thresh( 0.5 );
                break;
            case 4:
                set_auto_start_thresh( 0.75 );
                break;
            case 5:
                set_auto_start_thresh( 0.99 );
                break;
            default:
                break;
        }
    } else {
        set_auto_start_thresh( -1.0 );
    }
}
References _, uilist::addentry(), info(), is_auto_start_on(), uilist::query(), uilist::ret, set_auto_start_thresh(), and uilist::text.
Referenced by show_bionics_ui().
toggle_safe_fuel_mod()
void bionic::toggle_safe_fuel_mod ()
Definition at line 2768 of file bionics.cpp.
{
    if( info().fuel_opts.empty() && !info().is_remote_fueled ) {
        return;
    }
    if( !has_flag( flag_SAFE_FUEL_OFF ) ) {
        set_flag( flag_SAFE_FUEL_OFF );
    } else {
        remove_flag( flag_SAFE_FUEL_OFF );
    }
}
References flag_SAFE_FUEL_OFF(), has_flag(), info(), remove_flag(), and set_flag().
Referenced by show_bionics_ui().
Member Data Documentation
ammo_count
unsigned int bionic::ammo_count = 0
Definition at line 163 of file bionics.h.
Referenced by Character::activate_bionic(), npc::check_or_reload_cbm(), Character::deactivate_bionic(), deserialize(), find_reloadable_cbms(), serialize(), and show_bionics_ui().
ammo_loaded
itype_id bionic::ammo_loaded = itype_id::NULL_ID()
Definition at line 161 of file bionics.h.
Referenced by Character::activate_bionic(), npc::check_or_reload_cbm(), Character::deactivate_bionic(), deserialize(), find_reloadable_cbms(), and serialize().
auto_start_threshold
float bionic::auto_start_threshold = -1.0 private
Definition at line 198 of file bionics.h.
Referenced by deserialize(), get_auto_start_thresh(), serialize(), and set_auto_start_thresh().
bionic_tags
cata::flat_set<std::string> bionic::bionic_tags private
Definition at line 197 of file bionics.h.
Referenced by deserialize(), has_flag(), remove_flag(), serialize(), and set_flag().
charge_timer
int bionic::charge_timer = 0
Definition at line 157 of file bionics.h.
Referenced by Character::absorb_hit(), Character::activate_bionic(), attempt_recharge(), deserialize(), Character::process_bionic(), and serialize().
energy_stored
units::energy bionic::energy_stored = 0_kJ
Definition at line 167 of file bionics.h.
Referenced by Character::absorb_hit(), Character::deactivate_bionic(), deserialize(), Character::process_bionic(), and serialize().
id
bionic_id bionic::id
Definition at line 156 of file bionics.h.
Referenced by Character::activate_bionic(), build_bionic_powerdesc_string(), build_bionic_poweronly_string(), Character::burn_fuel(), Character::deactivate_bionic(), draw_bionics_titlebar(), draw_description(), find_reloadable_cbms(), get_bionic_text_color(), info(), Character::passive_power_gen(), Character::process_bionic(), show_bionics_ui(), Character::uninstall_bionic(), and debug_menu::wishbionics().
incapacitated_time
time_duration bionic::incapacitated_time
Definition at line 165 of file bionics.h.
Referenced by Character::absorb_hit(), Character::activate_bionic(), build_bionic_poweronly_string(), Character::deactivate_bionic(), deserialize(), and serialize().
invlet
char bionic::invlet = 'a'
Definition at line 158 of file bionics.h.
Referenced by deserialize(), anonymous_namespace{bionics_ui.cpp}::bionic_sort_less::operator()(), serialize(), and show_bionics_ui().
powered
bool bionic::powered = false
Definition at line 159 of file bionics.h.
Referenced by Character::activate_bionic(), npc::activate_bionic_by_id(), build_bionic_poweronly_string(), Character::burn_fuel(), Character::deactivate_bionic(), npc::deactivate_bionic_by_id(), deactivate_weapon_cbm(), deserialize(), get_bionic_text_color(), Character::process_bionic(), serialize(), show_bionics_ui(), sleep(), Character::uninstall_bionic(), and npc::use_bionic_by_id().
The documentation for this struct was generated from the following files:
src/bionics.h
src/bionics.cpp