Cataclysm BN: scen_blacklist Struct Reference
scen_blacklist Struct Reference
#include <scenario.h>
Public Member Functions
void load (const JsonObject &jo, const std::string &)
void finalize ()
Static Public Member Functions
static void load_scen_blacklist (const JsonObject &jo, const std::string &src)
Public Attributes
std::set< string_id< scenario > > whitelist_scenarios
std::set< string_id< scenario > > blacklist_scenarios
std::set< string_id< scenario > > allowed_scenarios
Detailed Description
Definition at line 118 of file scenario.h.
Member Function Documentation
finalize()
void scen_blacklist::finalize ()
Definition at line 263 of file scenario.cpp.
{
    std::set<string_id<scenario>> all_scen;
    for( const scenario &scen : scenario::get_all() ) {
        all_scen.insert( scen.ident() );
    }
    for( const string_id<scenario> &sc : blacklist_scenarios ) {
        if( all_scen.count( sc ) == 0 ) {
            debugmsg( "Scenario blacklist contains invalid scenario" );
        }
    }
    for( const string_id<scenario> &sc : whitelist_scenarios ) {
        if( all_scen.count( sc ) == 0 ) {
            debugmsg( "Scenario whitelist contains invalid scenario" );
        }
    }
    if( !whitelist_scenarios.empty() ) {
        allowed_scenarios = whitelist_scenarios;
    } else {
        allowed_scenarios = std::move( all_scen );
    }
    for( auto i = allowed_scenarios.begin(); i != allowed_scenarios.end(); ) {
        if( blacklist_scenarios.count( *i ) != 0 ) {
            i = allowed_scenarios.erase( i );
        } else {
            i++;
        }
    }
}
References allowed_scenarios, blacklist_scenarios, debugmsg, scenario::get_all(), avatar_action::move(), and whitelist_scenarios.
Referenced by scenario::check_definitions().
load()
void scen_blacklist::load (const JsonObject & jo, const std::string &)
Definition at line 247 of file scenario.cpp.
{
    const std::string bl_stype = jo.get_string( "subtype" );
    for( const std::string &line : jo.get_array( "scenarios" ) ) {
        if( bl_stype == "whitelist" ) {
            whitelist_scenarios.emplace( line );
        } else if( bl_stype == "blacklist" ) {
            blacklist_scenarios.emplace( line );
        } else {
            jo.throw_error( "Blacklist subtype is not a valid subtype." );
        }
    }
}
References blacklist_scenarios, JsonObject::get_array(), JsonObject::get_string(), line(), JsonObject::throw_error(), and whitelist_scenarios.
Referenced by load_scen_blacklist().
load_scen_blacklist()
void scen_blacklist::load_scen_blacklist (const JsonObject & jo, const std::string & src) static
Definition at line 242 of file scenario.cpp.
{
    sc_blacklist.load( jo, src );
}
References load(), and sc_blacklist.
Referenced by DynamicDataLoader::initialize().
Member Data Documentation
allowed_scenarios
std::set<string_id<scenario> > scen_blacklist::allowed_scenarios
Definition at line 121 of file scenario.h.
Referenced by finalize(), and scenario::scen_is_blacklisted().
blacklist_scenarios
std::set<string_id<scenario> > scen_blacklist::blacklist_scenarios
Definition at line 120 of file scenario.h.
Referenced by finalize(), and load().
whitelist_scenarios
std::set<string_id<scenario> > scen_blacklist::whitelist_scenarios
Definition at line 119 of file scenario.h.
Referenced by finalize(), and load().
The documentation for this struct was generated from the following files:
src/scenario.h
src/scenario.cpp